import { appTitle } from '../plugins/partials.ts';
import { getInputName, type Project } from '../plugins/projects.ts';

/**
 * The files that turn the rendered pages into a standalone Vite project.
 *
 * They are generated rather than copied from a template, because both of them carry data that only the build knows:
 * the literal list of pages (as rollup inputs) and the dependency versions of this package.
 */

/** Dependency versions of a generated project, taken from this package so they never drift apart. */
export type Versions = Record<string, string>;

const dependencyNames = ['@porsche-design-system/components-js', 'tailwindcss'];
const devDependencyNames = ['@tailwindcss/vite', '@types/node', 'lightningcss', 'vite'];

const pick = (versions: Versions, names: string[]): Versions =>
  Object.fromEntries(
    names.map((name) => {
      const version = versions[name];
      if (!version) {
        throw new Error(`[examples] "${name}" is missing from the dependencies of this package`);
      }
      return [name, version];
    })
  );

/** `package.json` of a generated project – the workspace it replaces in the examples repository. */
export const getPackageJson = (project: Project, versions: Versions): string =>
  `${JSON.stringify(
    {
      name: project.packageName,
      version: '0.0.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: pick(versions, dependencyNames),
      devDependencies: pick(versions, devDependencyNames),
    },
    null,
    2
  )}\n`;

/**
 * `vite.config.ts` of a generated project.
 *
 * It injects the Porsche Design System partials into every page – the loader script above all, without which the
 * `p-*` elements never upgrade – and lists its pages as literal rollup inputs, so the build is a plain multi page
 * Vite build with nothing scanning the file tree at config time.
 */
export const getViteConfig = (project: Project, pageDirs: string[]): string => {
  const inputs = pageDirs
    .map(
      (pageDir) =>
        `        '${getInputName(pageDir)}': resolve(import.meta.dirname, 'src/${pageDir ? `${pageDir}/` : ''}index.html'),`
    )
    .join('\n');

  return `// Generated by @porsche-design-system/examples – edit the source of the examples, not this file.
import { resolve } from 'node:path';
import {
  getComponentChunkLinks,
  getFontLinks,
  getIconLinks,
  getLoaderScript,
  getMetaTagsAndIconLinks,
} from '@porsche-design-system/components-js/partials';
import tailwindcss from '@tailwindcss/vite';
import { Features } from 'lightningcss';
import { defineConfig } from 'vite';

const REGEX_HEAD = /<\\/head>/;
const REGEX_BODY = /<\\/body>/;

const transformIndexHtmlPlugin = () => {
  return {
    name: 'html-transform',
    transformIndexHtml(html: string): string {
      // biome-ignore lint/correctness/noUnusedVariables: can be re-enabled when config is extended to support home & nav
      const cspContent = [
        \`default-src 'self' https://cdn.ui.porsche.com\`,
        \`style-src 'self' https://cdn.ui.porsche.com 'unsafe-inline'\`,
        \`script-src 'self' https://cdn.ui.porsche.com \${getLoaderScript({ format: 'sha256' })}\`,
        \`img-src 'self' https://cdn.ui.porsche.com https://porsche-design-system.github.io data:\`, // data: is needed for inline background images, e.g. used in checkbox-wrapper and radio-button-wrapper
        \`media-src 'self' https://porsche-design-system.github.io\`, // the mood videos of the examples are hosted there
      ].join('; ');

      const headPartials = [
        //\`<meta http-equiv="Content-Security-Policy" content="\${cspContent}"/>\`, // disabled due to loading of H&N
        getComponentChunkLinks({ components: ${JSON.stringify(project.components)} }),
        getFontLinks(),
        getIconLinks(),
        getMetaTagsAndIconLinks({ appTitle: '${appTitle}' }),
      ].join('');

      return html.replace(REGEX_HEAD, \`\${headPartials}$&\`).replace(REGEX_BODY, \`\${getLoaderScript()}$&\`);
    },
  };
};

export default defineConfig({
  base: process.env.${project.baseEnvVariable} || '',
  root: 'src',
  publicDir: '../public',
  emptyOutDir: true,
  server: {
    host: true,
  },
  css: {
    transformer: 'lightningcss',
    // Disables light-dark() polyfill of lightningcss which is broken https://github.com/porsche-design-system/porsche-design-system/issues/4257
    lightningcss: {
      exclude: Features.LightDark,
    },
  },
  build: {
    outDir: '../dist/',
    rollupOptions: {
      input: {
${inputs}
      },
    },
  },
  plugins: [transformIndexHtmlPlugin(), tailwindcss()],
});
`;
};
