import { appTitle } from '../plugins/partials.ts';
import { type Category, getPageId, type PageLocation } from '../plugins/projects.ts';

/**
 * The files that turn a rendered page into a standalone Vite project – the one "Open in StackBlitz" hands over.
 *
 * They are generated rather than copied from a template, because both of them carry data that only the build knows:
 * the name of the page, the components its category preloads and the dependency versions of this package.
 */

/** Dependency versions of a generated project, taken from this package so they never drift apart. */
export type Versions = Record<string, string>;

const dependencyNames = ['@porsche-design-system/components-js', 'tailwindcss'];
const devDependencyNames = ['@tailwindcss/vite', '@types/node', 'lightningcss', 'vite'];

const pick = (versions: Versions, names: string[]): Versions =>
  Object.fromEntries(
    names.map((name) => {
      const version = versions[name];
      if (!version) {
        throw new Error(`[examples] "${name}" is missing from the dependencies of this package`);
      }
      return [name, version];
    })
  );

/** `package.json` of the generated project of a page. */
export const getPackageJson = (location: PageLocation, versions: Versions): string =>
  `${JSON.stringify(
    {
      name: `@porsche-design-system/example-${getPageId(location)}`,
      version: '0.0.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: pick(versions, dependencyNames),
      devDependencies: pick(versions, devDependencyNames),
    },
    null,
    2
  )}\n`;

/**
 * `vite.config.ts` of the generated project of a page.
 *
 * It injects the Porsche Design System partials – the loader script above all, without which the `p-*` elements never
 * upgrade. Everything else is Vite's default: the project root is where the config is, and `index.html` next to it is
 * the one input, which is how the project builds in StackBlitz as much as in `scripts/buildSite.ts`.
 */
export const getViteConfig = (
  category: Category
): string => `// Generated by @porsche-design-system/examples – edit the source of the examples, not this file.
import {
  getComponentChunkLinks,
  getFontLinks,
  getIconLinks,
  getLoaderScript,
  getMetaTagsAndIconLinks,
} from '@porsche-design-system/components-js/partials';
import tailwindcss from '@tailwindcss/vite';
import { Features } from 'lightningcss';
import { defineConfig } from 'vite';

const REGEX_HEAD = /<\\/head>/;
const REGEX_BODY = /<\\/body>/;

const transformIndexHtmlPlugin = () => {
  return {
    name: 'html-transform',
    transformIndexHtml(html: string): string {
      // biome-ignore lint/correctness/noUnusedVariables: can be re-enabled when config is extended to support home & nav
      const cspContent = [
        \`default-src 'self' https://cdn.ui.porsche.com\`,
        \`style-src 'self' https://cdn.ui.porsche.com 'unsafe-inline'\`,
        \`script-src 'self' https://cdn.ui.porsche.com \${getLoaderScript({ format: 'sha256' })}\`,
        \`img-src 'self' https://cdn.ui.porsche.com data:\`, // data: is needed for inline background images, e.g. used in checkbox-wrapper and radio-button-wrapper
        \`media-src 'self'\`, // the images and videos of the examples are served by the storefront
      ].join('; ');

      const headPartials = [
        //\`<meta http-equiv="Content-Security-Policy" content="\${cspContent}"/>\`, // disabled due to loading of H&N
        getComponentChunkLinks({ components: ${JSON.stringify(category.components)} }),
        getFontLinks(),
        getIconLinks(),
        getMetaTagsAndIconLinks({ appTitle: '${appTitle}' }),
      ].join('');

      return html.replace(REGEX_HEAD, \`\${headPartials}$&\`).replace(REGEX_BODY, \`\${getLoaderScript()}$&\`);
    },
  };
};

export default defineConfig({
  server: {
    host: true,
  },
  css: {
    transformer: 'lightningcss',
    // Disables light-dark() polyfill of lightningcss which is broken https://github.com/porsche-design-system/porsche-design-system/issues/4257
    lightningcss: {
      exclude: Features.LightDark,
    },
  },
  plugins: [transformIndexHtmlPlugin(), tailwindcss()],
});
`;
