/* Auto Generated File */
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'page-typography-latin-U+2000-26FF',
  styles: [
    `
      h2,
      h4 {
        color: deeppink;
      }
    
      p-text {
        display: inline-block;
        text-align: center;
        vertical-align: top;
        margin: 4px;
        padding: 4px;
        background: #f1f1f1;
        width: 36px;
        height: 36px;
      }
    `,
  ],
  template: `
    <div class="playground" title="should show typography in basic latin charset">
      <h2>Porsche Next Latin</h2>
      <h4>Range: U+2000-206F ("General Punctuation")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+2000 | Dec:8192"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2001 | Dec:8193"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2002 | Dec:8194">&ensp;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2003 | Dec:8195">&emsp;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2004 | Dec:8196"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2005 | Dec:8197"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2006 | Dec:8198"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2007 | Dec:8199"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2008 | Dec:8200"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2009 | Dec:8201">&thinsp;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+200A | Dec:8202">&#8202;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+200B | Dec:8203">&#8203;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+200C | Dec:8204">&zwnj;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+200D | Dec:8205">&zwj;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+200E | Dec:8206">&lrm;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+200F | Dec:8207">&rlm;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2010 | Dec:8208">‐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2011 | Dec:8209">‑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2012 | Dec:8210">‒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2013 | Dec:8211">–</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2014 | Dec:8212">—</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2015 | Dec:8213">―</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2016 | Dec:8214">‖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2017 | Dec:8215">‗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2018 | Dec:8216">‘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2019 | Dec:8217">’</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+201A | Dec:8218">‚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+201B | Dec:8219">‛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+201C | Dec:8220">“</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+201D | Dec:8221">”</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+201E | Dec:8222">„</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+201F | Dec:8223">‟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2020 | Dec:8224">†</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2021 | Dec:8225">‡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2022 | Dec:8226">•</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2023 | Dec:8227">‣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2024 | Dec:8228">․</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2025 | Dec:8229">‥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2026 | Dec:8230">…</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2027 | Dec:8231">‧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2028 | Dec:8232"></p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2029 | Dec:8233"></p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+202A | Dec:8234">&#8234;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+202B | Dec:8235">&#8235;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+202C | Dec:8236">&#8236;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+202D | Dec:8237">&#8237;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+202E | Dec:8238">&#8238;</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+202F | Dec:8239"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2030 | Dec:8240">‰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2031 | Dec:8241">‱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2032 | Dec:8242">′</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2033 | Dec:8243">″</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2034 | Dec:8244">‴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2035 | Dec:8245">‵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2036 | Dec:8246">‶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2037 | Dec:8247">‷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2038 | Dec:8248">‸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2039 | Dec:8249">‹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+203A | Dec:8250">›</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+203B | Dec:8251">※</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+203C | Dec:8252">‼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+203D | Dec:8253">‽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+203E | Dec:8254">‾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+203F | Dec:8255">‿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2040 | Dec:8256">⁀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2041 | Dec:8257">⁁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2042 | Dec:8258">⁂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2043 | Dec:8259">⁃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2044 | Dec:8260">⁄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2045 | Dec:8261">⁅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2046 | Dec:8262">⁆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2047 | Dec:8263">⁇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2048 | Dec:8264">⁈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2049 | Dec:8265">⁉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+204A | Dec:8266">⁊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+204B | Dec:8267">⁋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+204C | Dec:8268">⁌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+204D | Dec:8269">⁍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+204E | Dec:8270">⁎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+204F | Dec:8271">⁏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2050 | Dec:8272">⁐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2051 | Dec:8273">⁑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2052 | Dec:8274">⁒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2053 | Dec:8275">⁓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2054 | Dec:8276">⁔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2055 | Dec:8277">⁕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2056 | Dec:8278">⁖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2057 | Dec:8279">⁗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2058 | Dec:8280">⁘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2059 | Dec:8281">⁙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+205A | Dec:8282">⁚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+205B | Dec:8283">⁛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+205C | Dec:8284">⁜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+205D | Dec:8285">⁝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+205E | Dec:8286">⁞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+205F | Dec:8287"> </p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2060 | Dec:8288">⁠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2061 | Dec:8289">⁡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2062 | Dec:8290">⁢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2063 | Dec:8291">⁣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2064 | Dec:8292">⁤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2065 | Dec:8293">⁥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2066 | Dec:8294">⁦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2067 | Dec:8295">⁧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2068 | Dec:8296">⁨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2069 | Dec:8297">⁩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+206A | Dec:8298">⁪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+206B | Dec:8299">⁫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+206C | Dec:8300">⁬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+206D | Dec:8301">⁭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+206E | Dec:8302">⁮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+206F | Dec:8303">⁯</p-text>
      <h4>Range: U+2070-209F ("Superscripts and Subscripts")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+2070 | Dec:8304">⁰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2071 | Dec:8305">ⁱ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2072 | Dec:8306">⁲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2073 | Dec:8307">⁳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2074 | Dec:8308">⁴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2075 | Dec:8309">⁵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2076 | Dec:8310">⁶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2077 | Dec:8311">⁷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2078 | Dec:8312">⁸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2079 | Dec:8313">⁹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+207A | Dec:8314">⁺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+207B | Dec:8315">⁻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+207C | Dec:8316">⁼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+207D | Dec:8317">⁽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+207E | Dec:8318">⁾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+207F | Dec:8319">ⁿ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2080 | Dec:8320">₀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2081 | Dec:8321">₁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2082 | Dec:8322">₂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2083 | Dec:8323">₃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2084 | Dec:8324">₄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2085 | Dec:8325">₅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2086 | Dec:8326">₆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2087 | Dec:8327">₇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2088 | Dec:8328">₈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2089 | Dec:8329">₉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+208A | Dec:8330">₊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+208B | Dec:8331">₋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+208C | Dec:8332">₌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+208D | Dec:8333">₍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+208E | Dec:8334">₎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+208F | Dec:8335">₏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2090 | Dec:8336">ₐ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2091 | Dec:8337">ₑ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2092 | Dec:8338">ₒ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2093 | Dec:8339">ₓ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2094 | Dec:8340">ₔ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2095 | Dec:8341">ₕ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2096 | Dec:8342">ₖ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2097 | Dec:8343">ₗ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2098 | Dec:8344">ₘ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2099 | Dec:8345">ₙ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+209A | Dec:8346">ₚ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+209B | Dec:8347">ₛ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+209C | Dec:8348">ₜ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+209D | Dec:8349">₝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+209E | Dec:8350">₞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+209F | Dec:8351">₟</p-text>

      <h4>Range: U+20A0-20CF ("Currency Symbols")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A0 | Dec:8352">₠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A1 | Dec:8353">₡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A2 | Dec:8354">₢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A3 | Dec:8355">₣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A4 | Dec:8356">₤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A5 | Dec:8357">₥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A6 | Dec:8358">₦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A7 | Dec:8359">₧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A8 | Dec:8360">₨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20A9 | Dec:8361">₩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20AA | Dec:8362">₪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20AB | Dec:8363">₫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20AC | Dec:8364">€</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20AD | Dec:8365">₭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20AE | Dec:8366">₮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20AF | Dec:8367">₯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B0 | Dec:8368">₰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B1 | Dec:8369">₱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B2 | Dec:8370">₲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B3 | Dec:8371">₳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B4 | Dec:8372">₴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B5 | Dec:8373">₵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B6 | Dec:8374">₶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B7 | Dec:8375">₷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B8 | Dec:8376">₸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20B9 | Dec:8377">₹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20BA | Dec:8378">₺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20BB | Dec:8379">₻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20BC | Dec:8380">₼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20BD | Dec:8381">₽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20BE | Dec:8382">₾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20BF | Dec:8383">₿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C0 | Dec:8384">⃀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C1 | Dec:8385">⃁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C2 | Dec:8386">⃂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C3 | Dec:8387">⃃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C4 | Dec:8388">⃄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C5 | Dec:8389">⃅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C6 | Dec:8390">⃆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C7 | Dec:8391">⃇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C8 | Dec:8392">⃈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20C9 | Dec:8393">⃉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20CA | Dec:8394">⃊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20CB | Dec:8395">⃋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20CC | Dec:8396">⃌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20CD | Dec:8397">⃍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20CE | Dec:8398">⃎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+20CF | Dec:8399">⃏</p-text>

      <h4>Range: U+2100-214F ("Letterlike Symbols")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+2100 | Dec:8448">℀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2101 | Dec:8449">℁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2102 | Dec:8450">ℂ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2103 | Dec:8451">℃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2104 | Dec:8452">℄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2105 | Dec:8453">℅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2106 | Dec:8454">℆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2107 | Dec:8455">ℇ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2108 | Dec:8456">℈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2109 | Dec:8457">℉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+210A | Dec:8458">ℊ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+210B | Dec:8459">ℋ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+210C | Dec:8460">ℌ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+210D | Dec:8461">ℍ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+210E | Dec:8462">ℎ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+210F | Dec:8463">ℏ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2110 | Dec:8464">ℐ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2111 | Dec:8465">ℑ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2112 | Dec:8466">ℒ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2113 | Dec:8467">ℓ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2114 | Dec:8468">℔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2115 | Dec:8469">ℕ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2116 | Dec:8470">№</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2117 | Dec:8471">℗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2118 | Dec:8472">℘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2119 | Dec:8473">ℙ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+211A | Dec:8474">ℚ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+211B | Dec:8475">ℛ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+211C | Dec:8476">ℜ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+211D | Dec:8477">ℝ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+211E | Dec:8478">℞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+211F | Dec:8479">℟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2120 | Dec:8480">℠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2121 | Dec:8481">℡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2122 | Dec:8482">™</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2123 | Dec:8483">℣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2124 | Dec:8484">ℤ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2125 | Dec:8485">℥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2126 | Dec:8486">Ω</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2127 | Dec:8487">℧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2128 | Dec:8488">ℨ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2129 | Dec:8489">℩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+212A | Dec:8490">K</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+212B | Dec:8491">Å</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+212C | Dec:8492">ℬ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+212D | Dec:8493">ℭ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+212E | Dec:8494">℮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+212F | Dec:8495">ℯ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2130 | Dec:8496">ℰ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2131 | Dec:8497">ℱ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2132 | Dec:8498">Ⅎ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2133 | Dec:8499">ℳ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2134 | Dec:8500">ℴ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2135 | Dec:8501">ℵ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2136 | Dec:8502">ℶ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2137 | Dec:8503">ℷ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2138 | Dec:8504">ℸ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2139 | Dec:8505">ℹ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+213A | Dec:8506">℺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+213B | Dec:8507">℻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+213C | Dec:8508">ℼ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+213D | Dec:8509">ℽ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+213E | Dec:8510">ℾ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+213F | Dec:8511">ℿ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2140 | Dec:8512">⅀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2141 | Dec:8513">⅁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2142 | Dec:8514">⅂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2143 | Dec:8515">⅃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2144 | Dec:8516">⅄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2145 | Dec:8517">ⅅ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2146 | Dec:8518">ⅆ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2147 | Dec:8519">ⅇ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2148 | Dec:8520">ⅈ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2149 | Dec:8521">ⅉ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+214A | Dec:8522">⅊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+214B | Dec:8523">⅋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+214C | Dec:8524">⅌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+214D | Dec:8525">⅍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+214E | Dec:8526">ⅎ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+214F | Dec:8527">⅏</p-text>

      <h4>Range: U+2150-218F ("Number Forms")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+2150 | Dec:8528">⅐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2151 | Dec:8529">⅑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2152 | Dec:8530">⅒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2153 | Dec:8531">⅓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2154 | Dec:8532">⅔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2155 | Dec:8533">⅕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2156 | Dec:8534">⅖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2157 | Dec:8535">⅗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2158 | Dec:8536">⅘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2159 | Dec:8537">⅙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+215A | Dec:8538">⅚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+215B | Dec:8539">⅛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+215C | Dec:8540">⅜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+215D | Dec:8541">⅝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+215E | Dec:8542">⅞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+215F | Dec:8543">⅟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2160 | Dec:8544">Ⅰ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2161 | Dec:8545">Ⅱ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2162 | Dec:8546">Ⅲ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2163 | Dec:8547">Ⅳ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2164 | Dec:8548">Ⅴ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2165 | Dec:8549">Ⅵ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2166 | Dec:8550">Ⅶ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2167 | Dec:8551">Ⅷ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2168 | Dec:8552">Ⅸ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2169 | Dec:8553">Ⅹ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+216A | Dec:8554">Ⅺ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+216B | Dec:8555">Ⅻ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+216C | Dec:8556">Ⅼ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+216D | Dec:8557">Ⅽ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+216E | Dec:8558">Ⅾ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+216F | Dec:8559">Ⅿ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2170 | Dec:8560">ⅰ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2171 | Dec:8561">ⅱ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2172 | Dec:8562">ⅲ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2173 | Dec:8563">ⅳ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2174 | Dec:8564">ⅴ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2175 | Dec:8565">ⅵ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2176 | Dec:8566">ⅶ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2177 | Dec:8567">ⅷ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2178 | Dec:8568">ⅸ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2179 | Dec:8569">ⅹ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+217A | Dec:8570">ⅺ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+217B | Dec:8571">ⅻ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+217C | Dec:8572">ⅼ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+217D | Dec:8573">ⅽ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+217E | Dec:8574">ⅾ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+217F | Dec:8575">ⅿ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2180 | Dec:8576">ↀ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2181 | Dec:8577">ↁ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2182 | Dec:8578">ↂ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2183 | Dec:8579">Ↄ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2184 | Dec:8580">ↄ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2185 | Dec:8581">ↅ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2186 | Dec:8582">ↆ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2187 | Dec:8583">ↇ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2188 | Dec:8584">ↈ</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2189 | Dec:8585">↉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+218A | Dec:8586">↊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+218B | Dec:8587">↋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+218C | Dec:8588">↌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+218D | Dec:8589">↍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+218E | Dec:8590">↎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+218F | Dec:8591">↏</p-text>

      <h4>Range: U+2190-21FF ("Arrows")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+2190 | Dec:8592">←</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2191 | Dec:8593">↑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2192 | Dec:8594">→</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2193 | Dec:8595">↓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2194 | Dec:8596">↔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2195 | Dec:8597">↕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2196 | Dec:8598">↖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2197 | Dec:8599">↗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2198 | Dec:8600">↘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2199 | Dec:8601">↙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+219A | Dec:8602">↚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+219B | Dec:8603">↛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+219C | Dec:8604">↜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+219D | Dec:8605">↝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+219E | Dec:8606">↞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+219F | Dec:8607">↟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A0 | Dec:8608">↠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A1 | Dec:8609">↡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A2 | Dec:8610">↢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A3 | Dec:8611">↣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A4 | Dec:8612">↤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A5 | Dec:8613">↥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A6 | Dec:8614">↦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A7 | Dec:8615">↧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A8 | Dec:8616">↨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21A9 | Dec:8617">↩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21AA | Dec:8618">↪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21AB | Dec:8619">↫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21AC | Dec:8620">↬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21AD | Dec:8621">↭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21AE | Dec:8622">↮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21AF | Dec:8623">↯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B0 | Dec:8624">↰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B1 | Dec:8625">↱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B2 | Dec:8626">↲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B3 | Dec:8627">↳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B4 | Dec:8628">↴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B5 | Dec:8629">↵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B6 | Dec:8630">↶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B7 | Dec:8631">↷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B8 | Dec:8632">↸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21B9 | Dec:8633">↹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21BA | Dec:8634">↺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21BB | Dec:8635">↻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21BC | Dec:8636">↼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21BD | Dec:8637">↽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21BE | Dec:8638">↾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21BF | Dec:8639">↿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C0 | Dec:8640">⇀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C1 | Dec:8641">⇁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C2 | Dec:8642">⇂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C3 | Dec:8643">⇃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C4 | Dec:8644">⇄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C5 | Dec:8645">⇅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C6 | Dec:8646">⇆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C7 | Dec:8647">⇇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C8 | Dec:8648">⇈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21C9 | Dec:8649">⇉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21CA | Dec:8650">⇊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21CB | Dec:8651">⇋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21CC | Dec:8652">⇌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21CD | Dec:8653">⇍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21CE | Dec:8654">⇎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21CF | Dec:8655">⇏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D0 | Dec:8656">⇐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D1 | Dec:8657">⇑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D2 | Dec:8658">⇒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D3 | Dec:8659">⇓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D4 | Dec:8660">⇔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D5 | Dec:8661">⇕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D6 | Dec:8662">⇖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D7 | Dec:8663">⇗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D8 | Dec:8664">⇘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21D9 | Dec:8665">⇙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21DA | Dec:8666">⇚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21DB | Dec:8667">⇛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21DC | Dec:8668">⇜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21DD | Dec:8669">⇝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21DE | Dec:8670">⇞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21DF | Dec:8671">⇟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E0 | Dec:8672">⇠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E1 | Dec:8673">⇡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E2 | Dec:8674">⇢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E3 | Dec:8675">⇣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E4 | Dec:8676">⇤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E5 | Dec:8677">⇥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E6 | Dec:8678">⇦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E7 | Dec:8679">⇧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E8 | Dec:8680">⇨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21E9 | Dec:8681">⇩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21EA | Dec:8682">⇪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21EB | Dec:8683">⇫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21EC | Dec:8684">⇬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21ED | Dec:8685">⇭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21EE | Dec:8686">⇮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21EF | Dec:8687">⇯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F0 | Dec:8688">⇰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F1 | Dec:8689">⇱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F2 | Dec:8690">⇲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F3 | Dec:8691">⇳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F4 | Dec:8692">⇴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F5 | Dec:8693">⇵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F6 | Dec:8694">⇶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F7 | Dec:8695">⇷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F8 | Dec:8696">⇸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21F9 | Dec:8697">⇹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21FA | Dec:8698">⇺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21FB | Dec:8699">⇻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21FC | Dec:8700">⇼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21FD | Dec:8701">⇽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21FE | Dec:8702">⇾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+21FF | Dec:8703">⇿</p-text>

      <h4>Range: U+2200-22FF ("Mathematical Operators")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+2200 | Dec:8704">∀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2201 | Dec:8705">∁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2202 | Dec:8706">∂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2203 | Dec:8707">∃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2204 | Dec:8708">∄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2205 | Dec:8709">∅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2206 | Dec:8710">∆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2207 | Dec:8711">∇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2208 | Dec:8712">∈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2209 | Dec:8713">∉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+220A | Dec:8714">∊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+220B | Dec:8715">∋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+220C | Dec:8716">∌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+220D | Dec:8717">∍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+220E | Dec:8718">∎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+220F | Dec:8719">∏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2210 | Dec:8720">∐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2211 | Dec:8721">∑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2212 | Dec:8722">−</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2213 | Dec:8723">∓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2214 | Dec:8724">∔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2215 | Dec:8725">∕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2216 | Dec:8726">∖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2217 | Dec:8727">∗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2218 | Dec:8728">∘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2219 | Dec:8729">∙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+221A | Dec:8730">√</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+221B | Dec:8731">∛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+221C | Dec:8732">∜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+221D | Dec:8733">∝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+221E | Dec:8734">∞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+221F | Dec:8735">∟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2220 | Dec:8736">∠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2221 | Dec:8737">∡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2222 | Dec:8738">∢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2223 | Dec:8739">∣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2224 | Dec:8740">∤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2225 | Dec:8741">∥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2226 | Dec:8742">∦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2227 | Dec:8743">∧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2228 | Dec:8744">∨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2229 | Dec:8745">∩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+222A | Dec:8746">∪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+222B | Dec:8747">∫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+222C | Dec:8748">∬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+222D | Dec:8749">∭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+222E | Dec:8750">∮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+222F | Dec:8751">∯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2230 | Dec:8752">∰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2231 | Dec:8753">∱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2232 | Dec:8754">∲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2233 | Dec:8755">∳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2234 | Dec:8756">∴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2235 | Dec:8757">∵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2236 | Dec:8758">∶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2237 | Dec:8759">∷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2238 | Dec:8760">∸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2239 | Dec:8761">∹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+223A | Dec:8762">∺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+223B | Dec:8763">∻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+223C | Dec:8764">∼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+223D | Dec:8765">∽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+223E | Dec:8766">∾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+223F | Dec:8767">∿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2240 | Dec:8768">≀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2241 | Dec:8769">≁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2242 | Dec:8770">≂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2243 | Dec:8771">≃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2244 | Dec:8772">≄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2245 | Dec:8773">≅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2246 | Dec:8774">≆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2247 | Dec:8775">≇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2248 | Dec:8776">≈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2249 | Dec:8777">≉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+224A | Dec:8778">≊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+224B | Dec:8779">≋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+224C | Dec:8780">≌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+224D | Dec:8781">≍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+224E | Dec:8782">≎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+224F | Dec:8783">≏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2250 | Dec:8784">≐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2251 | Dec:8785">≑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2252 | Dec:8786">≒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2253 | Dec:8787">≓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2254 | Dec:8788">≔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2255 | Dec:8789">≕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2256 | Dec:8790">≖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2257 | Dec:8791">≗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2258 | Dec:8792">≘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2259 | Dec:8793">≙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+225A | Dec:8794">≚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+225B | Dec:8795">≛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+225C | Dec:8796">≜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+225D | Dec:8797">≝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+225E | Dec:8798">≞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+225F | Dec:8799">≟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2260 | Dec:8800">≠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2261 | Dec:8801">≡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2262 | Dec:8802">≢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2263 | Dec:8803">≣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2264 | Dec:8804">≤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2265 | Dec:8805">≥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2266 | Dec:8806">≦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2267 | Dec:8807">≧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2268 | Dec:8808">≨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2269 | Dec:8809">≩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+226A | Dec:8810">≪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+226B | Dec:8811">≫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+226C | Dec:8812">≬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+226D | Dec:8813">≭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+226E | Dec:8814">≮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+226F | Dec:8815">≯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2270 | Dec:8816">≰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2271 | Dec:8817">≱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2272 | Dec:8818">≲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2273 | Dec:8819">≳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2274 | Dec:8820">≴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2275 | Dec:8821">≵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2276 | Dec:8822">≶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2277 | Dec:8823">≷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2278 | Dec:8824">≸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2279 | Dec:8825">≹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+227A | Dec:8826">≺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+227B | Dec:8827">≻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+227C | Dec:8828">≼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+227D | Dec:8829">≽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+227E | Dec:8830">≾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+227F | Dec:8831">≿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2280 | Dec:8832">⊀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2281 | Dec:8833">⊁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2282 | Dec:8834">⊂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2283 | Dec:8835">⊃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2284 | Dec:8836">⊄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2285 | Dec:8837">⊅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2286 | Dec:8838">⊆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2287 | Dec:8839">⊇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2288 | Dec:8840">⊈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2289 | Dec:8841">⊉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+228A | Dec:8842">⊊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+228B | Dec:8843">⊋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+228C | Dec:8844">⊌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+228D | Dec:8845">⊍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+228E | Dec:8846">⊎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+228F | Dec:8847">⊏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2290 | Dec:8848">⊐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2291 | Dec:8849">⊑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2292 | Dec:8850">⊒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2293 | Dec:8851">⊓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2294 | Dec:8852">⊔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2295 | Dec:8853">⊕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2296 | Dec:8854">⊖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2297 | Dec:8855">⊗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2298 | Dec:8856">⊘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2299 | Dec:8857">⊙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+229A | Dec:8858">⊚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+229B | Dec:8859">⊛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+229C | Dec:8860">⊜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+229D | Dec:8861">⊝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+229E | Dec:8862">⊞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+229F | Dec:8863">⊟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A0 | Dec:8864">⊠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A1 | Dec:8865">⊡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A2 | Dec:8866">⊢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A3 | Dec:8867">⊣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A4 | Dec:8868">⊤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A5 | Dec:8869">⊥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A6 | Dec:8870">⊦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A7 | Dec:8871">⊧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A8 | Dec:8872">⊨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22A9 | Dec:8873">⊩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22AA | Dec:8874">⊪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22AB | Dec:8875">⊫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22AC | Dec:8876">⊬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22AD | Dec:8877">⊭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22AE | Dec:8878">⊮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22AF | Dec:8879">⊯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B0 | Dec:8880">⊰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B1 | Dec:8881">⊱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B2 | Dec:8882">⊲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B3 | Dec:8883">⊳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B4 | Dec:8884">⊴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B5 | Dec:8885">⊵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B6 | Dec:8886">⊶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B7 | Dec:8887">⊷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B8 | Dec:8888">⊸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22B9 | Dec:8889">⊹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22BA | Dec:8890">⊺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22BB | Dec:8891">⊻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22BC | Dec:8892">⊼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22BD | Dec:8893">⊽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22BE | Dec:8894">⊾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22BF | Dec:8895">⊿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C0 | Dec:8896">⋀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C1 | Dec:8897">⋁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C2 | Dec:8898">⋂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C3 | Dec:8899">⋃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C4 | Dec:8900">⋄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C5 | Dec:8901">⋅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C6 | Dec:8902">⋆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C7 | Dec:8903">⋇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C8 | Dec:8904">⋈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22C9 | Dec:8905">⋉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22CA | Dec:8906">⋊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22CB | Dec:8907">⋋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22CC | Dec:8908">⋌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22CD | Dec:8909">⋍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22CE | Dec:8910">⋎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22CF | Dec:8911">⋏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D0 | Dec:8912">⋐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D1 | Dec:8913">⋑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D2 | Dec:8914">⋒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D3 | Dec:8915">⋓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D4 | Dec:8916">⋔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D5 | Dec:8917">⋕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D6 | Dec:8918">⋖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D7 | Dec:8919">⋗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D8 | Dec:8920">⋘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22D9 | Dec:8921">⋙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22DA | Dec:8922">⋚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22DB | Dec:8923">⋛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22DC | Dec:8924">⋜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22DD | Dec:8925">⋝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22DE | Dec:8926">⋞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22DF | Dec:8927">⋟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E0 | Dec:8928">⋠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E1 | Dec:8929">⋡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E2 | Dec:8930">⋢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E3 | Dec:8931">⋣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E4 | Dec:8932">⋤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E5 | Dec:8933">⋥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E6 | Dec:8934">⋦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E7 | Dec:8935">⋧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E8 | Dec:8936">⋨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22E9 | Dec:8937">⋩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22EA | Dec:8938">⋪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22EB | Dec:8939">⋫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22EC | Dec:8940">⋬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22ED | Dec:8941">⋭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22EE | Dec:8942">⋮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22EF | Dec:8943">⋯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F0 | Dec:8944">⋰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F1 | Dec:8945">⋱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F2 | Dec:8946">⋲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F3 | Dec:8947">⋳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F4 | Dec:8948">⋴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F5 | Dec:8949">⋵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F6 | Dec:8950">⋶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F7 | Dec:8951">⋷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F8 | Dec:8952">⋸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22F9 | Dec:8953">⋹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22FA | Dec:8954">⋺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22FB | Dec:8955">⋻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22FC | Dec:8956">⋼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22FD | Dec:8957">⋽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22FE | Dec:8958">⋾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+22FF | Dec:8959">⋿</p-text>

      <h4>Range: U+25A0-25FF ("Geometric Shapes")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A0 | Dec:9632">■</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A1 | Dec:9633">□</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A2 | Dec:9634">▢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A3 | Dec:9635">▣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A4 | Dec:9636">▤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A5 | Dec:9637">▥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A6 | Dec:9638">▦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A7 | Dec:9639">▧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A8 | Dec:9640">▨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25A9 | Dec:9641">▩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25AA | Dec:9642">▪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25AB | Dec:9643">▫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25AC | Dec:9644">▬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25AD | Dec:9645">▭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25AE | Dec:9646">▮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25AF | Dec:9647">▯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B0 | Dec:9648">▰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B1 | Dec:9649">▱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B2 | Dec:9650">▲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B3 | Dec:9651">△</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B4 | Dec:9652">▴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B5 | Dec:9653">▵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B6 | Dec:9654">▶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B7 | Dec:9655">▷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B8 | Dec:9656">▸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25B9 | Dec:9657">▹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25BA | Dec:9658">►</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25BB | Dec:9659">▻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25BC | Dec:9660">▼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25BD | Dec:9661">▽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25BE | Dec:9662">▾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25BF | Dec:9663">▿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C0 | Dec:9664">◀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C1 | Dec:9665">◁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C2 | Dec:9666">◂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C3 | Dec:9667">◃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C4 | Dec:9668">◄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C5 | Dec:9669">◅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C6 | Dec:9670">◆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C7 | Dec:9671">◇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C8 | Dec:9672">◈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25C9 | Dec:9673">◉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25CA | Dec:9674">◊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25CB | Dec:9675">○</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25CC | Dec:9676">◌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25CD | Dec:9677">◍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25CE | Dec:9678">◎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25CF | Dec:9679">●</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D0 | Dec:9680">◐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D1 | Dec:9681">◑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D2 | Dec:9682">◒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D3 | Dec:9683">◓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D4 | Dec:9684">◔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D5 | Dec:9685">◕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D6 | Dec:9686">◖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D7 | Dec:9687">◗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D8 | Dec:9688">◘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25D9 | Dec:9689">◙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25DA | Dec:9690">◚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25DB | Dec:9691">◛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25DC | Dec:9692">◜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25DD | Dec:9693">◝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25DE | Dec:9694">◞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25DF | Dec:9695">◟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E0 | Dec:9696">◠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E1 | Dec:9697">◡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E2 | Dec:9698">◢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E3 | Dec:9699">◣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E4 | Dec:9700">◤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E5 | Dec:9701">◥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E6 | Dec:9702">◦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E7 | Dec:9703">◧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E8 | Dec:9704">◨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25E9 | Dec:9705">◩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25EA | Dec:9706">◪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25EB | Dec:9707">◫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25EC | Dec:9708">◬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25ED | Dec:9709">◭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25EE | Dec:9710">◮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25EF | Dec:9711">◯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F0 | Dec:9712">◰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F1 | Dec:9713">◱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F2 | Dec:9714">◲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F3 | Dec:9715">◳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F4 | Dec:9716">◴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F5 | Dec:9717">◵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F6 | Dec:9718">◶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F7 | Dec:9719">◷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F8 | Dec:9720">◸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25F9 | Dec:9721">◹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25FA | Dec:9722">◺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25FB | Dec:9723">◻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25FC | Dec:9724">◼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25FD | Dec:9725">◽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25FE | Dec:9726">◾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+25FF | Dec:9727">◿</p-text>

      <h4>Range: U+2600-26FF ("Miscellaneous Symbols")</h4>
      <p-text [size]="'medium'" [align]="'center'" title="U+2600 | Dec:9728">☀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2601 | Dec:9729">☁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2602 | Dec:9730">☂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2603 | Dec:9731">☃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2604 | Dec:9732">☄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2605 | Dec:9733">★</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2606 | Dec:9734">☆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2607 | Dec:9735">☇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2608 | Dec:9736">☈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2609 | Dec:9737">☉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+260A | Dec:9738">☊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+260B | Dec:9739">☋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+260C | Dec:9740">☌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+260D | Dec:9741">☍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+260E | Dec:9742">☎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+260F | Dec:9743">☏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2610 | Dec:9744">☐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2611 | Dec:9745">☑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2612 | Dec:9746">☒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2613 | Dec:9747">☓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2614 | Dec:9748">☔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2615 | Dec:9749">☕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2616 | Dec:9750">☖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2617 | Dec:9751">☗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2618 | Dec:9752">☘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2619 | Dec:9753">☙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+261A | Dec:9754">☚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+261B | Dec:9755">☛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+261C | Dec:9756">☜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+261D | Dec:9757">☝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+261E | Dec:9758">☞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+261F | Dec:9759">☟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2620 | Dec:9760">☠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2621 | Dec:9761">☡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2622 | Dec:9762">☢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2623 | Dec:9763">☣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2624 | Dec:9764">☤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2625 | Dec:9765">☥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2626 | Dec:9766">☦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2627 | Dec:9767">☧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2628 | Dec:9768">☨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2629 | Dec:9769">☩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+262A | Dec:9770">☪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+262B | Dec:9771">☫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+262C | Dec:9772">☬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+262D | Dec:9773">☭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+262E | Dec:9774">☮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+262F | Dec:9775">☯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2630 | Dec:9776">☰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2631 | Dec:9777">☱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2632 | Dec:9778">☲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2633 | Dec:9779">☳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2634 | Dec:9780">☴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2635 | Dec:9781">☵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2636 | Dec:9782">☶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2637 | Dec:9783">☷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2638 | Dec:9784">☸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2639 | Dec:9785">☹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+263A | Dec:9786">☺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+263B | Dec:9787">☻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+263C | Dec:9788">☼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+263D | Dec:9789">☽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+263E | Dec:9790">☾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+263F | Dec:9791">☿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2640 | Dec:9792">♀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2641 | Dec:9793">♁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2642 | Dec:9794">♂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2643 | Dec:9795">♃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2644 | Dec:9796">♄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2645 | Dec:9797">♅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2646 | Dec:9798">♆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2647 | Dec:9799">♇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2648 | Dec:9800">♈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2649 | Dec:9801">♉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+264A | Dec:9802">♊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+264B | Dec:9803">♋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+264C | Dec:9804">♌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+264D | Dec:9805">♍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+264E | Dec:9806">♎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+264F | Dec:9807">♏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2650 | Dec:9808">♐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2651 | Dec:9809">♑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2652 | Dec:9810">♒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2653 | Dec:9811">♓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2654 | Dec:9812">♔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2655 | Dec:9813">♕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2656 | Dec:9814">♖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2657 | Dec:9815">♗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2658 | Dec:9816">♘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2659 | Dec:9817">♙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+265A | Dec:9818">♚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+265B | Dec:9819">♛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+265C | Dec:9820">♜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+265D | Dec:9821">♝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+265E | Dec:9822">♞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+265F | Dec:9823">♟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2660 | Dec:9824">♠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2661 | Dec:9825">♡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2662 | Dec:9826">♢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2663 | Dec:9827">♣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2664 | Dec:9828">♤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2665 | Dec:9829">♥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2666 | Dec:9830">♦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2667 | Dec:9831">♧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2668 | Dec:9832">♨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2669 | Dec:9833">♩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+266A | Dec:9834">♪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+266B | Dec:9835">♫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+266C | Dec:9836">♬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+266D | Dec:9837">♭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+266E | Dec:9838">♮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+266F | Dec:9839">♯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2670 | Dec:9840">♰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2671 | Dec:9841">♱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2672 | Dec:9842">♲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2673 | Dec:9843">♳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2674 | Dec:9844">♴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2675 | Dec:9845">♵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2676 | Dec:9846">♶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2677 | Dec:9847">♷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2678 | Dec:9848">♸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2679 | Dec:9849">♹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+267A | Dec:9850">♺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+267B | Dec:9851">♻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+267C | Dec:9852">♼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+267D | Dec:9853">♽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+267E | Dec:9854">♾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+267F | Dec:9855">♿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2680 | Dec:9856">⚀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2681 | Dec:9857">⚁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2682 | Dec:9858">⚂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2683 | Dec:9859">⚃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2684 | Dec:9860">⚄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2685 | Dec:9861">⚅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2686 | Dec:9862">⚆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2687 | Dec:9863">⚇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2688 | Dec:9864">⚈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2689 | Dec:9865">⚉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+268A | Dec:9866">⚊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+268B | Dec:9867">⚋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+268C | Dec:9868">⚌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+268D | Dec:9869">⚍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+268E | Dec:9870">⚎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+268F | Dec:9871">⚏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2690 | Dec:9872">⚐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2691 | Dec:9873">⚑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2692 | Dec:9874">⚒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2693 | Dec:9875">⚓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2694 | Dec:9876">⚔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2695 | Dec:9877">⚕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2696 | Dec:9878">⚖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2697 | Dec:9879">⚗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2698 | Dec:9880">⚘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+2699 | Dec:9881">⚙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+269A | Dec:9882">⚚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+269B | Dec:9883">⚛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+269C | Dec:9884">⚜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+269D | Dec:9885">⚝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+269E | Dec:9886">⚞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+269F | Dec:9887">⚟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A0 | Dec:9888">⚠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A1 | Dec:9889">⚡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A2 | Dec:9890">⚢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A3 | Dec:9891">⚣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A4 | Dec:9892">⚤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A5 | Dec:9893">⚥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A6 | Dec:9894">⚦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A7 | Dec:9895">⚧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A8 | Dec:9896">⚨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26A9 | Dec:9897">⚩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26AA | Dec:9898">⚪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26AB | Dec:9899">⚫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26AC | Dec:9900">⚬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26AD | Dec:9901">⚭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26AE | Dec:9902">⚮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26AF | Dec:9903">⚯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B0 | Dec:9904">⚰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B1 | Dec:9905">⚱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B2 | Dec:9906">⚲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B3 | Dec:9907">⚳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B4 | Dec:9908">⚴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B5 | Dec:9909">⚵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B6 | Dec:9910">⚶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B7 | Dec:9911">⚷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B8 | Dec:9912">⚸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26B9 | Dec:9913">⚹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26BA | Dec:9914">⚺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26BB | Dec:9915">⚻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26BC | Dec:9916">⚼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26BD | Dec:9917">⚽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26BE | Dec:9918">⚾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26BF | Dec:9919">⚿</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C0 | Dec:9920">⛀</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C1 | Dec:9921">⛁</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C2 | Dec:9922">⛂</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C3 | Dec:9923">⛃</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C4 | Dec:9924">⛄</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C5 | Dec:9925">⛅</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C6 | Dec:9926">⛆</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C7 | Dec:9927">⛇</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C8 | Dec:9928">⛈</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26C9 | Dec:9929">⛉</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26CA | Dec:9930">⛊</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26CB | Dec:9931">⛋</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26CC | Dec:9932">⛌</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26CD | Dec:9933">⛍</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26CE | Dec:9934">⛎</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26CF | Dec:9935">⛏</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D0 | Dec:9936">⛐</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D1 | Dec:9937">⛑</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D2 | Dec:9938">⛒</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D3 | Dec:9939">⛓</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D4 | Dec:9940">⛔</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D5 | Dec:9941">⛕</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D6 | Dec:9942">⛖</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D7 | Dec:9943">⛗</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D8 | Dec:9944">⛘</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26D9 | Dec:9945">⛙</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26DA | Dec:9946">⛚</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26DB | Dec:9947">⛛</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26DC | Dec:9948">⛜</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26DD | Dec:9949">⛝</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26DE | Dec:9950">⛞</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26DF | Dec:9951">⛟</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E0 | Dec:9952">⛠</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E1 | Dec:9953">⛡</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E2 | Dec:9954">⛢</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E3 | Dec:9955">⛣</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E4 | Dec:9956">⛤</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E5 | Dec:9957">⛥</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E6 | Dec:9958">⛦</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E7 | Dec:9959">⛧</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E8 | Dec:9960">⛨</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26E9 | Dec:9961">⛩</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26EA | Dec:9962">⛪</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26EB | Dec:9963">⛫</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26EC | Dec:9964">⛬</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26ED | Dec:9965">⛭</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26EE | Dec:9966">⛮</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26EF | Dec:9967">⛯</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F0 | Dec:9968">⛰</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F1 | Dec:9969">⛱</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F2 | Dec:9970">⛲</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F3 | Dec:9971">⛳</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F4 | Dec:9972">⛴</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F5 | Dec:9973">⛵</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F6 | Dec:9974">⛶</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F7 | Dec:9975">⛷</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F8 | Dec:9976">⛸</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26F9 | Dec:9977">⛹</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26FA | Dec:9978">⛺</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26FB | Dec:9979">⛻</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26FC | Dec:9980">⛼</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26FD | Dec:9981">⛽</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26FE | Dec:9982">⛾</p-text>
      <p-text [size]="'medium'" [align]="'center'" title="U+26FF | Dec:9983">⛿</p-text>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TypographyLatinU_2000_26FfComponent {}
