name: 'Setup'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Cache node_modules'
      uses: actions/cache@v4
      id: cache-node_modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: 'Install node_modules'
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash
    - name: 'Download artifact'
      uses: actions/download-artifact@v4
      with:
        name: build-development
        path: ./packages
    - name: 'Setup executable files'
      run: |
        chmod +x ./packages/assets/bin/serve-cdn.js
        chmod +x ./packages/shared/bin/serve-dummyassets.js
      shell: bash
