name: 'Restore'

inputs:
  artifact:
    description: 'The artifact name.'
    required: true
    default: 'build-development'

runs:
  using: 'composite'
  steps:
    - name: 'Download artifact'
      uses: actions/download-artifact@v8
      with:
        name: '${{ inputs.artifact }}'
        path: ./packages
