name: 'Restore'

inputs:
  artifact:
    description: 'The artifact name.'
    required: true
    default: 'build-development'

runs:
  using: 'composite'
  steps:
    - name: 'Download artifact'
      uses: actions/download-artifact@v4
      with:
        name: '${{ inputs.artifact }}'
        path: ./packages
    - name: 'Setup executable files'
      run: |
        chmod +x ./packages/assets/bin/serve-cdn.js
        chmod +x ./packages/shared/bin/serve-dummyassets.js
      shell: bash
