name: 'Build components-js'
description: 'Build and restore cached builds of assets, component-meta, components, components-js, shared and utilities'
runs:
  using: 'composite'
  steps:
    - name: 'Restore Cached Builds'
      uses: actions/cache/restore@v4
      id: cache-builds-restore
      with:
        # TODO: icons and utilities/styles wouldn't be needed if icon-utils and injectGlobalStyle would use treeshakable assets package
        path: |
          ./packages/assets/bin
          ./packages/assets/cdn
          ./packages/assets/dist
          ./packages/component-meta/dist
          ./packages/components/dist
          ./packages/components/src/components/**/*.props.md
          ./packages/components-js/dist
          ./packages/components-js/projects/components-wrapper/lib
          ./packages/components-js/www
          ./packages/components-angular/projects/angular-wrapper/src/lib
          ./packages/components-react/projects/react-wrapper/src/lib
          ./packages/components-react/projects/react-ssr-wrapper/src/lib
          ./packages/components-react/projects/uxpin-wrapper/src/lib
          ./packages/components-vue/projects/vue-wrapper/src/lib
          ./packages/fallbacks/dist
          ./packages/icons/dist
          ./packages/model-signatures/dist
          ./packages/shared/dist
          ./packages/utilities/projects/styles/dist
          ./packages/utilities/projects/utilities/dist
        key: ${{ runner.os }}-${{ github.sha }} # cache is only used for current commit
    - name: 'Build Core Dependencies'
      if: steps.cache-builds-restore.outputs.cache-hit != 'true'
      uses: ./.github/actions/docker-run-playwright
      with:
        entrypoint: run-build
        args: --core-dependencies
    - name: 'Build Components'
      if: steps.cache-builds-restore.outputs.cache-hit != 'true'
      uses: ./.github/actions/docker-run-playwright
      with:
        entrypoint: run-build
        args: --components
    - name: 'Build Components JS'
      if: steps.cache-builds-restore.outputs.cache-hit != 'true'
      uses: ./.github/actions/docker-run-playwright
      with:
        entrypoint: run-build
        args: --components-js
    - name: 'Cache Builds'
      if: steps.cache-builds-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      id: cache-builds-save
      with:
        path: |
          ./packages/assets/bin
          ./packages/assets/cdn
          ./packages/assets/dist
          ./packages/component-meta/dist
          ./packages/components/dist
          ./packages/components/src/components/**/*.props.md
          ./packages/components-js/dist
          ./packages/components-js/projects/components-wrapper/lib
          ./packages/components-js/www
          ./packages/components-angular/projects/angular-wrapper/src/lib
          ./packages/components-react/projects/react-wrapper/src/lib
          ./packages/components-react/projects/react-ssr-wrapper/src/lib
          ./packages/components-react/projects/uxpin-wrapper/src/lib
          ./packages/components-vue/projects/vue-wrapper/src/lib
          ./packages/fallbacks/dist
          ./packages/model-signatures/dist
          ./packages/icons/dist
          ./packages/shared/dist
          ./packages/utilities/projects/styles/dist
          ./packages/utilities/projects/utilities/dist
        key: ${{ steps.cache-builds-restore.outputs.cache-primary-key }} # linked to restore key
