export const colors = {
  // a11y
  focusColor: 'var(--color-focus)',
  // background
  canvasColor: 'var(--color-canvas)',
  surfaceColor: 'var(--color-surface)',
  frostedColor: 'var(--color-frosted)',
  frostedSoftColor: 'var(--color-frosted-soft)',
  backdropColor: 'var(--color-backdrop)',
  // foreground
  contrastLowerColor: 'var(--color-contrast-lower)',
  contrastLowColor: 'var(--color-contrast-low)',
  contrastMediumColor: 'var(--color-contrast-medium)',
  contrastHighColor: 'var(--color-contrast-high)',
  contrastHigherColor: 'var(--color-contrast-higher)',
  contrastDisabledColor: 'var(--color-contrast-disabled)',
  primaryColor: 'var(--color-primary)',
  // semantic
  successColor: 'var(--color-success)',
  successFrostedColor: 'var(--color-success-frosted)',
  successFrostedSoftColor: 'var(--color-success-frosted-soft)',
  warningColor: 'var(--color-warning)',
  warningFrostedColor: 'var(--color-warning-frosted)',
  warningFrostedSoftColor: 'var(--color-warning-frosted-soft)',
  errorColor: 'var(--color-error)',
  errorFrostedColor: 'var(--color-error-frosted)',
  errorFrostedSoftColor: 'var(--color-error-frosted-soft)',
  infoColor: 'var(--color-info)',
  infoFrostedColor: 'var(--color-info-frosted)',
  infoFrostedSoftColor: 'var(--color-info-frosted-soft)',
} as const;
