analyzer:
  skip_excluded: true
  enabled_package_managers: [Yarn]

excludes:
  # -----------------------------
  # Path-based excludes
  # -----------------------------
  paths:
    - pattern: "docker/**"
      reason: OTHER
      comment: "The path only contains tools and executables used for CI/CD automation which is not included in any distributed artifacts."

    - pattern: "packages/shared/**"
      reason: OTHER
      comment: "The path only contains tools and dependencies used as devDependencies in other packages which is not included in any distributed artifacts."

    - pattern: "packages/storefront/**"
      reason: DOCUMENTATION_OF
      comment: "PDS examples and documentation site; not part of distributed PDS components."

    - pattern: "packages/**/tests/**"
      reason: TEST_OF
      comment: "Unit, integration, and E2E tests; not included in any distributed artifacts."

    - pattern: "packages/components/test-utils/**"
      reason: TEST_TOOL_OF
      comment: "Helper utilities for testing; not included in any distributed artifacts."

  # -----------------------------
  # Scope-based excludes
  # -----------------------------
  scopes:
    - pattern: "devDependencies"
      reason: DEV_DEPENDENCY_OF
      comment: "Development-only packages."

    - scope: "peerDependencies"
      reason: PROVIDED_DEPENDENCY_OF
      comment: "Peer dependencies must be provided by the consuming project; not part of delivered artifacts."
