analyzer:
  skip_excluded: true
  enabled_package_managers: [Yarn]

excludes:
  # -----------------------------
  # Path-based excludes
  # -----------------------------
  paths:

    - pattern: "packages/shared/**"
      reason: OTHER
      comment: "The path only contains tools and dependencies used as devDependencies in other packages which is not included in any distributed artifacts."

    # -----------------------------
    # components-react
    # -----------------------------
    - pattern: "packages/components-react/package.json"
      reason: OTHER
      comment: "Excluded project definition for React components; not part of distributed artifacts."

    - pattern: "packages/components-react/projects/nextjs/**"
      reason: EXAMPLE_OF
      comment: "Example integration project demonstrating framework usage; not included in any distributed artifacts."

    - pattern: "packages/components-react/projects/react-router/**"
      reason: EXAMPLE_OF
      comment: "Example integration project demonstrating framework usage; not included in any distributed artifacts."

    - pattern: "packages/components-react/projects/remix/**"
      reason: EXAMPLE_OF
      comment: "Example integration project demonstrating framework usage; not included in any distributed artifacts."

    # -----------------------------
    # components-angular
    # -----------------------------
    - pattern: "packages/components-angular/package.json"
      reason: OTHER
      comment: "Excluded project definition for Angular components; not part of distributed artifacts."

    # -----------------------------
    # components-vue
    # -----------------------------
    - pattern: "packages/components-vue/package.json"
      reason: OTHER
      comment: "Excluded project definition for Vue components; not part of distributed artifacts."

    # -----------------------------
    # test tools
    # -----------------------------
    - pattern: "packages/**/tests/**"
      reason: TEST_OF
      comment: "Unit, integration, and E2E tests; not included in any distributed artifacts."

    - pattern: "packages/components/test-utils/**"
      reason: TEST_TOOL_OF
      comment: "Helper utilities for testing; not included in any distributed artifacts."

  # -----------------------------
  # Scope-based excludes
  # -----------------------------
  scopes:
    - pattern: "devDependencies"
      reason: DEV_DEPENDENCY_OF
      comment: "Development-only packages."

    - scope: "peerDependencies"
      reason: PROVIDED_DEPENDENCY_OF
      comment: "Peer dependencies must be provided by the consuming project; not part of delivered artifacts."
