import {
  blurFrosted,
  colorBackdrop,
  colorBackdropDark,
  colorBackdropLight,
  colorCanvas,
  colorCanvasDark,
  colorCanvasLight,
  colorContrastHigh,
  colorContrastHighDark,
  colorContrastHigher,
  colorContrastHigherDark,
  colorContrastHigherLight,
  colorContrastHighLight,
  colorContrastLow,
  colorContrastLowDark,
  colorContrastLower,
  colorContrastLowerDark,
  colorContrastLowerLight,
  colorContrastLowLight,
  colorContrastMedium,
  colorContrastMediumDark,
  colorContrastMediumLight,
  colorError,
  colorErrorDark,
  colorErrorFrosted,
  colorErrorFrostedDark,
  colorErrorFrostedLight,
  colorErrorFrostedSoft,
  colorErrorFrostedSoftDark,
  colorErrorFrostedSoftLight,
  colorErrorLight,
  colorErrorLow,
  colorErrorLowDark,
  colorErrorLowLight,
  colorErrorMedium,
  colorErrorMediumDark,
  colorErrorMediumLight,
  colorFocus,
  colorFocusDark,
  colorFocusLight,
  colorFrosted,
  colorFrostedDark,
  colorFrostedLight,
  colorFrostedSoft,
  colorFrostedSoftDark,
  colorFrostedSoftLight,
  colorFrostedStrong,
  colorFrostedStrongDark,
  colorFrostedStrongLight,
  colorInfo,
  colorInfoDark,
  colorInfoFrosted,
  colorInfoFrostedDark,
  colorInfoFrostedLight,
  colorInfoFrostedSoft,
  colorInfoFrostedSoftDark,
  colorInfoFrostedSoftLight,
  colorInfoLight,
  colorInfoLow,
  colorInfoLowDark,
  colorInfoLowLight,
  colorInfoMedium,
  colorInfoMediumDark,
  colorInfoMediumLight,
  colorPrimary,
  colorPrimaryDark,
  colorPrimaryLight,
  colorSuccess,
  colorSuccessDark,
  colorSuccessFrosted,
  colorSuccessFrostedDark,
  colorSuccessFrostedLight,
  colorSuccessFrostedSoft,
  colorSuccessFrostedSoftDark,
  colorSuccessFrostedSoftLight,
  colorSuccessLight,
  colorSuccessLow,
  colorSuccessLowDark,
  colorSuccessLowLight,
  colorSuccessMedium,
  colorSuccessMediumDark,
  colorSuccessMediumLight,
  colorSurface,
  colorSurfaceDark,
  colorSurfaceLight,
  colorWarning,
  colorWarningDark,
  colorWarningFrosted,
  colorWarningFrostedDark,
  colorWarningFrostedLight,
  colorWarningFrostedSoft,
  colorWarningFrostedSoftDark,
  colorWarningFrostedSoftLight,
  colorWarningLight,
  colorWarningLow,
  colorWarningLowDark,
  colorWarningLowLight,
  colorWarningMedium,
  colorWarningMediumDark,
  colorWarningMediumLight,
  durationLg,
  durationMd,
  durationSm,
  durationXl,
  easeIn,
  easeInOut,
  easeOut,
  fontPorscheNext,
  fontPorscheNextJa,
  fontPorscheNextKo,
  fontPorscheNextZhHans,
  fontPorscheNextZhHant,
  fontWeightBold,
  fontWeightNormal,
  fontWeightSemibold,
  leadingNormal,
  radius2Xl,
  radius3Xl,
  radius4Xl,
  radiusFull,
  radiusLg,
  radiusMd,
  radiusSm,
  radiusXl,
  radiusXs,
  shadowLg,
  shadowMd,
  shadowSm,
  spacingFluid2Xl,
  spacingFluidLg,
  spacingFluidMd,
  spacingFluidSm,
  spacingFluidXl,
  spacingFluidXs,
  spacingStatic2Xl,
  spacingStatic2Xs,
  spacingStaticLg,
  spacingStaticMd,
  spacingStaticSm,
  spacingStaticXl,
  spacingStaticXs,
  typescale2Xl,
  typescale2Xs,
  typescale3Xl,
  typescale4Xl,
  typescale5Xl,
  typescaleLg,
  typescaleMd,
  typescaleSm,
  typescaleXl,
  typescaleXs,
} from '@porsche-design-system/tokens';
import { flattenCssVariables } from './helpers';
import type { CssNode, CssVariableMeta, CssVariablesMetaTree } from './types';

/** Returns a `var(--…)` reference for the given CSS variable, for use in component and docs styles. */
export const reference = ({ property }: CssVariableMeta): string => `var(${property})`;

export const cssVariablesMeta = {
  color: {
    background: {
      canvas: {
        name: 'canvas',
        type: 'color',
        property: '--p-color-canvas',
        description: 'Applies the **canvas** color, typically used for surfaces.',
        value: colorCanvas,
        valueLight: colorCanvasLight,
        valueDark: colorCanvasDark,
      },
      surface: {
        name: 'surface',
        type: 'color',
        property: '--p-color-surface',
        description: 'Applies the **surface** color, typically used for surfaces.',
        value: colorSurface,
        valueLight: colorSurfaceLight,
        valueDark: colorSurfaceDark,
      },
      frosted: {
        name: 'frosted',
        type: 'color',
        property: '--p-color-frosted',
        description: 'Applies the **frosted** color, typically used as a background in combination with a blur effect.',
        value: colorFrosted,
        valueLight: colorFrostedLight,
        valueDark: colorFrostedDark,
      },
      frostedSoft: {
        name: 'frostedSoft',
        type: 'color',
        property: '--p-color-frosted-soft',
        description: 'Applies the **frosted** color, typically used as a background `:hover`.',
        value: colorFrostedSoft,
        valueLight: colorFrostedSoftLight,
        valueDark: colorFrostedSoftDark,
      },
      frostedStrong: {
        name: 'frostedStrong',
        type: 'color',
        property: '--p-color-frosted-strong',
        description:
          'Applies the **frosted-strong** color, typically used as a background in combination with a blur effect.',
        value: colorFrostedStrong,
        valueLight: colorFrostedStrongLight,
        valueDark: colorFrostedStrongDark,
      },
      backdrop: {
        name: 'backdrop',
        type: 'color',
        property: '--p-color-backdrop',
        description: 'Applies the **backdrop** color, typically used for backdrops.',
        value: colorBackdrop,
        valueLight: colorBackdropLight,
        valueDark: colorBackdropDark,
      },
    },
    foreground: {
      primary: {
        name: 'primary',
        type: 'color',
        property: '--p-color-primary',
        description: 'Applies the **primary** color, typically used for text.',
        value: colorPrimary,
        valueLight: colorPrimaryLight,
        valueDark: colorPrimaryDark,
      },
      contrastHigher: {
        name: 'contrastHigher',
        type: 'color',
        property: '--p-color-contrast-higher',
        description: 'Applies the **contrast-higher** color, typically used for text.',
        value: colorContrastHigher,
        valueLight: colorContrastHigherLight,
        valueDark: colorContrastHigherDark,
      },
      contrastHigh: {
        name: 'contrastHigh',
        type: 'color',
        property: '--p-color-contrast-high',
        description: 'Applies the **contrast-high** color, typically used for text.',
        value: colorContrastHigh,
        valueLight: colorContrastHighLight,
        valueDark: colorContrastHighDark,
      },
      contrastMedium: {
        name: 'contrastMedium',
        type: 'color',
        property: '--p-color-contrast-medium',
        description: 'Applies the **contrast-medium** color, typically used for text.',
        value: colorContrastMedium,
        valueLight: colorContrastMediumLight,
        valueDark: colorContrastMediumDark,
      },
      contrastLow: {
        name: 'contrastLow',
        type: 'color',
        property: '--p-color-contrast-low',
        description:
          'Applies the **contrast-low** color, intended only for decorative elements, as it is not accessibility-compliant.',
        value: colorContrastLow,
        valueLight: colorContrastLowLight,
        valueDark: colorContrastLowDark,
      },
      contrastLower: {
        name: 'contrastLower',
        type: 'color',
        property: '--p-color-contrast-lower',
        description:
          'Applies the **contrast-lower** color, intended only for decorative elements, as it is not accessibility-compliant.',
        value: colorContrastLower,
        valueLight: colorContrastLowerLight,
        valueDark: colorContrastLowerDark,
      },
    },
    semantic: {
      info: {
        name: 'info',
        type: 'color',
        property: '--p-color-info',
        description: 'Applies the **info** color, typically used for text.',
        value: colorInfo,
        valueLight: colorInfoLight,
        valueDark: colorInfoDark,
      },
      infoMedium: {
        name: 'infoMedium',
        type: 'color',
        property: '--p-color-info-medium',
        description: 'Applies the **info** color, typically used for text or border.',
        value: colorInfoMedium,
        valueLight: colorInfoMediumLight,
        valueDark: colorInfoMediumDark,
      },
      infoLow: {
        name: 'infoLow',
        type: 'color',
        property: '--p-color-info-low',
        description: 'Applies the **info** color, typically used for text or border.',
        value: colorInfoLow,
        valueLight: colorInfoLowLight,
        valueDark: colorInfoLowDark,
      },
      infoFrosted: {
        name: 'infoFrosted',
        type: 'color',
        property: '--p-color-info-frosted',
        description:
          'Applies the **info-frosted** color, typically used as background in combination with a blur effect.',
        value: colorInfoFrosted,
        valueLight: colorInfoFrostedLight,
        valueDark: colorInfoFrostedDark,
      },
      infoFrostedSoft: {
        name: 'infoFrostedSoft',
        type: 'color',
        property: '--p-color-info-frosted-soft',
        description: 'Applies the **info-frosted-soft** color, typically used as background `:hover`.',
        value: colorInfoFrostedSoft,
        valueLight: colorInfoFrostedSoftLight,
        valueDark: colorInfoFrostedSoftDark,
      },
      success: {
        name: 'success',
        type: 'color',
        property: '--p-color-success',
        description: 'Applies the **success** color, typically used for text.',
        value: colorSuccess,
        valueLight: colorSuccessLight,
        valueDark: colorSuccessDark,
      },
      successMedium: {
        name: 'successMedium',
        type: 'color',
        property: '--p-color-success-medium',
        description: 'Applies the **success** color, typically used for text or border.',
        value: colorSuccessMedium,
        valueLight: colorSuccessMediumLight,
        valueDark: colorSuccessMediumDark,
      },
      successLow: {
        name: 'successLow',
        type: 'color',
        property: '--p-color-success-low',
        description: 'Applies the **success** color, typically used for text or border.',
        value: colorSuccessLow,
        valueLight: colorSuccessLowLight,
        valueDark: colorSuccessLowDark,
      },
      successFrosted: {
        name: 'successFrosted',
        type: 'color',
        property: '--p-color-success-frosted',
        description:
          'Applies the **success-frosted** color, typically used as background in combination with a blur effect.',
        value: colorSuccessFrosted,
        valueLight: colorSuccessFrostedLight,
        valueDark: colorSuccessFrostedDark,
      },
      successFrostedSoft: {
        name: 'successFrostedSoft',
        type: 'color',
        property: '--p-color-success-frosted-soft',
        description: 'Applies the **success-frosted-soft** color, typically used as background `:hover`.',
        value: colorSuccessFrostedSoft,
        valueLight: colorSuccessFrostedSoftLight,
        valueDark: colorSuccessFrostedSoftDark,
      },
      warning: {
        name: 'warning',
        type: 'color',
        property: '--p-color-warning',
        description: 'Applies the **warning** color, typically used for text.',
        value: colorWarning,
        valueLight: colorWarningLight,
        valueDark: colorWarningDark,
      },
      warningMedium: {
        name: 'warningMedium',
        type: 'color',
        property: '--p-color-warning-medium',
        description: 'Applies the **warning** color, typically used for text or border.',
        value: colorWarningMedium,
        valueLight: colorWarningMediumLight,
        valueDark: colorWarningMediumDark,
      },
      warningLow: {
        name: 'warningLow',
        type: 'color',
        property: '--p-color-warning-low',
        description: 'Applies the **warning** color, typically used for text or border.',
        value: colorWarningLow,
        valueLight: colorWarningLowLight,
        valueDark: colorWarningLowDark,
      },
      warningFrosted: {
        name: 'warningFrosted',
        type: 'color',
        property: '--p-color-warning-frosted',
        description:
          'Applies the **warning-frosted** color, typically used as background in combination with a blur effect.',
        value: colorWarningFrosted,
        valueLight: colorWarningFrostedLight,
        valueDark: colorWarningFrostedDark,
      },
      warningFrostedSoft: {
        name: 'warningFrostedSoft',
        type: 'color',
        property: '--p-color-warning-frosted-soft',
        description: 'Applies the **warning-frosted-soft** color, typically used as background `:hover`.',
        value: colorWarningFrostedSoft,
        valueLight: colorWarningFrostedSoftLight,
        valueDark: colorWarningFrostedSoftDark,
      },
      error: {
        name: 'error',
        type: 'color',
        property: '--p-color-error',
        description: 'Applies the **error** color, typically used for text.',
        value: colorError,
        valueLight: colorErrorLight,
        valueDark: colorErrorDark,
      },
      errorMedium: {
        name: 'errorMedium',
        type: 'color',
        property: '--p-color-error-medium',
        description: 'Applies the **error** color, typically used for text or border.',
        value: colorErrorMedium,
        valueLight: colorErrorMediumLight,
        valueDark: colorErrorMediumDark,
      },
      errorLow: {
        name: 'errorLow',
        type: 'color',
        property: '--p-color-error-low',
        description: 'Applies the **error** color, typically used for text or border.',
        value: colorErrorLow,
        valueLight: colorErrorLowLight,
        valueDark: colorErrorLowDark,
      },
      errorFrosted: {
        name: 'errorFrosted',
        type: 'color',
        property: '--p-color-error-frosted',
        description:
          'Applies the **error-frosted** color, typically used as background in combination with a blur effect.',
        value: colorErrorFrosted,
        valueLight: colorErrorFrostedLight,
        valueDark: colorErrorFrostedDark,
      },
      errorFrostedSoft: {
        name: 'errorFrostedSoft',
        type: 'color',
        property: '--p-color-error-frosted-soft',
        description: 'Applies the **error-frosted-soft** color, typically used as background `:hover`.',
        value: colorErrorFrostedSoft,
        valueLight: colorErrorFrostedSoftLight,
        valueDark: colorErrorFrostedSoftDark,
      },
    },
    a11y: {
      focus: {
        name: 'focus',
        type: 'color',
        property: '--p-color-focus',
        description: 'Applies the **focus** color, typically used as the outline for `:focus-visible` states.',
        value: colorFocus,
        valueLight: colorFocusLight,
        valueDark: colorFocusDark,
      },
    },
  },
  typography: {
    family: {
      porscheNext: {
        name: 'porscheNext',
        type: 'typography',
        property: '--p-font-porsche-next',
        description:
          'Applies the **Porsche Next** font family along with fallback fonts. Automatically swaps to the locale-specific CJK stack (Simplified Chinese, Traditional Chinese, Japanese, Korean) via `:lang()` based on the nearest `lang` attribute.',
        value: fontPorscheNext,
      },
      sans: {
        name: 'sans',
        type: 'typography',
        property: '--p-font-sans',
        description: 'Alias for `--p-font-porsche-next`, provided for Tailwind-style `font-sans` usage.',
        value: 'var(--p-font-porsche-next)',
      },
    },
    weight: {
      normal: {
        name: 'normal',
        type: 'typography',
        property: '--p-font-weight-normal',
        description: 'Applies the **regular** font weight optimized for the Porsche Next typeface.',
        value: fontWeightNormal,
      },
      semibold: {
        name: 'semibold',
        type: 'typography',
        property: '--p-font-weight-semibold',
        description: 'Applies the **semi-bold** font weight optimized for the Porsche Next typeface.',
        value: fontWeightSemibold,
      },
      bold: {
        name: 'bold',
        type: 'typography',
        property: '--p-font-weight-bold',
        description: 'Applies the **bold** font weight optimized for the Porsche Next typeface.',
        value: fontWeightBold,
      },
    },
    lineHeight: {
      normal: {
        name: 'normal',
        type: 'typography',
        property: '--p-leading-normal',
        description: 'Applies a dynamic default line height specifically optimized for the Porsche Next typeface.',
        value: leadingNormal,
      },
    },
    typescale: {
      '2xs': {
        name: '2xs',
        type: 'typography',
        property: '--p-typescale-2xs',
        description: 'Applies the **2x-small** font size for the Porsche Next typeface.',
        value: typescale2Xs,
      },
      xs: {
        name: 'xs',
        type: 'typography',
        property: '--p-typescale-xs',
        description: 'Applies the **x-small** font size for the Porsche Next typeface.',
        value: typescaleXs,
      },
      sm: {
        name: 'sm',
        type: 'typography',
        property: '--p-typescale-sm',
        description: 'Applies the **small** font size for the Porsche Next typeface.',
        value: typescaleSm,
      },
      md: {
        name: 'md',
        type: 'typography',
        property: '--p-typescale-md',
        description: 'Applies the **medium** font size for the Porsche Next typeface.',
        value: typescaleMd,
      },
      lg: {
        name: 'lg',
        type: 'typography',
        property: '--p-typescale-lg',
        description: 'Applies the **large** font size for the Porsche Next typeface.',
        value: typescaleLg,
      },
      xl: {
        name: 'xl',
        type: 'typography',
        property: '--p-typescale-xl',
        description: 'Applies the **x-large** font size for the Porsche Next typeface.',
        value: typescaleXl,
      },
      '2xl': {
        name: '2xl',
        type: 'typography',
        property: '--p-typescale-2xl',
        description: 'Applies the **2x-large** font size for the Porsche Next typeface.',
        value: typescale2Xl,
      },
      '3xl': {
        name: '3xl',
        type: 'typography',
        property: '--p-typescale-3xl',
        description: 'Applies the **3x-large** font size for the Porsche Next typeface.',
        value: typescale3Xl,
      },
      '4xl': {
        name: '4xl',
        type: 'typography',
        property: '--p-typescale-4xl',
        description: 'Applies the **4x-large** font size for the Porsche Next typeface.',
        value: typescale4Xl,
      },
      '5xl': {
        name: '5xl',
        type: 'typography',
        property: '--p-typescale-5xl',
        description: 'Applies the **5x-large** font size for the Porsche Next typeface.',
        value: typescale5Xl,
      },
    },
  },
  spacing: {
    fluid: {
      xs: {
        name: 'xs',
        type: 'spacing',
        property: '--p-spacing-fluid-xs',
        description: 'Applies the **x-small** fluid spacing.',
        value: spacingFluidXs,
      },
      sm: {
        name: 'sm',
        type: 'spacing',
        property: '--p-spacing-fluid-sm',
        description: 'Applies the **small** fluid spacing.',
        value: spacingFluidSm,
      },
      md: {
        name: 'md',
        type: 'spacing',
        property: '--p-spacing-fluid-md',
        description: 'Applies the **medium** fluid spacing.',
        value: spacingFluidMd,
      },
      lg: {
        name: 'lg',
        type: 'spacing',
        property: '--p-spacing-fluid-lg',
        description: 'Applies the **large** fluid spacing.',
        value: spacingFluidLg,
      },
      xl: {
        name: 'xl',
        type: 'spacing',
        property: '--p-spacing-fluid-xl',
        description: 'Applies the **x-large** fluid spacing.',
        value: spacingFluidXl,
      },
      '2xl': {
        name: '2xl',
        type: 'spacing',
        property: '--p-spacing-fluid-2xl',
        description: 'Applies the **2x-large** fluid spacing.',
        value: spacingFluid2Xl,
      },
    },
    static: {
      '2xs': {
        name: '2xs',
        type: 'spacing',
        property: '--p-spacing-static-2xs',
        description: 'Applies the **2x-small** static spacing.',
        value: spacingStatic2Xs,
      },
      xs: {
        name: 'xs',
        type: 'spacing',
        property: '--p-spacing-static-xs',
        description: 'Applies the **x-small** static spacing.',
        value: spacingStaticXs,
      },
      sm: {
        name: 'sm',
        type: 'spacing',
        property: '--p-spacing-static-sm',
        description: 'Applies the **small** static spacing.',
        value: spacingStaticSm,
      },
      md: {
        name: 'md',
        type: 'spacing',
        property: '--p-spacing-static-md',
        description: 'Applies the **medium** static spacing.',
        value: spacingStaticMd,
      },
      lg: {
        name: 'lg',
        type: 'spacing',
        property: '--p-spacing-static-lg',
        description: 'Applies the **large** static spacing.',
        value: spacingStaticLg,
      },
      xl: {
        name: 'xl',
        type: 'spacing',
        property: '--p-spacing-static-xl',
        description: 'Applies the **x-large** static spacing.',
        value: spacingStaticXl,
      },
      '2xl': {
        name: '2xl',
        type: 'spacing',
        property: '--p-spacing-static-2xl',
        description: 'Applies the **2x-large** static spacing.',
        value: spacingStatic2Xl,
      },
    },
  },
  radius: {
    xs: {
      name: 'xs',
      type: 'radius',
      property: '--p-radius-xs',
      description: 'Applies a **x-small** `border-radius`.',
      value: radiusXs,
    },
    sm: {
      name: 'sm',
      type: 'radius',
      property: '--p-radius-sm',
      description: 'Applies a **small** `border-radius`.',
      value: radiusSm,
    },
    md: {
      name: 'md',
      type: 'radius',
      property: '--p-radius-md',
      description: 'Applies a **medium** `border-radius`.',
      value: radiusMd,
    },
    lg: {
      name: 'lg',
      type: 'radius',
      property: '--p-radius-lg',
      description: 'Applies a **large** `border-radius`.',
      value: radiusLg,
    },
    xl: {
      name: 'xl',
      type: 'radius',
      property: '--p-radius-xl',
      description: 'Applies a **x-large** `border-radius`.',
      value: radiusXl,
    },
    '2xl': {
      name: '2xl',
      type: 'radius',
      property: '--p-radius-2xl',
      description: 'Applies a **2x-large** `border-radius`.',
      value: radius2Xl,
    },
    '3xl': {
      name: '3xl',
      type: 'radius',
      property: '--p-radius-3xl',
      description: 'Applies a **3x-large** `border-radius`.',
      value: radius3Xl,
    },
    '4xl': {
      name: '4xl',
      type: 'radius',
      property: '--p-radius-4xl',
      description: 'Applies a **4x-large** `border-radius`.',
      value: radius4Xl,
    },
    full: {
      name: 'full',
      type: 'radius',
      property: '--p-radius-full',
      description: 'Applies a **fully** rounded `border-radius`.',
      value: radiusFull,
    },
  },
  blur: {
    frosted: {
      name: 'frosted',
      type: 'blur',
      property: '--p-blur-frosted',
      description:
        'Applies a **frosted** effect when used with `backdrop-filter` or `filter: blur()` when combined with a semi-transparent color.',
      value: blurFrosted,
    },
  },
  shadow: {
    sm: {
      name: 'sm',
      type: 'shadow',
      property: '--p-shadow-sm',
      description: 'Applies a **small** `box-shadow`.',
      value: shadowSm,
    },
    md: {
      name: 'md',
      type: 'shadow',
      property: '--p-shadow-md',
      description: 'Applies a **medium** `box-shadow`.',
      value: shadowMd,
    },
    lg: {
      name: 'lg',
      type: 'shadow',
      property: '--p-shadow-lg',
      description: 'Applies a **large** `box-shadow`.',
      value: shadowLg,
    },
  },
  motion: {
    duration: {
      sm: {
        name: 'sm',
        type: 'motion',
        property: '--p-duration-sm',
        description: 'Applies a **short** `transition-duration`.',
        value: durationSm,
      },
      md: {
        name: 'md',
        type: 'motion',
        property: '--p-duration-md',
        description: 'Applies a **moderate** `transition-duration`.',
        value: durationMd,
      },
      lg: {
        name: 'lg',
        type: 'motion',
        property: '--p-duration-lg',
        description: 'Applies a **long** `transition-duration`.',
        value: durationLg,
      },
      xl: {
        name: 'xl',
        type: 'motion',
        property: '--p-duration-xl',
        description: 'Applies a **very long** `transition-duration`.',
        value: durationXl,
      },
    },
    easing: {
      inOut: {
        name: 'inOut',
        type: 'motion',
        property: '--p-ease-in-out',
        description: 'Applies an **in-out** `transition-timing-function`.',
        value: easeInOut,
      },
      in: {
        name: 'in',
        type: 'motion',
        property: '--p-ease-in',
        description: 'Applies an **in** `transition-timing-function`.',
        value: easeIn,
      },
      out: {
        name: 'out',
        type: 'motion',
        property: '--p-ease-out',
        description: 'Applies an **out** `transition-timing-function`.',
        value: easeOut,
      },
    },
  },
} satisfies CssVariablesMetaTree;

const fontPorscheNextProperty = cssVariablesMeta.typography.family.porscheNext.property;

// The fully resolved CSS for `variables.css`, expressed as `CssNode` trees. The
// build scripts only have to `renderCss()` these nodes and format the result.
export const variablesCss: CssNode[] = [
  {
    selector: ':root',
    declarations: [
      { property: 'color-scheme', value: 'light' },
      // Variable leaves are structurally `CssDeclaration`s, so they are emitted directly.
      ...flattenCssVariables(cssVariablesMeta),
    ],
  },
  {
    comment: 'Simplified Chinese',
    selector: [':lang(zh-Hans)', ':lang(zh-CN)', ':lang(zh-SG)'].join(',\n'),
    declarations: [{ property: fontPorscheNextProperty, value: fontPorscheNextZhHans }],
  },
  {
    comment: 'Traditional Chinese',
    selector: [':lang(zh-Hant)', ':lang(zh-TW)', ':lang(zh-HK)', ':lang(zh-MO)'].join(',\n'),
    declarations: [{ property: fontPorscheNextProperty, value: fontPorscheNextZhHant }],
  },
  {
    comment: 'Japanese',
    selector: [':lang(ja)'].join(',\n'),
    declarations: [{ property: fontPorscheNextProperty, value: fontPorscheNextJa }],
  },
  {
    comment: 'Korean',
    selector: [':lang(ko)'].join(',\n'),
    declarations: [{ property: fontPorscheNextProperty, value: fontPorscheNextKo }],
  },
];
