import type { Example } from './meta.ts';
import { examplesPath, mediaPath } from './projects.ts';

/**
 * The package export, `@porsche-design-system/examples`: every example with its meta and the files of its generated
 * project, and the paths the built pages and their media are served at.
 *
 * ```text
 * generated/examples.ts   # scripts/build.ts – the source, imported as it is by the scripts and the knowledge skill
 * dist/examples.js        # rollup.config.mjs – the source bundled, what a consumer imports
 * dist/examples.d.ts      # rollup.config.mjs – its declarations, bundled
 * ```
 *
 * It is generated because the files are build output – rendered, formatted and split into a project by this package –
 * and the paths of the examples are only known once the pages are found. Its types are those of `lib/meta.ts`,
 * re-exported, so they are defined there and nowhere else; the generated part is `ExamplePath`, the path of every
 * example as a union. The generated source imports nothing but types, so it bundles without the `.ts` import
 * extensions the rest of the package uses.
 */

export const exportFileName = 'examples.ts';

/** Every example by its path, in the order of the pages. */
export type Examples = Record<string, Example>;

/** A string as a literal of the generated code – the values written as such hold no quote. */
const literal = (value: string): string => `'${value}'`;

export const getExportModule = (examples: Examples): string =>
  [
    '// Generated by scripts/build.ts – do not edit.',
    "import type { Example } from '../lib/meta.ts';",
    '',
    "export type { Example, ExampleMeta, ExampleProject } from '../lib/meta.ts';",
    '',
    '/** The path of every example below the root of the examples. */',
    `export type ExamplePath =\n${Object.keys(examples)
      .map((path) => `  | ${literal(path)}`)
      .join('\n')};`,
    '',
    '/** Where the built pages are served, relative to the root of a site: `/examples/patterns/header/overlay/`. */',
    `export const examplesPath = ${literal(examplesPath)};`,
    '',
    '/** Where the media of the examples are served, relative to the root of a site – the path the pages use. */',
    `export const mediaPath = ${literal(mediaPath)};`,
    '',
    '/**',
    ' * Every pattern and template by its path, in the order of the pages: its meta and the files of its generated',
    ' * project. They reference their media by `mediaPath`, which a deployment below a base path has to prefix.',
    ' *',
    ' * The whole set is large – import it on the server only, and hand a client the example it shows.',
    ' */',
    `export const examples: { readonly [Path in ExamplePath]: Example<Path> } = ${JSON.stringify(examples, null, 2)};`,
    '',
  ].join('\n');
