const fs = require('fs');
const path = require('path');
const icons = require('@porsche-design-system/icons');

(async () => {
  const iconNames = [];

  for (let id in icons.manifest) {
    iconNames.push(`'${id}'`);
  }

  const typeCode = `/* this file is auto generated by icon-name-generation.js */ \n
export type IconName = ${iconNames.sort().join("\n| ")};`;
  const targetFile = path.join(__dirname, '../src/components/icon/icon/icon-name.ts');
  fs.writeFile(targetFile, typeCode, 'utf8', (err) => {
    if (err) throw err;
  });
})();
