export * from './deprecated';
export { spacingFluid2Xl } from './spacingFluid2Xl';
export { spacingFluidLg } from './spacingFluidLg';
export { spacingFluidMd } from './spacingFluidMd';
export { spacingFluidSm } from './spacingFluidSm';
export { spacingFluidXl } from './spacingFluidXl';
export { spacingFluidXs } from './spacingFluidXs';
export { spacingStatic2Xl } from './spacingStatic2Xl';
export { spacingStaticLg } from './spacingStaticLg';
export { spacingStaticMd } from './spacingStaticMd';
export { spacingStaticSm } from './spacingStaticSm';
export { spacingStaticXl } from './spacingStaticXl';
export { spacingStaticXs } from './spacingStaticXs';
