import * as fs from 'node:fs';
import * as path from 'node:path';
import { cssVariableTokens } from '../src/theme';
import type { CssVariableMeta, StylesheetTokenTree } from '../src/types';

// Generates one plain-literal module per CSS custom property *name* under
// `src/generated/cssVariables/<group>/<...>/<name>.ts`, e.g.:
//
//   export const colorCanvas = '--p-color-canvas';
//
// `cssVariableTokens` is the single source of truth (it carries the authored `property`
// strings). These const files are a DERIVED build artifact generated from it — they live
// in the gitignored `src/generated/` folder and are (re)built by `build:constants` (part
// of `npm run build`) and by the unit-test global setup.
//
// They are emitted as standalone literals (not derived from the `cssVariableTokens` object
// at runtime) so bundlers (Stencil/Rollup) can tree-shake a single variable into a
// component without dragging the whole meta object along. The grouped directory structure
// mirrors `cssVariableTokens` (e.g. `color/background/colorCanvas.ts`) so it stays
// self-documenting and aligned with the docs/LLM categorization. The const *names* are
// derived from each `property` string (not the tree keys), so they are unaffected by the
// catalog's domain vocabulary. The hand-written `ref()` helper lives separately in
// `src/ref.ts` and is NOT generated.

// Resolved from this file, not from `process.cwd()`: the unit-test global setup imports and calls
// `buildCssVariableConstants()`, so the generator also runs under whatever directory vitest was
// launched from. A cwd-relative path silently wrote the tree into the repository root — where the
// specs importing `src/generated/cssVariables` could never resolve it — and pointed the `rmSync`
// below at that unrelated directory too.
const generatedDir = path.resolve(__dirname, '..', 'src', 'generated', 'cssVariables');
const HEADER = '// AUTO-GENERATED by scripts/buildCssVariableConstants.ts — do not edit by hand.\n';

const isLeaf = (node: StylesheetTokenTree | CssVariableMeta): node is CssVariableMeta =>
  typeof (node as CssVariableMeta).property === 'string';

/** Derives the const/file name from a CSS custom property, e.g. `--p-spacing-fluid-2xl` -> `spacingFluid2Xl`. */
export const toConstName = (property: string): string =>
  property
    .replace(/^--_?p-/, '')
    .split('-')
    .map((segment, index) => {
      const cased = index === 0 ? segment : segment.charAt(0).toUpperCase() + segment.slice(1);
      // Capitalize the letter following a leading digit, e.g. `2xl` -> `2Xl`.
      return cased.replace(/^(\d+)([a-z])/, (_, digits, letter) => digits + letter.toUpperCase());
    })
    .join('');

type Leaf = { constName: string; property: string };
type Dir = { dirs: Map<string, Dir>; leaves: Leaf[] };

const createDir = (): Dir => ({ dirs: new Map(), leaves: [] });

/** Recursively collects the grouped tree of variable leaves mirroring `cssVariableTokens`. */
const collect = (tree: StylesheetTokenTree, dir: Dir): void => {
  for (const [key, node] of Object.entries(tree)) {
    if (isLeaf(node)) {
      dir.leaves.push({ constName: toConstName(node.property), property: node.property });
    } else {
      const childDir = createDir();
      dir.dirs.set(key, childDir);
      collect(node, childDir);
    }
  }
};

/** Recursively writes the per-variable files and `index.ts` barrels for a directory node. */
const writeDir = (dir: Dir, dirPath: string): void => {
  fs.mkdirSync(dirPath, { recursive: true });
  const barrelLines: string[] = [];

  for (const { constName, property } of [...dir.leaves].sort((a, b) => a.constName.localeCompare(b.constName))) {
    fs.writeFileSync(path.join(dirPath, `${constName}.ts`), `${HEADER}export const ${constName} = '${property}';\n`);
    barrelLines.push(`export { ${constName} } from './${constName}';`);
  }

  for (const childKey of [...dir.dirs.keys()].sort()) {
    const childDir = dir.dirs.get(childKey) as Dir;
    writeDir(childDir, path.join(dirPath, childKey));
    barrelLines.push(`export * from './${childKey}';`);
  }

  fs.writeFileSync(path.join(dirPath, 'index.ts'), `${HEADER}${barrelLines.sort().join('\n')}\n`);
};

export const buildCssVariableConstants = (): void => {
  // Fully regenerate the gitignored output folder.
  fs.rmSync(generatedDir, { recursive: true, force: true });

  const root = createDir();
  collect(cssVariableTokens, root);

  writeDir(root, generatedDir);

  console.log(`Built CSS variable constants under ${path.relative(process.cwd(), generatedDir)}`);
};

// Only auto-run when executed directly (e.g. via tsx in `build:constants`), not when
// imported (e.g. by the unit-test global setup).
if (process.argv[1]?.endsWith('buildCssVariableConstants.ts')) {
  buildCssVariableConstants();
}
