import { minify as htmlMinifier } from 'html-minifier';
import CleanCSS from 'clean-css';

export const minifyHTML = (str: string): string =>
  htmlMinifier(str, {
    collapseWhitespace: true,
    collapseInlineTagWhitespace: true,
    removeAttributeQuotes: true,
    removeComments: true,
    minifyCSS: true,
    minifyJS: true,
    includeAutoGeneratedTags: false,
    quoteCharacter: '"'
  });

export const minifyCSS = (str: string): string => new CleanCSS().minify(str).styles;
