#!/usr/bin/env bash
# outdated-report.sh — deterministic dependency report for the minimal
# dep-bump onboarding blueprint.
#
# Runs `npm outdated`, renders the result as a single Markdown table, and
# upserts it as one PR comment. Idempotent across retries: it edits the last
# bot comment when one exists, otherwise creates it. It is best-effort and
# ALWAYS exits 0 so a report never fails the run:
#   - `npm outdated` exits non-zero when packages are outdated; that is the
#     normal case, not an error, so its exit code is ignored.
#   - With no PR context (TURBO_SPEC_PR_NUMBER unset) it prints the table to
#     the log and skips the comment, so local / non-PR runs stay green.
set -uo pipefail

out_dir=".turbo-spec/out"
json_file="${out_dir}/outdated.json"
body_file="${out_dir}/outdated-report.md"
mkdir -p "${out_dir}"

# `npm outdated --json` emits a JSON object keyed by package name and exits 1
# when anything is outdated. Capture stdout regardless of exit code.
npm outdated --json --long >"${json_file}" 2>/dev/null || true
[ -s "${json_file}" ] || echo '{}' >"${json_file}"

# Render the JSON into a Markdown table via a small deterministic Node
# transform. Columns: package | current | wanted | latest | type.
node -e '
  const fs = require("fs");
  let data = {};
  try { data = JSON.parse(fs.readFileSync(process.argv[1], "utf8")) || {}; }
  catch { data = {}; }

  const rows = Object.entries(data).map(([name, info]) => {
    const i = info && typeof info === "object" ? info : {};
    return {
      name,
      current: i.current || "-",
      wanted: i.wanted || "-",
      latest: i.latest || "-",
      type: i.type || "dependencies",
    };
  }).sort((a, b) => a.name.localeCompare(b.name));

  const lines = ["## 📦 Outdated dependencies", ""];
  if (rows.length === 0) {
    lines.push("All third-party npm dependencies are up to date. ✅");
  } else {
    lines.push(`${rows.length} package(s) have a newer version available:`, "");
    lines.push("| Package | Current | Wanted | Latest | Type |");
    lines.push("| ------- | ------- | ------ | ------ | ---- |");
    for (const r of rows) {
      lines.push(`| \`${r.name}\` | ${r.current} | ${r.wanted} | ${r.latest} | ${r.type} |`);
    }
  }
  lines.push("", "<sub>Generated by the TurboSpec dep-bump report stage.</sub>", "");
  fs.writeFileSync(process.argv[2], lines.join("\n"));
' "${json_file}" "${body_file}"

# Always surface the report in the run log.
cat "${body_file}"

pr="${TURBO_SPEC_PR_NUMBER:-}"
if [ -z "${pr}" ]; then
  echo "outdated-report: no TURBO_SPEC_PR_NUMBER; skipping PR comment." >&2
  exit 0
fi

# Prefer editing the previous comment so retries don't stack duplicates; fall
# back to creating the first one. Never let a comment failure fail the run.
gh pr comment "${pr}" --edit-last --body-file "${body_file}" \
  || gh pr comment "${pr}" --body-file "${body_file}" \
  || echo "outdated-report: failed to post PR comment (non-fatal)." >&2

exit 0
