#!/usr/bin/env bash
# report-comment.sh — stage: report.
#
# Reads the structured artifact .turbo-spec/out/outdated.json (authored by the
# check_outdated_dependencies stage), renders a Markdown report that embeds the
# outdated-dependency table, and upserts it as a single PR comment.
#
# Split responsibilities by failure mode:
#   - Rendering is STRICT: a missing or invalid artifact fails the step, because
#     that means the upstream stage/contract did not deliver what this stage
#     depends on.
#   - Publishing is BEST-EFFORT: no PR context, or a transient gh/network error,
#     must not fail the run — the rendered report is always written to the log.
#
# The comment is upserted via a hidden HTML marker so retries edit the SAME
# comment instead of stacking duplicates, and so it never clobbers an unrelated
# bot comment (unlike `gh pr comment --edit-last`, which edits the actor's most
# recent comment whatever it is).
set -uo pipefail

out_dir=".turbo-spec/out"
json_file="${out_dir}/outdated.json"
body_file="${out_dir}/outdated-report.md"
marker="<!-- turbo-spec:outdated-report -->"
mkdir -p "${out_dir}"

# --- Render (strict) --------------------------------------------------------
if [ ! -s "${json_file}" ]; then
  echo "report-comment: missing ${json_file}; upstream stage did not produce it." >&2
  exit 1
fi

MARKER="${marker}" node -e '
  const fs = require("fs");
  const marker = process.env.MARKER;
  const data = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  if (data.schemaVersion !== 1 || !Array.isArray(data.outdated)) {
    console.error("report-comment: invalid artifact — expected schemaVersion 1 and an outdated array.");
    process.exit(1);
  }
  const rows = data.outdated;

  const lines = [marker, "## 📦 Dependency update report", ""];
  if (rows.length === 0) {
    lines.push("All third-party npm dependencies are up to date. ✅");
  } else {
    lines.push(`${rows.length} package(s) have a newer version available:`, "");
    lines.push("| Package | Current | Wanted | Latest | Type |");
    lines.push("| ------- | ------- | ------ | ------ | ---- |");
    for (const r of rows) {
      lines.push(`| \`${r.name}\` | ${r.current} | ${r.wanted} | ${r.latest} | ${r.type || "dependencies"} |`);
    }
  }
  if (data.generatedAt) {
    lines.push("", `<sub>Collected ${data.generatedAt} · generated by the TurboSpec dep-bump report stage.</sub>`);
  } else {
    lines.push("", "<sub>Generated by the TurboSpec dep-bump report stage.</sub>");
  }
  lines.push("");
  fs.writeFileSync(process.argv[2], lines.join("\n"));
' "${json_file}" "${body_file}" || {
  echo "report-comment: failed to render report from ${json_file}." >&2
  exit 1
}

# Always surface the rendered report in the run log.
cat "${body_file}"

# --- Publish (best-effort) --------------------------------------------------
pr="${TURBO_SPEC_PR_NUMBER:-}"
if [ -z "${pr}" ]; then
  echo "report-comment: no TURBO_SPEC_PR_NUMBER; skipping PR comment." >&2
  exit 0
fi

repo="${GITHUB_REPOSITORY:-}"
if [ -z "${repo}" ]; then
  echo "report-comment: no GITHUB_REPOSITORY; skipping PR comment." >&2
  exit 0
fi

# Find the most recent comment carrying our marker so we edit it in place.
existing_id="$(
  gh api --paginate "repos/${repo}/issues/${pr}/comments" \
    --jq ".[] | select(.body | contains(\"${marker}\")) | .id" 2>/dev/null | tail -n1
)" || existing_id=""

if [ -n "${existing_id}" ]; then
  gh api --method PATCH "repos/${repo}/issues/comments/${existing_id}" \
    -F body=@"${body_file}" >/dev/null 2>&1 \
    && { echo "report-comment: updated comment ${existing_id}."; exit 0; }
  echo "report-comment: failed to update comment ${existing_id}; trying to create a new one." >&2
fi

gh api --method POST "repos/${repo}/issues/${pr}/comments" \
  -F body=@"${body_file}" >/dev/null 2>&1 \
  && echo "report-comment: created new comment on PR #${pr}." \
  || echo "report-comment: failed to post PR comment (non-fatal)." >&2

exit 0
