version: 2
jobs:
  ui_kit_v0_core_dev_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/core/ui-kit
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v0-core-dependencies-{{ checksum "package.json" }}
            - v0-core-dependencies-
      - run:
          name: Install
          command: |
            echo "//porscheui.jfrog.io/porscheui/api/npm/npm/:_authToken=$ARTIFACTORY_TOKEN" >> .npmrc
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v0-core-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run release
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_BRANCH
            popd
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_BRANCH && cp -r ./patternlab/public/. ./$TARGET_BRANCH/$CIRCLE_BRANCH
            pushd $TARGET_BRANCH
              git add -A
              git commit -m "Automated deployment of Porsche UI Kit (${CIRCLE_BRANCH}) to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push origin $TARGET_BRANCH --force-with-lease
            popd
      - run:
          name: GitHub.io URL
          command: |
            echo https://$CIRCLE_PROJECT_USERNAME.github.io/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH/
  ui_kit_v0_react_dev_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/react
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - run:
          name: Install
          command: |
            pushd packages/@porsche/ui-kit-react
              echo "//porscheui.jfrog.io/porscheui/api/npm/npm/:_authToken=$ARTIFACTORY_TOKEN" >> .npmrc
              yarn install
            popd
      - run:
          name: Build
          command: |
            pushd packages/@porsche/ui-kit-react
              yarn run build
            popd
            pushd packages/@porsche/ui-kit-react-docs
              yarn run build
            popd
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_BRANCH
            popd
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_BRANCH && cp -r ./packages/@porsche/ui-kit-react-docs/dist/. ./$TARGET_BRANCH/$CIRCLE_BRANCH
            pushd $TARGET_BRANCH
              git add -A
              git commit -m "Automated deployment of Porsche UI Kit (${CIRCLE_BRANCH}) to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push origin $TARGET_BRANCH --force-with-lease
            popd
      - run:
          name: GitHub.io URL
          command: |
            echo https://$CIRCLE_PROJECT_USERNAME.github.io/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH/
  ui_kit_v1_dev_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - run:
          name: Install npm dependencies
          command: |
            echo "ui_kit_v1_dev_build_deploy"
  ui_kit_v0_core_release_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/core/ui-kit
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v0-core-dependencies-{{ checksum "package.json" }}
            - v0-core-dependencies-
      - run:
          name: Install
          command: |
            echo "//porscheui.jfrog.io/porscheui/api/npm/npm/:_authToken=$ARTIFACTORY_TOKEN" >> .npmrc
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v0-core-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run release
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_TAG
            popd
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_TAG && cp -r ./patternlab/public/. ./$TARGET_BRANCH/$CIRCLE_TAG
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_TAG/../sketch && cp ./../../sketch/porsche-ui-kit.sketch ./$TARGET_BRANCH/$CIRCLE_TAG/../sketch/porsche-ui-kit.sketch
            pushd $TARGET_BRANCH
              git add -A
              git commit -m "Automated deployment of Porsche UI Kit (${CIRCLE_TAG}) to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push origin $TARGET_BRANCH --force-with-lease
            popd
      - run:
          name: GitHub.io URL
          command: |
            echo https://$CIRCLE_PROJECT_USERNAME.github.io/$CIRCLE_PROJECT_REPONAME/$CIRCLE_TAG/
  ui_kit_v0_react_release_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/react
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - run:
          name: Install
          command: |
            pushd packages/@porsche/ui-kit-react
              echo "//porscheui.jfrog.io/porscheui/api/npm/npm/:_authToken=$ARTIFACTORY_TOKEN" >> .npmrc
              yarn install
            popd
      - run:
          name: Build
          command: |
            pushd packages/@porsche/ui-kit-react
              yarn run build
            popd
            pushd packages/@porsche/ui-kit-react-docs
              yarn run build
            popd
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_TAG
            popd
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_TAG && cp -r ./packages/@porsche/ui-kit-react-docs/dist/. ./$TARGET_BRANCH/$CIRCLE_TAG
            pushd $TARGET_BRANCH
              git add -A
              git commit -m "Automated deployment of Porsche UI Kit (${CIRCLE_TAG}) to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push origin $TARGET_BRANCH --force-with-lease
            popd
      - run:
          name: GitHub.io URL
          command: |
            echo https://$CIRCLE_PROJECT_USERNAME.github.io/$CIRCLE_PROJECT_REPONAME/$CIRCLE_TAG/
  ui_kit_v1_release_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - run:
          name: Install npm dependencies
          command: |
            echo "ui_kit_v1_release_build_deploy"
  ui_kit_v0_test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/core/ui-kit
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - deploy:
          name: Deploy
          command: |
            pwd
            ls -al
            pushd ../../
              pwd
              ls -al
            popd
workflows:
  version: 2
  ui_kit_build_deploy:
    jobs:
      - ui_kit_v0_test:
          filters:
            branches:
              only: /.*/
      - ui_kit_v0_core_dev_build_deploy:
          filters:
            branches:
              only: /^issue\/[0-9]+\/v0\.x\/core$/
      - ui_kit_v0_react_dev_build_deploy:
          filters:
            branches:
              only: /^issue\/[0-9]+\/v0\.x\/react$/
      - ui_kit_v1_dev_build_deploy:
          filters:
            branches:
              only: /^issue\/[0-9]+\/v1\.x$/
      - ui_kit_v0_core_release_build_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v0\.[0-9]+\.[0-9]+\/core$/
      - ui_kit_v0_react_release_build_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v0\.[0-9]+\.[0-9]+\/react$/
      - ui_kit_v1_release_build_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v1\.[0-9]+\.[0-9]+$/
