version: 2
jobs:
  ui_kit_v0_core_dev_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/core/ui-kit
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v0-core-dependencies-{{ checksum "package.json" }}
            - v0-core-dependencies-
      - run:
          name: Install
          command: |
            echo "//porscheui.jfrog.io/porscheui/api/npm/npm/:_authToken=$ARTIFACTORY_TOKEN" >> .npmrc
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v0-core-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run release
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_BRANCH
            popd
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_BRANCH && cp -r ./patternlab/public/. ./$TARGET_BRANCH/$CIRCLE_BRANCH
            pushd $TARGET_BRANCH
              git add -A
              git commit -m "Automated deployment of Porsche UI Kit (${CIRCLE_BRANCH}) to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push origin $TARGET_BRANCH --force-with-lease
            popd
      - run:
          name: GitHub.io URL
          command: |
            echo https://$CIRCLE_PROJECT_USERNAME.github.io/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH/
  ui_kit_v0_react_dev_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/react
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - run:
          name: Install
          command: |
            pushd packages/@porsche/ui-kit-react
              echo "//porscheui.jfrog.io/porscheui/api/npm/npm/:_authToken=$ARTIFACTORY_TOKEN" >> .npmrc
              yarn install
            popd
      - run:
          name: Build
          command: |
            pushd packages/@porsche/ui-kit-react
              yarn run build
            popd
            pushd packages/@porsche/ui-kit-react-docs
              yarn run build
            popd
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_BRANCH
            popd
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_BRANCH && cp -r ./packages/@porsche/ui-kit-react-docs/dist/. ./$TARGET_BRANCH/$CIRCLE_BRANCH
            pushd $TARGET_BRANCH
              git add -A
              git commit -m "Automated deployment of Porsche UI Kit (${CIRCLE_BRANCH}) to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push origin $TARGET_BRANCH --force-with-lease
            popd
      - run:
          name: GitHub.io URL
          command: |
            echo https://$CIRCLE_PROJECT_USERNAME.github.io/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH/
  ui_kit_v0_core_release_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/core/ui-kit
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v0-core-dependencies-{{ checksum "package.json" }}
            - v0-core-dependencies-
      - run:
          name: Install
          command: |
            echo "//porscheui.jfrog.io/porscheui/api/npm/npm/:_authToken=$ARTIFACTORY_TOKEN" >> .npmrc
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v0-core-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run release
      - deploy:
          name: Deploy
          command: |
            DATE="$(date -R)"
            LATEST_0X_UI_KIT_CORE_VERSION="$(git tag --sort=-version:refname --list 'v0.*/core' | head -n 1 | cut -d "/" -f1 | cut -c 2-)"
            VERSION_TAG="$(echo $CIRCLE_TAG | cut -d "/" -f1 | cut -c 2-)"

            function v0xCoreReleaseLatest {
              for tag in $(git tag --sort=-version:refname --list 'v0.*/core')
              do
                echo "<p><a href="http://ui.porsche.com/${tag}/">${tag}</a></p>"
                break
              done
            }

            function v0xCoreReleaseHistory {
              echo "<ul>"
              for tag in $(git tag --sort=-version:refname --list 'v0.*/core')
              do
                echo "<li><a href="http://ui.porsche.com/${tag}/">${tag}</a></li>"
              done
              echo "</ul>"
            }

            function v0xReactReleaseLatest {
              for tag in $(git tag --sort=-version:refname --list 'v0.*/react')
              do
                echo "<p><a href="http://ui.porsche.com/${tag}/">${tag}</a></p>"
                break
              done
            }

            function v0xReactReleaseHistory {
              echo "<ul>"
              for tag in $(git tag --sort=-version:refname --list 'v0.*/react')
              do
                echo "<li><a href="http://ui.porsche.com/${tag}/">${tag}</a></li>"
              done
              echo "</ul>"
            }

            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_TAG
            popd

            mkdir -p ./$TARGET_BRANCH/$CIRCLE_TAG && cp -r ./patternlab/public/. ./$TARGET_BRANCH/$CIRCLE_TAG
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_TAG/../sketch && cp ./../../sketch/porsche-ui-kit.sketch ./$TARGET_BRANCH/$CIRCLE_TAG/../sketch/porsche-ui-kit.sketch

            pushd $TARGET_BRANCH
              cat << _EOF_ > index.html
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <title>Porsche UI</title>
            </head>
            <body>
              <h1>Porsche UI Kit</h1>
              <hr>
              <h2>Links</h2>
              <h4>Sketch Library <a href="sketch://add-library?url=https%3A%2F%2Fui.porsche.com%2Fsketch.xml">Link to feed</a> (public)</h4>
              <h4>NPM Packages <a href="https://porscheui.jfrog.io">Link npm registry</a> (private)</h4>
              <h4>SCM <a href="https://github.com/porscheui/porsche-ui-kit">Link to GitHub</a> (private)</h4>
              <h4>Wiki <a href="https://github.com/porscheui/porsche-ui-kit/wiki">Link to GitHub Wiki</a> (private)</h4>
              <h4>Issues <a href="https://github.com/porscheui/porsche-ui-kit/issues">Link to GitHub Issues</a> (private)</h4>
              <h4>Kanban Board <a href="https://github.com/porscheui/porsche-ui-kit/projects/1">Link to GitHub Projects</a> (private)</h4>
              <hr>
              <h2>Documentation</h2>
              <table border="1">
                <tr>
                  <th>Porsche UI Kit v0.x/core</th>
                  <th>Porsche UI Kit v0.x/react</th>
                  <th>Porsche UI Kit v1.x</th>
                </tr>
                <tr>
                  <td valign="top">
                    <h4>Latest Release</h4>
                    $(v0xCoreReleaseLatest)
                  </td>
                  <td valign="top">
                    <h4>Latest Release</h4>
                    $(v0xReactReleaseLatest)
                  </td>
                  <td valign="top">
                    <h4>Latest Release</h4>
                    <p>Not yet available</p>
                  </td>
                </tr>
                <tr>
                  <td valign="top">
                    <h4>History</h4>
                    $(v0xCoreReleaseHistory)
                  </td>
                  <td valign="top">
                    <h4>History</h4>
                    $(v0xReactReleaseHistory)
                  </td>
                  <td valign="top">
                    <h4>History</h4>
                    <p>Not yet available</p>
                  </td>
                </tr>
              </table>
            </body>
            </html>
            _EOF_
            
              cat << _EOF_ > ./sketch.xml
            <?xml version="1.0" encoding="utf-8"?>
            <rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
              <channel>
                <title>Porsche UI</title>
                <description>A Porsche UI Sketch library.</description>
                <item>
                  <title>Porsche UI Kit (v$LATEST_0X_UI_KIT_CORE_VERSION)</title>
                  <pubDate>$(DATE)</pubDate>
                  <enclosure url="https://ui.porsche.com/v$LATEST_0X_UI_KIT_CORE_VERSION/sketch/porsche-ui-kit.sketch" sparkle:version="$LATEST_0X_UI_KIT_CORE_VERSION" type="application/octet-stream"/>
                </item>
              </channel>
            </rss>
            _EOF_
            popd

            pushd $TARGET_BRANCH
              git add -A
              git commit -m "Automated deployment of Porsche UI Kit (${CIRCLE_TAG}) & Porsche UI Kit Sketch Library (${VERSION_TAG}) to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push origin $TARGET_BRANCH --force-with-lease
            popd
      - run:
          name: GitHub.io URL
          command: |
            echo https://$CIRCLE_PROJECT_USERNAME.github.io/$CIRCLE_PROJECT_REPONAME/$CIRCLE_TAG/
  ui_kit_v0_react_release_build_deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/react
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:78:de:a2:82:44:81:31:e6:3e:36:3b:78:80:c0:68"
      - checkout:
          path: ~/repo
      - run:
          name: Install
          command: |
            pushd packages/@porsche/ui-kit-react
              echo "//porscheui.jfrog.io/porscheui/api/npm/npm/:_authToken=$ARTIFACTORY_TOKEN" >> .npmrc
              yarn install
            popd
      - run:
          name: Build
          command: |
            pushd packages/@porsche/ui-kit-react
              yarn run build
            popd
            pushd packages/@porsche/ui-kit-react-docs
              yarn run build
            popd
      - deploy:
          name: Deploy
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_TAG
            popd
            mkdir -p ./$TARGET_BRANCH/$CIRCLE_TAG && cp -r ./packages/@porsche/ui-kit-react-docs/dist/. ./$TARGET_BRANCH/$CIRCLE_TAG
            pushd $TARGET_BRANCH
              git add -A
              git commit -m "Automated deployment of Porsche UI Kit (${CIRCLE_TAG}) to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push origin $TARGET_BRANCH --force-with-lease
            popd
      - run:
          name: GitHub.io URL
          command: |
            echo https://$CIRCLE_PROJECT_USERNAME.github.io/$CIRCLE_PROJECT_REPONAME/$CIRCLE_TAG/
workflows:
  version: 2
  ui_kit_build_deploy:
    jobs:
      - ui_kit_v0_core_dev_build_deploy:
          filters:
            branches:
              only: /^issue\/[0-9]+\/v0\.x\/core$/
      - ui_kit_v0_react_dev_build_deploy:
          filters:
            branches:
              only: /^issue\/[0-9]+\/v0\.x\/react$/
      - ui_kit_v0_core_release_build_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v0\.[0-9]+\.[0-9]+\/core$/
      - ui_kit_v0_react_release_build_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v0\.[0-9]+\.[0-9]+\/react$/
