version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:8
    working_directory: ~/repo/core/ui-kit
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install npm dependencies
          command: |
            echo "//porschedev.jfrog.io/porschedev/api/npm/public-npm/:_authToken=$ARTIFACTORY_TOKEN" >> ~/.npmrc
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Porsche UI Kit
          command: npm run release
      - deploy:
          name: Deploy to GitHub Pages
          command: |
            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
            pushd $TARGET_BRANCH
              rm -rf ./$CIRCLE_BRANCH
            popd
            cp -r ./patternlab/public/. ./$TARGET_BRANCH/$CIRCLE_BRANCH
            pushd $TARGET_BRANCH/master
              echo "pushd gh-pages/master"
              ls -l
            popd

#            git config --global user.email $GH_EMAIL
#            git config --global user.name $GH_NAME
#
#            git clone --single-branch -b $TARGET_BRANCH $CIRCLE_REPOSITORY_URL $TARGET_BRANCH
#
#
#
#            pushd $TARGET_BRANCH
#              git add -A
#              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
#              git push origin $TARGET_BRANCH
#            popd
