options:
  merge-default-rules: true
  max-warnings: 50
files:
  include: 'src/**/*.s+(a|c)ss'
rules:
  attribute-quotes: 2
  bem-depth: 2
  border-zero: 2
  brace-style: 2
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
  clean-import-paths:
    - 2
    -
      filename-extension: true
  declarations-before-nesting: 2
  empty-args: 2
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    -
      convention: hyphenatedlowercase
  hex-length: 2
  hex-notation: 2
  id-name-format: 2
  indentation:
    - 2
    -
      size: 2
  leading-zero: 2
  max-file-line-count: 0
  max-line-length: 0
  mixin-name-format:
    - 2
    -
      convention: hyphenatedlowercase
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    -
      max-depth: 2
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals: 2
  no-combinators: 2
  no-css-comments: 0
  no-debug: 2
  no-disallowed-properties: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format: 2
  property-sort-order: 0
  property-units: 2
  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 0
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property:
    - 0
    -
      properties:
        - 'color'
        - 'padding'
        - 'margin'
        - 'font-size'
        - 'background-color'
        - 'height'
        - 'min-height'
        - 'max-height'
        - 'width'
        - 'min-width'
        - 'min-height'
        - 'left'
        - 'top'
  variable-name-format: 2
  zero-unit: 2
