options:
  merge-default-rules: true
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'src/vehicle-related-services/remote-*.s+(a|c)ss'
    - 'src/vehicle-related-services/shame.scss'
    - 'src/modules/navigation/*.scss'
rules:
  property-sort-order:
    0
  class-name-format:
    - 2
    - convention: hyphenatedbem
  clean-import-paths:
    - 2
    - filename-extension: true
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
  variable-for-property:
  - 0
  -
    'properties':
    - 'color'
    - 'padding'
    - 'margin'
    - 'font-size'
    - 'background-color'
    - 'height'
    - 'min-height'
    - 'max-height'
    - 'width'
    - 'min-width'
    - 'min-height'
    - 'left'
    - 'top'
  space-between-parens:
    - 0
    - include: true
  no-universal-selectors:
    - 2
  no-transition-all:
    - 1
  no-combinators: true
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
  nesting-depth:
    - 2
    -
      max-depth: 2
  variable-name-format:
    1
  single-line-per-selector:
    1
  space-before-brace:
    1
  space-after-comma:
    1
  no-css-comments:
    0
  hex-notation:
    1
  hex-length:
    1
  no-mergeable-selectors:
    1
  final-newline:
    1
  url-quotes:
    1
  no-duplicate-properties:
    1
  indentation:
    1
  empty-line-between-blocks:
    1
  no-important:
    1
  no-vendor-prefixes:
    1
  quotes:
    1
  force-pseudo-nesting:
    1
  force-element-nesting:
    1
  force-attribute-nesting:
    1
