name: 🐞 Bug Report
description: Create a report to help us improve
title: "[BUG] - Short description"
labels: ["bug", "community", "to be refined"]
projects: ["porsche-design-system/14"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: By providing contact details, you agree that they are publicly visible and we may contact you for the purpose of further inquiries.
      placeholder: e.g. email@example.com
  - type: input
    id: framework
    attributes:
      label: JS Framework
      placeholder: e.g. React
    validations:
      required: true
  - type: input
    id: pds-version
    attributes:
      label: Porsche Design System version
      placeholder: e.g. 2.16.0
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: On which device(s) you can see the bug?
      placeholder: e.g. Apple Iphone 14, Google Pixel 6, Mac Sonoma, Windows 11
  - type: dropdown
    id: browsers
    attributes:
      label: In which browsers you can see the bug?
      multiple: true
      options:
        - Firefox
        - Mobile Firefox
        - Chrome
        - Mobile Chrome
        - Safari
        - Mobile Safari
        - Microsoft Edge
  - type: input
    id: browser-version
    attributes:
      label: Browser version
      placeholder: e.g. 106.0.5249.119
  - type: input
    id: reproduction
    attributes:
      label: Reproduction Example
      description: Please provide a minimal reproduction example of the issue using [StackBlitz](https://designsystem.porsche.com/v3/help/bug-report#reproduction).
      placeholder: e.g. https://stackblitz.com/
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Steps to reproduce the behavior
      description: A clear and concise description of what the bug is
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected to see
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste all relevant log outputs. This is automatically formatted into code so no backticks are required.
      render: shell
