name: Open Source Office ORT Docker Login and Pull
description: Login for private docker registry and pull custom image
inputs:
  user:
    description: 'User'
    required: true
  password:
    description: 'Password'
    required: true
runs:
  using: composite
  steps:
    - run: echo ${{ inputs.password }} | docker login -u ${{ inputs.user }} --password-stdin 215495424956.dkr.ecr.eu-central-1.amazonaws.com
      shell: bash
    - run: docker pull 215495424956.dkr.ecr.eu-central-1.amazonaws.com/ort-porsche:latest
      shell: bash
    - run: docker run -v "$PWD":/project 215495424956.dkr.ecr.eu-central-1.amazonaws.com/ort-porsche:latest analyze -i /project/ -o /project/ort/ --package-managers yarn
      shell: bash
