FROM docker.pkg.github.com/porscheui/porsche-design-system/node:12.16.1-stretch

# COPY package.json yarn.lock .npmrc /opt/porsche-design-system-app/
# COPY packages /opt/porsche-design-system-app/packages/

# WORKDIR /opt/porsche-design-system-app

ARG PORSCHE_NPM_REGISTRY_TOKEN
ENV PORSCHE_NPM_REGISTRY_TOKEN=$PORSCHE_NPM_REGISTRY_TOKEN

RUN exec "run-install"
