import { provideZoneChangeDetection } from "@angular/core";
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { componentsReady } from '@porsche-design-system/components-angular';
import { AppModule } from './app/app.module';

// Opt-in via `?eventCoalescing` since it is the default of apps generated by the Angular CLI and changes the timing of
// change detection, but existing tests rely on synchronous change detection
const eventCoalescing = new URLSearchParams(window.location.search).has('eventCoalescing');

platformBrowserDynamic()
  .bootstrapModule(AppModule, { applicationProviders: [provideZoneChangeDetection({ eventCoalescing })], })
  .catch((err) => console.error(err));

(window as any).componentsReady = componentsReady; // for vrt
