'use client';

import type { Story } from '@/models/story';

export const aiTagStoryWithText: Story<'p-ai-tag'> = {
  generator: () => [
    {
      tag: 'p-text',
      children: [
        "This content was generated using artificial intelligence (AI). AI can be a powerful tool for creating content, but it's important to be transparent about its use. By including an AI tag, we can inform users that this content may have been modified or generated by AI, helping to build trust and provide context for the information presented.",
        { tag: 'p-ai-tag', properties: { variant: 'modified', className: 'align-bottom' } },
        ' This is some additional text to show how the AI tag can be used within a text component. The AI tag can be used to indicate that certain content has been modified or generated by AI, providing transparency to users.',
      ],
    },
  ],
};

