import {
  colorBackdrop,
  colorBackdropDark,
  colorBackdropLight,
  colorCanvas,
  colorCanvasDark,
  colorCanvasLight,
  colorContrastHigh,
  colorContrastHighDark,
  colorContrastHigher,
  colorContrastHigherDark,
  colorContrastHigherLight,
  colorContrastHighLight,
  colorContrastLow,
  colorContrastLowDark,
  colorContrastLower,
  colorContrastLowerDark,
  colorContrastLowerLight,
  colorContrastLowLight,
  colorContrastMedium,
  colorContrastMediumDark,
  colorContrastMediumLight,
  colorError,
  colorErrorDark,
  colorErrorFrosted,
  colorErrorFrostedDark,
  colorErrorFrostedLight,
  colorErrorFrostedSoft,
  colorErrorFrostedSoftDark,
  colorErrorFrostedSoftLight,
  colorErrorLight,
  colorErrorLow,
  colorErrorLowDark,
  colorErrorLowLight,
  colorErrorMedium,
  colorErrorMediumDark,
  colorErrorMediumLight,
  colorFocus,
  colorFocusDark,
  colorFocusLight,
  colorFrosted,
  colorFrostedDark,
  colorFrostedLight,
  colorFrostedSoft,
  colorFrostedSoftDark,
  colorFrostedSoftLight,
  colorFrostedStrong,
  colorFrostedStrongDark,
  colorFrostedStrongLight,
  colorInfo,
  colorInfoDark,
  colorInfoFrosted,
  colorInfoFrostedDark,
  colorInfoFrostedLight,
  colorInfoFrostedSoft,
  colorInfoFrostedSoftDark,
  colorInfoFrostedSoftLight,
  colorInfoLight,
  colorInfoLow,
  colorInfoLowDark,
  colorInfoLowLight,
  colorInfoMedium,
  colorInfoMediumDark,
  colorInfoMediumLight,
  colorPrimary,
  colorPrimaryDark,
  colorPrimaryLight,
  colorSuccess,
  colorSuccessDark,
  colorSuccessFrosted,
  colorSuccessFrostedDark,
  colorSuccessFrostedLight,
  colorSuccessFrostedSoft,
  colorSuccessFrostedSoftDark,
  colorSuccessFrostedSoftLight,
  colorSuccessLight,
  colorSuccessLow,
  colorSuccessLowDark,
  colorSuccessLowLight,
  colorSuccessMedium,
  colorSuccessMediumDark,
  colorSuccessMediumLight,
  colorSurface,
  colorSurfaceDark,
  colorSurfaceLight,
  colorWarning,
  colorWarningDark,
  colorWarningFrosted,
  colorWarningFrostedDark,
  colorWarningFrostedLight,
  colorWarningFrostedSoft,
  colorWarningFrostedSoftDark,
  colorWarningFrostedSoftLight,
  colorWarningLight,
  colorWarningLow,
  colorWarningLowDark,
  colorWarningLowLight,
  colorWarningMedium,
  colorWarningMediumDark,
  colorWarningMediumLight,
} from '@porsche-design-system/tokens';
import type { CssVariableTokens } from '../types';

export const color = {
  background: {
    canvas: {
      type: 'color',
      property: '--p-color-canvas',
      description: 'Applies the **canvas** color, typically used for surfaces.',
      value: colorCanvas,
      valueLight: colorCanvasLight,
      valueDark: colorCanvasDark,
    },
    surface: {
      type: 'color',
      property: '--p-color-surface',
      description: 'Applies the **surface** color, typically used for surfaces.',
      value: colorSurface,
      valueLight: colorSurfaceLight,
      valueDark: colorSurfaceDark,
    },
    frosted: {
      type: 'color',
      property: '--p-color-frosted',
      description: 'Applies the **frosted** color, typically used as a background in combination with a blur effect.',
      value: colorFrosted,
      valueLight: colorFrostedLight,
      valueDark: colorFrostedDark,
    },
    frostedSoft: {
      type: 'color',
      property: '--p-color-frosted-soft',
      description: 'Applies the **frosted** color, typically used as a background `:hover`.',
      value: colorFrostedSoft,
      valueLight: colorFrostedSoftLight,
      valueDark: colorFrostedSoftDark,
    },
    frostedStrong: {
      type: 'color',
      property: '--p-color-frosted-strong',
      description:
        'Applies the **frosted-strong** color, typically used as a background in combination with a blur effect.',
      value: colorFrostedStrong,
      valueLight: colorFrostedStrongLight,
      valueDark: colorFrostedStrongDark,
    },
    backdrop: {
      type: 'color',
      property: '--p-color-backdrop',
      description: 'Applies the **backdrop** color, typically used for backdrops.',
      value: colorBackdrop,
      valueLight: colorBackdropLight,
      valueDark: colorBackdropDark,
    },
  },
  foreground: {
    primary: {
      type: 'color',
      property: '--p-color-primary',
      description: 'Applies the **primary** color, typically used for text.',
      value: colorPrimary,
      valueLight: colorPrimaryLight,
      valueDark: colorPrimaryDark,
    },
    contrastHigher: {
      type: 'color',
      property: '--p-color-contrast-higher',
      description: 'Applies the **contrast-higher** color, typically used for text.',
      value: colorContrastHigher,
      valueLight: colorContrastHigherLight,
      valueDark: colorContrastHigherDark,
    },
    contrastHigh: {
      type: 'color',
      property: '--p-color-contrast-high',
      description: 'Applies the **contrast-high** color, typically used for text.',
      value: colorContrastHigh,
      valueLight: colorContrastHighLight,
      valueDark: colorContrastHighDark,
    },
    contrastMedium: {
      type: 'color',
      property: '--p-color-contrast-medium',
      description: 'Applies the **contrast-medium** color, typically used for text.',
      value: colorContrastMedium,
      valueLight: colorContrastMediumLight,
      valueDark: colorContrastMediumDark,
    },
    contrastLow: {
      type: 'color',
      property: '--p-color-contrast-low',
      description:
        'Applies the **contrast-low** color, intended only for decorative elements, as it is not accessibility-compliant.',
      value: colorContrastLow,
      valueLight: colorContrastLowLight,
      valueDark: colorContrastLowDark,
    },
    contrastLower: {
      type: 'color',
      property: '--p-color-contrast-lower',
      description:
        'Applies the **contrast-lower** color, intended only for decorative elements, as it is not accessibility-compliant.',
      value: colorContrastLower,
      valueLight: colorContrastLowerLight,
      valueDark: colorContrastLowerDark,
    },
  },
  semantic: {
    info: {
      type: 'color',
      property: '--p-color-info',
      description: 'Applies the **info** color, typically used for text.',
      value: colorInfo,
      valueLight: colorInfoLight,
      valueDark: colorInfoDark,
    },
    infoMedium: {
      type: 'color',
      property: '--p-color-info-medium',
      description: 'Applies the **info** color, typically used for text or border.',
      value: colorInfoMedium,
      valueLight: colorInfoMediumLight,
      valueDark: colorInfoMediumDark,
    },
    infoLow: {
      type: 'color',
      property: '--p-color-info-low',
      description: 'Applies the **info** color, typically used for text or border.',
      value: colorInfoLow,
      valueLight: colorInfoLowLight,
      valueDark: colorInfoLowDark,
    },
    infoFrosted: {
      type: 'color',
      property: '--p-color-info-frosted',
      description:
        'Applies the **info-frosted** color, typically used as background in combination with a blur effect.',
      value: colorInfoFrosted,
      valueLight: colorInfoFrostedLight,
      valueDark: colorInfoFrostedDark,
    },
    infoFrostedSoft: {
      type: 'color',
      property: '--p-color-info-frosted-soft',
      description: 'Applies the **info-frosted-soft** color, typically used as background `:hover`.',
      value: colorInfoFrostedSoft,
      valueLight: colorInfoFrostedSoftLight,
      valueDark: colorInfoFrostedSoftDark,
    },
    success: {
      type: 'color',
      property: '--p-color-success',
      description: 'Applies the **success** color, typically used for text.',
      value: colorSuccess,
      valueLight: colorSuccessLight,
      valueDark: colorSuccessDark,
    },
    successMedium: {
      type: 'color',
      property: '--p-color-success-medium',
      description: 'Applies the **success** color, typically used for text or border.',
      value: colorSuccessMedium,
      valueLight: colorSuccessMediumLight,
      valueDark: colorSuccessMediumDark,
    },
    successLow: {
      type: 'color',
      property: '--p-color-success-low',
      description: 'Applies the **success** color, typically used for text or border.',
      value: colorSuccessLow,
      valueLight: colorSuccessLowLight,
      valueDark: colorSuccessLowDark,
    },
    successFrosted: {
      type: 'color',
      property: '--p-color-success-frosted',
      description:
        'Applies the **success-frosted** color, typically used as background in combination with a blur effect.',
      value: colorSuccessFrosted,
      valueLight: colorSuccessFrostedLight,
      valueDark: colorSuccessFrostedDark,
    },
    successFrostedSoft: {
      type: 'color',
      property: '--p-color-success-frosted-soft',
      description: 'Applies the **success-frosted-soft** color, typically used as background `:hover`.',
      value: colorSuccessFrostedSoft,
      valueLight: colorSuccessFrostedSoftLight,
      valueDark: colorSuccessFrostedSoftDark,
    },
    warning: {
      type: 'color',
      property: '--p-color-warning',
      description: 'Applies the **warning** color, typically used for text.',
      value: colorWarning,
      valueLight: colorWarningLight,
      valueDark: colorWarningDark,
    },
    warningMedium: {
      type: 'color',
      property: '--p-color-warning-medium',
      description: 'Applies the **warning** color, typically used for text or border.',
      value: colorWarningMedium,
      valueLight: colorWarningMediumLight,
      valueDark: colorWarningMediumDark,
    },
    warningLow: {
      type: 'color',
      property: '--p-color-warning-low',
      description: 'Applies the **warning** color, typically used for text or border.',
      value: colorWarningLow,
      valueLight: colorWarningLowLight,
      valueDark: colorWarningLowDark,
    },
    warningFrosted: {
      type: 'color',
      property: '--p-color-warning-frosted',
      description:
        'Applies the **warning-frosted** color, typically used as background in combination with a blur effect.',
      value: colorWarningFrosted,
      valueLight: colorWarningFrostedLight,
      valueDark: colorWarningFrostedDark,
    },
    warningFrostedSoft: {
      type: 'color',
      property: '--p-color-warning-frosted-soft',
      description: 'Applies the **warning-frosted-soft** color, typically used as background `:hover`.',
      value: colorWarningFrostedSoft,
      valueLight: colorWarningFrostedSoftLight,
      valueDark: colorWarningFrostedSoftDark,
    },
    error: {
      type: 'color',
      property: '--p-color-error',
      description: 'Applies the **error** color, typically used for text.',
      value: colorError,
      valueLight: colorErrorLight,
      valueDark: colorErrorDark,
    },
    errorMedium: {
      type: 'color',
      property: '--p-color-error-medium',
      description: 'Applies the **error** color, typically used for text or border.',
      value: colorErrorMedium,
      valueLight: colorErrorMediumLight,
      valueDark: colorErrorMediumDark,
    },
    errorLow: {
      type: 'color',
      property: '--p-color-error-low',
      description: 'Applies the **error** color, typically used for text or border.',
      value: colorErrorLow,
      valueLight: colorErrorLowLight,
      valueDark: colorErrorLowDark,
    },
    errorFrosted: {
      type: 'color',
      property: '--p-color-error-frosted',
      description:
        'Applies the **error-frosted** color, typically used as background in combination with a blur effect.',
      value: colorErrorFrosted,
      valueLight: colorErrorFrostedLight,
      valueDark: colorErrorFrostedDark,
    },
    errorFrostedSoft: {
      type: 'color',
      property: '--p-color-error-frosted-soft',
      description: 'Applies the **error-frosted-soft** color, typically used as background `:hover`.',
      value: colorErrorFrostedSoft,
      valueLight: colorErrorFrostedSoftLight,
      valueDark: colorErrorFrostedSoftDark,
    },
  },
  a11y: {
    focus: {
      type: 'color',
      property: '--p-color-focus',
      description: 'Applies the **focus** color, typically used as the outline for `:focus-visible` states.',
      value: colorFocus,
      valueLight: colorFocusLight,
      valueDark: colorFocusDark,
    },
  },
} satisfies CssVariableTokens['color'];
