import {
  themeDarkBackgroundBase,
  themeDarkBackgroundFrosted,
  themeDarkBackgroundShading,
  themeDarkBackgroundSurface,
  themeDarkContrastHigh,
  themeDarkContrastLow,
  themeDarkContrastMedium,
  themeDarkNotificationError,
  themeDarkNotificationErrorSoft,
  themeDarkNotificationInfo,
  themeDarkNotificationInfoSoft,
  themeDarkNotificationSuccess,
  themeDarkNotificationSuccessSoft,
  themeDarkNotificationWarning,
  themeDarkNotificationWarningSoft,
  themeDarkPrimary,
  themeDarkStateFocus,
  themeLightBackgroundBase,
  themeLightBackgroundFrosted,
  themeLightBackgroundShading,
  themeLightBackgroundSurface,
  themeLightContrastHigh,
  themeLightContrastLow,
  themeLightContrastMedium,
  themeLightNotificationError,
  themeLightNotificationErrorSoft,
  themeLightNotificationInfo,
  themeLightNotificationInfoSoft,
  themeLightNotificationSuccess,
  themeLightNotificationSuccessSoft,
  themeLightNotificationWarning,
  themeLightNotificationWarningSoft,
  themeLightPrimary,
  themeLightStateDisabled,
  themeLightStateFocus,
} from '@porsche-design-system/vanilla-extract';
import { createTheme, createThemeContract } from '@vanilla-extract/css';

export const vars = createThemeContract({
  focus: null,
  disabled: null,
  canvas: null,
  surface: null,
  frosted: null,
  frostedSoft: null,
  backdrop: null,
  contrastLower: null,
  contrastLow: null,
  contrastMedium: null,
  contrastHigh: null,
  contrastHigher: null,
  primary: null,
  success: null,
  successLow: null,
  successMedium: null,
  successFrosted: null,
  successFrostedSoft: null,
  warning: null,
  warningLow: null,
  warningMedium: null,
  warningFrosted: null,
  warningFrostedSoft: null,
  error: null,
  errorLow: null,
  errorMedium: null,
  errorFrosted: null,
  errorFrostedSoft: null,
  info: null,
  infoLow: null,
  infoMedium: null,
  infoFrosted: null,
  infoFrostedSoft: null,
  skeleton: null,
});

export const lightTheme = createTheme(vars, {
  focus: themeLightStateFocus,
  disabled: themeLightStateDisabled,
  canvas: themeLightBackgroundBase,
  surface: themeLightBackgroundSurface,
  frosted: themeLightBackgroundFrosted,
  frostedSoft: 'hsla(234, 9.8%, 60%, 0.06)',
  backdrop: themeLightBackgroundShading,
  contrastLower: 'hsla(234, 6%, 32.9%, 0.324)',
  contrastLow: themeLightContrastLow,
  contrastMedium: themeLightContrastMedium,
  contrastHigh: themeLightContrastHigh,
  contrastHigher: 'hsla(240, 8.7%, 9%, 0.8)',
  primary: themeLightPrimary,
  success: themeLightNotificationSuccess,
  successLow: 'hsla(115, 77.5%, 27.8%, 0.18)',
  successMedium: 'hsla(115, 77.5%, 27.8%, 0.6)',
  successFrosted: themeLightNotificationSuccessSoft,
  successFrostedSoft: 'hsla(115, 77.5%, 27.8%, 0.1)',
  warning: themeLightNotificationWarning,
  warningLow: 'hsla(28, 97.7%, 34.1%, 0.18)',
  warningMedium: 'hsla(28, 97.7%, 34.1%, 0.6)',
  warningFrosted: themeLightNotificationWarningSoft,
  warningFrostedSoft: 'hsla(28, 97.7%, 34.1%, 0.1)',
  error: themeLightNotificationError,
  errorLow: 'hsla(357, 78%, 41%, 0.18)',
  errorMedium: 'hsla(357, 78%, 41%, 0.6)',
  errorFrosted: themeLightNotificationErrorSoft,
  errorFrostedSoft: 'hsla(357, 78%, 41%, 0.1)',
  info: themeLightNotificationInfo,
  infoLow: 'hsla(228, 83.2%, 51%, 0.18)',
  infoMedium: 'hsla(228, 83.2%, 51%, 0.6)',
  infoFrosted: themeLightNotificationInfoSoft,
  infoFrostedSoft: 'hsla(228, 83.2%, 51%, 0.1)',
  skeleton: '#f7f7f7',
});

export const darkTheme = createTheme(vars, {
  focus: themeDarkStateFocus,
  disabled: themeDarkStateFocus,
  canvas: themeDarkBackgroundBase,
  surface: themeDarkBackgroundSurface,
  frosted: themeDarkBackgroundFrosted,
  frostedSoft: 'hsla(240, 3.7%, 26.5%, 0.154)',
  backdrop: themeDarkBackgroundShading,
  contrastLower: 'hsla(240, 1.5%, 61.8%, 0.302)',
  contrastLow: themeDarkContrastLow,
  contrastMedium: themeDarkContrastMedium,
  contrastHigh: themeDarkContrastHigh,
  contrastHigher: 'hsla(240, 12.5%, 96.9%, 0.78)',
  primary: themeDarkPrimary,
  success: themeDarkNotificationSuccess,
  successLow: 'hsla(157, 84.9%, 41.6%, 0.18)',
  successMedium: 'hsla(157, 84.9%, 41.6%, 0.6)',
  successFrosted: themeDarkNotificationSuccessSoft,
  successFrostedSoft: 'hsla(157, 84.9%, 41.6%, 0.1)',
  warning: themeDarkNotificationWarning,
  warningLow: 'hsla(28, 90.2%, 56.1%, 0.18)',
  warningMedium: 'hsla(28, 90.2%, 56.1%, 0.6)',
  warningFrosted: themeDarkNotificationWarningSoft,
  warningFrostedSoft: 'hsla(28, 90.2%, 56.1%, 0.1)',
  error: themeDarkNotificationError,
  errorLow: 'hsla(0, 96.9%, 62%, 0.18)',
  errorMedium: 'hsla(0, 96.9%, 62%, 0.6)',
  errorFrosted: themeDarkNotificationErrorSoft,
  errorFrostedSoft: 'hsla(0, 96.9%, 62%, 0.1)',
  info: themeDarkNotificationInfo,
  infoLow: 'hsla(210, 100%, 54.5%, 0.18)',
  infoMedium: 'hsla(210, 100%, 54.5%, 0.6)',
  infoFrosted: themeDarkNotificationInfoSoft,
  infoFrostedSoft: 'hsla(210, 100%, 54.5%, 0.1)',
  skeleton: '#1a1b1e',
});

export const autoTheme = darkTheme;
