import {
  colorBackdrop,
  colorCanvas,
  colorContrastHigh,
  colorContrastHigher,
  colorContrastLow,
  colorContrastLower,
  colorContrastMedium,
  colorError,
  colorErrorFrosted,
  colorErrorFrostedSoft,
  colorErrorLow,
  colorErrorMedium,
  colorFocus,
  colorFrosted,
  colorFrostedSoft,
  colorFrostedStrong,
  colorInfo,
  colorInfoFrosted,
  colorInfoFrostedSoft,
  colorInfoLow,
  colorInfoMedium,
  colorPrimary,
  colorSuccess,
  colorSuccessFrosted,
  colorSuccessFrostedSoft,
  colorSuccessLow,
  colorSuccessMedium,
  colorSurface,
  colorWarning,
  colorWarningFrosted,
  colorWarningFrostedSoft,
  colorWarningLow,
  colorWarningMedium,
} from '@porsche-design-system/vanilla-extract';
import { createTheme } from '@vanilla-extract/css';

export const [vanillaExtractTheme, vars] = createTheme({
  focus: colorFocus,
  canvas: colorCanvas,
  surface: colorSurface,
  frosted: colorFrosted,
  frostedSoft: colorFrostedSoft,
  frostedStrong: colorFrostedStrong,
  backdrop: colorBackdrop,
  contrastLower: colorContrastLower,
  contrastLow: colorContrastLow,
  contrastMedium: colorContrastMedium,
  contrastHigh: colorContrastHigh,
  contrastHigher: colorContrastHigher,
  primary: colorPrimary,
  success: colorSuccess,
  successLow: colorSuccessLow,
  successMedium: colorSuccessMedium,
  successFrosted: colorSuccessFrosted,
  successFrostedSoft: colorSuccessFrostedSoft,
  warning: colorWarning,
  warningLow: colorWarningLow,
  warningMedium: colorWarningMedium,
  warningFrosted: colorWarningFrosted,
  warningFrostedSoft: colorWarningFrostedSoft,
  error: colorError,
  errorLow: colorErrorLow,
  errorMedium: colorErrorMedium,
  errorFrosted: colorErrorFrosted,
  errorFrostedSoft: colorErrorFrostedSoft,
  info: colorInfo,
  infoLow: colorInfoLow,
  infoMedium: colorInfoMedium,
  infoFrosted: colorInfoFrosted,
  infoFrostedSoft: colorInfoFrostedSoft,
});
