name: Docker Login and Pull
description: Login for private docker registry and pull custom image
runs:
  using: composite
  steps:
    - run: echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      shell: bash
    - run: docker pull docker.pkg.github.com/porscheui/porsche-design-system/node:14.15.1-stretch-slim
      shell: bash
