/// <reference types="@figma/code-connect/figma-types-no-require" />
// url=https://www.figma.com/design/bEXOI0BAd6pXjvIG1mpWIN/Porsche-Web-Design-System--Renato-Code-Connect--Copy-?node-id=55823-8373
// source=https://designsystem.porsche.com/v4/components/flag/api
// component=PFlag
// Auto generated - do not edit by hand.
import figma from 'figma';

const instance = figma.selectedInstance;

const name = instance.getEnum('name', {
  ad: 'ad',
  ae: 'ae',
  al: 'al',
  am: 'am',
  ar: 'ar',
  at: 'at',
  au: 'au',
  az: 'az',
  ba: 'ba',
  bd: 'bd',
  be: 'be',
  bg: 'bg',
  bh: 'bh',
  bn: 'bn',
  bo: 'bo',
  br: 'br',
  by: 'by',
  ca: 'ca',
  ch: 'ch',
  cl: 'cl',
  cn: 'cn',
  co: 'co',
  cr: 'cr',
  cw: 'cw',
  cy: 'cy',
  cz: 'cz',
  de: 'de',
  dk: 'dk',
  do: 'do',
  dz: 'dz',
  ec: 'ec',
  ee: 'ee',
  eg: 'eg',
  es: 'es',
  fi: 'fi',
  fr: 'fr',
  gb: 'gb',
  ge: 'ge',
  gh: 'gh',
  gi: 'gi',
  gr: 'gr',
  gt: 'gt',
  hk: 'hk',
  hn: 'hn',
  hr: 'hr',
  ht: 'ht',
  hu: 'hu',
  id: 'id',
  ie: 'ie',
  il: 'il',
  in: 'in',
  is: 'is',
  it: 'it',
  jm: 'jm',
  jo: 'jo',
  jp: 'jp',
  ke: 'ke',
  kh: 'kh',
  kr: 'kr',
  kw: 'kw',
  kz: 'kz',
  lb: 'lb',
  li: 'li',
  lk: 'lk',
  lt: 'lt',
  lu: 'lu',
  lv: 'lv',
  ma: 'ma',
  mc: 'mc',
  md: 'md',
  me: 'me',
  mk: 'mk',
  mn: 'mn',
  mo: 'mo',
  mq: 'mq',
  mt: 'mt',
  mu: 'mu',
  mx: 'mx',
  my: 'my',
  ng: 'ng',
  nl: 'nl',
  no: 'no',
  nz: 'nz',
  om: 'om',
  pa: 'pa',
  pe: 'pe',
  pf: 'pf',
  ph: 'ph',
  pk: 'pk',
  pl: 'pl',
  pr: 'pr',
  pt: 'pt',
  py: 'py',
  qa: 'qa',
  re: 're',
  ro: 'ro',
  rs: 'rs',
  ru: 'ru',
  sa: 'sa',
  se: 'se',
  sg: 'sg',
  si: 'si',
  sk: 'sk',
  sv: 'sv',
  th: 'th',
  tn: 'tn',
  tr: 'tr',
  tt: 'tt',
  tw: 'tw',
  ua: 'ua',
  us: 'us',
  uy: 'uy',
  uz: 'uz',
  ve: 've',
  vn: 'vn',
  xx: 'xx',
  za: 'za',
});

export default {
  example: figma.code`<PFlag name="${name}"></PFlag>`,
  imports: [
    '// Docs: https://designsystem.porsche.com/v4/components/flag/api',
    "import { PFlag } from '@porsche-design-system/components-react';",
  ],
  id: 'p-flag',
  metadata: { nestable: true },
};
