export {
  spacing,
  spacingStatic,
  spacingFluid,
  spacingStaticXSmall,
  spacingStaticSmall,
  spacingStaticMedium,
  spacingStaticLarge,
  spacingStaticXLarge,
  spacingStaticXXLarge,
  spacingFluidXSmall,
  spacingFluidSmall,
  spacingFluidMedium,
  spacingFluidLarge,
  spacingFluidXLarge,
} from './spacing';
