name: 'Install'

inputs:
  rclone:
    description: 'Install rclone'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: 'Cache node_modules'
      uses: actions/cache@v4
      id: cache-node_modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: 'Install node_modules'
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash
    - name: 'Install rclone'
      if: inputs.rclone == 'true'
      run: |
        sudo apt-get -yq --no-install-suggests --no-install-recommends install rclone
      shell: bash
