// common type definitions
export type TextSize = 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'inherit';

export type TextWeight = 'thin' | 'regular' | 'semibold' | 'bold';

export type HeadlineVariant = 'large-title' | 'headline-1' | 'headline-2' | 'headline-3' | 'headline-4' | 'headline-5';

export type Theme = 'light' | 'dark';

export type ButtonType = 'button' | 'submit' | 'reset';

export type LinkTarget = '_self' | '_blank' | '_parent' | '_top' | string;

export type FormState = 'none' | 'error' | 'success';

/* Auto Generated Below */

export type IconName = '360'
| 'add'
| 'adjust'
| 'arrow-double-down'
| 'arrow-double-left'
| 'arrow-double-right'
| 'arrow-double-up'
| 'arrow-down'
| 'arrow-first'
| 'arrow-head-down'
| 'arrow-head-left'
| 'arrow-head-right'
| 'arrow-head-up'
| 'arrow-last'
| 'arrow-left'
| 'arrow-right'
| 'arrow-up'
| 'augmented-reality'
| 'battery-empty'
| 'broadcast'
| 'calculator'
| 'calendar'
| 'camera'
| 'car'
| 'card'
| 'charging-station'
| 'chart'
| 'chat'
| 'check'
| 'city'
| 'clock'
| 'close'
| 'closed-caption'
| 'co2-emission'
| 'compare'
| 'configurate'
| 'country-road'
| 'cubic-capacity'
| 'delete'
| 'disable'
| 'document'
| 'download'
| 'duration'
| 'edit'
| 'email'
| 'exclamation'
| 'external'
| 'filter'
| 'flash'
| 'fuel-station'
| 'gift'
| 'globe'
| 'grid'
| 'highway'
| 'home'
| 'image'
| 'increase'
| 'information'
| 'leaf'
| 'leather'
| 'light'
| 'list'
| 'locate'
| 'lock'
| 'lock-open'
| 'logo-baidu'
| 'logo-delicious'
| 'logo-digg'
| 'logo-facebook'
| 'logo-foursquare'
| 'logo-gmail'
| 'logo-google'
| 'logo-hatena'
| 'logo-instagram'
| 'logo-kaixin'
| 'logo-linkedin'
| 'logo-pinterest'
| 'logo-qq'
| 'logo-qq-share'
| 'logo-skyrock'
| 'logo-sohu'
| 'logo-tecent'
| 'logo-telegram'
| 'logo-tumblr'
| 'logo-twitter'
| 'logo-viber'
| 'logo-vk'
| 'logo-wechat'
| 'logo-weibo'
| 'logo-whatsapp'
| 'logo-xing'
| 'logo-yahoo'
| 'logo-youku'
| 'logo-youtube'
| 'logout'
| 'menu-dots-horizontal'
| 'menu-lines'
| 'minus'
| 'mobile'
| 'moon'
| 'oil-can'
| 'pause'
| 'phone'
| 'pin'
| 'play'
| 'plug'
| 'plus'
| 'printer'
| 'purchase'
| 'question'
| 'racing-flag'
| 'refresh'
| 'replay'
| 'reset'
| 'route'
| 'rss'
| 'save'
| 'screen'
| 'search'
| 'share'
| 'shopping-cart'
| 'snowflake'
| 'sort'
| 'stack'
| 'star'
| 'steering-wheel'
| 'stopwatch'
| 'subtract'
| 'sun'
| 'switch'
| 'tablet'
| 'tachometer'
| 'truck'
| 'upload'
| 'user'
| 'user-group'
| 'video'
| 'view'
| 'view-off'
| 'volume-off'
| 'volume-up'
| 'warning'
| 'weight'
| 'wifi'
| 'work'
| 'wrench'
| 'zoom-in'
| 'zoom-out';