import {
  colorBackdropDark,
  colorBackdropLight,
  colorCanvasDark,
  colorCanvasLight,
  colorContrastHighDark,
  colorContrastHigherDark,
  colorContrastHigherLight,
  colorContrastHighLight,
  colorContrastLowDark,
  colorContrastLowerDark,
  colorContrastLowerLight,
  colorContrastLowLight,
  colorContrastMediumDark,
  colorContrastMediumLight,
  colorErrorDark,
  colorErrorFrostedDark,
  colorErrorFrostedLight,
  colorErrorFrostedSoftDark,
  colorErrorFrostedSoftLight,
  colorErrorLight,
  colorErrorLowDark,
  colorErrorLowLight,
  colorErrorMediumDark,
  colorErrorMediumLight,
  colorFocusDark,
  colorFocusLight,
  colorFrostedDark,
  colorFrostedLight,
  colorFrostedSoftDark,
  colorFrostedSoftLight,
  colorFrostedStrongDark,
  colorFrostedStrongLight,
  colorInfoDark,
  colorInfoFrostedDark,
  colorInfoFrostedLight,
  colorInfoFrostedSoftDark,
  colorInfoFrostedSoftLight,
  colorInfoLight,
  colorInfoLowDark,
  colorInfoLowLight,
  colorInfoMediumDark,
  colorInfoMediumLight,
  colorPrimaryDark,
  colorPrimaryLight,
  colorSuccessDark,
  colorSuccessFrostedDark,
  colorSuccessFrostedLight,
  colorSuccessFrostedSoftDark,
  colorSuccessFrostedSoftLight,
  colorSuccessLight,
  colorSuccessLowDark,
  colorSuccessLowLight,
  colorSuccessMediumDark,
  colorSuccessMediumLight,
  colorSurfaceDark,
  colorSurfaceLight,
  colorWarningDark,
  colorWarningFrostedDark,
  colorWarningFrostedLight,
  colorWarningFrostedSoftDark,
  colorWarningFrostedSoftLight,
  colorWarningLight,
  colorWarningLowDark,
  colorWarningLowLight,
  colorWarningMediumDark,
  colorWarningMediumLight,
} from '@porsche-design-system/tokens';

const lightColorVariables = {
  '--_color-focus': colorFocusLight,
  '--_color-canvas': colorCanvasLight,
  '--_color-surface': colorSurfaceLight,
  '--_color-frosted': colorFrostedLight,
  '--_color-frosted-soft': colorFrostedSoftLight,
  '--_color-frosted-strong': colorFrostedStrongLight,
  '--_color-backdrop': colorBackdropLight,
  '--_color-contrast-lower': colorContrastLowerLight,
  '--_color-contrast-low': colorContrastLowLight,
  '--_color-contrast-medium': colorContrastMediumLight,
  '--_color-contrast-high': colorContrastHighLight,
  '--_color-contrast-higher': colorContrastHigherLight,
  '--_color-primary': colorPrimaryLight,
  '--_color-success': colorSuccessLight,
  '--_color-success-low': colorSuccessLowLight,
  '--_color-success-medium': colorSuccessMediumLight,
  '--_color-success-frosted': colorSuccessFrostedLight,
  '--_color-success-frosted-soft': colorSuccessFrostedSoftLight,
  '--_color-warning': colorWarningLight,
  '--_color-warning-low': colorWarningLowLight,
  '--_color-warning-medium': colorWarningMediumLight,
  '--_color-warning-frosted': colorWarningFrostedLight,
  '--_color-warning-frosted-soft': colorWarningFrostedSoftLight,
  '--_color-error': colorErrorLight,
  '--_color-error-low': colorErrorLowLight,
  '--_color-error-medium': colorErrorMediumLight,
  '--_color-error-frosted': colorErrorFrostedLight,
  '--_color-error-frosted-soft': colorErrorFrostedSoftLight,
  '--_color-info': colorInfoLight,
  '--_color-info-low': colorInfoLowLight,
  '--_color-info-medium': colorInfoMediumLight,
  '--_color-info-frosted': colorInfoFrostedLight,
  '--_color-info-frosted-soft': colorInfoFrostedSoftLight,
};

const darkColorVariables = {
  '--_color-focus': colorFocusDark,
  '--_color-canvas': colorCanvasDark,
  '--_color-surface': colorSurfaceDark,
  '--_color-frosted': colorFrostedDark,
  '--_color-frosted-soft': colorFrostedSoftDark,
  '--_color-frosted-strong': colorFrostedStrongDark,
  '--_color-backdrop': colorBackdropDark,
  '--_color-contrast-lower': colorContrastLowerDark,
  '--_color-contrast-low': colorContrastLowDark,
  '--_color-contrast-medium': colorContrastMediumDark,
  '--_color-contrast-high': colorContrastHighDark,
  '--_color-contrast-higher': colorContrastHigherDark,
  '--_color-primary': colorPrimaryDark,
  '--_color-success': colorSuccessDark,
  '--_color-success-low': colorSuccessLowDark,
  '--_color-success-medium': colorSuccessMediumDark,
  '--_color-success-frosted': colorSuccessFrostedDark,
  '--_color-success-frosted-soft': colorSuccessFrostedSoftDark,
  '--_color-warning': colorWarningDark,
  '--_color-warning-low': colorWarningLowDark,
  '--_color-warning-medium': colorWarningMediumDark,
  '--_color-warning-frosted': colorWarningFrostedDark,
  '--_color-warning-frosted-soft': colorWarningFrostedSoftDark,
  '--_color-error': colorErrorDark,
  '--_color-error-low': colorErrorLowDark,
  '--_color-error-medium': colorErrorMediumDark,
  '--_color-error-frosted': colorErrorFrostedDark,
  '--_color-error-frosted-soft': colorErrorFrostedSoftDark,
  '--_color-info': colorInfoDark,
  '--_color-info-low': colorInfoLowDark,
  '--_color-info-medium': colorInfoMediumDark,
  '--_color-info-frosted': colorInfoFrostedDark,
  '--_color-info-frosted-soft': colorInfoFrostedSoftDark,
};

export const colorSchemeStyles = [
  {
    selector: '.scheme-normal',
    rule: { colorScheme: 'normal' },
  },
  {
    selector: '.scheme-dark',
    rule: { colorScheme: 'dark' },
  },
  {
    selector: '.scheme-light',
    rule: { colorScheme: 'light' },
  },
  {
    selector: '.scheme-light-dark',
    rule: { colorScheme: 'light dark' },
  },
  {
    selector: '.scheme-only-dark',
    rule: { colorScheme: 'only dark' },
  },
  {
    selector: '.scheme-only-light',
    rule: { colorScheme: 'only light' },
  },
  {
    selector: ':root, .scheme-light, .scheme-only-light, .scheme-normal, .scheme-light-dark',
    rule: { '@supports': { 'not (color: light-dark(white, black))': lightColorVariables } },
  },
  {
    selector: '.scheme-dark, .scheme-only-dark',
    rule: { '@supports': { 'not (color: light-dark(white, black))': darkColorVariables } },
  },
  {
    selector: '.scheme-light-dark',
    rule: {
      '@supports': {
        'not (color: light-dark(white, black))': {
          '@media': { '(prefers-color-scheme: dark)': darkColorVariables },
        },
      },
    },
  },
];
