export * from './deprecated';
export { proseHeading2XlStyle } from './proseHeading2XlStyle';
export { proseHeading3XlStyle } from './proseHeading3XlStyle';
export { proseHeading4XlStyle } from './proseHeading4XlStyle';
export { proseHeading5XlStyle } from './proseHeading5XlStyle';
export { proseHeadingLgStyle } from './proseHeadingLgStyle';
export { proseHeadingMdStyle } from './proseHeadingMdStyle';
export { proseHeadingSmStyle } from './proseHeadingSmStyle';
export { proseHeadingXlStyle } from './proseHeadingXlStyle';
export { proseText2XsStyle } from './proseText2XsStyle';
export { proseTextLgStyle } from './proseTextLgStyle';
export { proseTextMdStyle } from './proseTextMdStyle';
export { proseTextSmStyle } from './proseTextSmStyle';
export { proseTextXlStyle } from './proseTextXlStyle';
export { proseTextXsStyle } from './proseTextXsStyle';
