import type { VanillaExtractMeta } from '../types/vanilla-extract-meta';

export type VanillaExtractMetaTree = { [key: string]: VanillaExtractMetaTree | VanillaExtractMeta };

export const vanillaExtractMeta = {
  blur: {
    blurFrosted: { name: "blurFrosted", value: "blur(32px)", description: "Holds a blur value for a **frosted** effect when combined with a semi-transparent color." },
    deprecated: {
      frostedGlassStyle: { name: "frostedGlassStyle", value: "{\"WebkitBackdropFilter\":\"blur(32px)\",\"backdropFilter\":\"blur(32px)\"}", description: "since v4.0.0, will be removed with next major release. Use backdropFilter: blurFrosted instead" },
    },
  },
  border: {
    radius: {
      radiusXs: { name: "radiusXs", value: "2px", description: "Holds a **x-small** `border-radius`." },
      radiusSm: { name: "radiusSm", value: "4px", description: "Holds a **small** `border-radius`." },
      radiusMd: { name: "radiusMd", value: "6px", description: "Holds a **medium** `border-radius`." },
      radiusLg: { name: "radiusLg", value: "8px", description: "Holds a **large** `border-radius`." },
      radiusXl: { name: "radiusXl", value: "12px", description: "Holds a **x-large** `border-radius`." },
      radius2Xl: { name: "radius2Xl", value: "16px", description: "Holds a **2x-large** `border-radius`." },
      radius3Xl: { name: "radius3Xl", value: "24px", description: "Holds a **3x-large** `border-radius`." },
      radius4Xl: { name: "radius4Xl", value: "32px", description: "Holds a **4x-large** `border-radius`." },
      radiusFull: { name: "radiusFull", value: "calc(infinity * 1px)", description: "Holds a **fully** rounded `border-radius`." },
    },
    deprecated: {
      borderWidthThin: { name: "borderWidthThin", value: "1px", description: "since v4.0.0, will be removed with next major release. Use 1px instead." },
      borderWidth: { name: "borderWidth", value: "{\"base\":\"2px\",\"thin\":\"1px\"}", description: "since v4.0.0, will be removed with next major release. Use variables directly instead." },
      borderWidthBase: { name: "borderWidthBase", value: "2px", description: "since v4.0.0, will be removed with next major release. Use 2px instead." },
      borderRadiusSmall: { name: "borderRadiusSmall", value: "4px", description: "since v4.0.0, will be removed with next major release. Use radiusSm instead." },
      borderRadiusMedium: { name: "borderRadiusMedium", value: "6px", description: "since v4.0.0, will be removed with next major release. Use radiusMd instead." },
      border: { name: "border", value: "{\"radius\":{\"small\":\"4px\",\"medium\":\"6px\",\"large\":\"8px\"},\"width\":{\"base\":\"2px\",\"thin\":\"1px\"}}", description: "since v4.0.0, will be removed with next major release. Use variables directly instead." },
      borderRadius: { name: "borderRadius", value: "{\"small\":\"4px\",\"medium\":\"6px\",\"large\":\"8px\"}", description: "since v4.0.0, will be removed with next major release. Use variables directly instead." },
      borderRadiusLarge: { name: "borderRadiusLarge", value: "8px", description: "since v4.0.0, will be removed with next major release. Use radiusLg instead." },
    },
  },
  color: {
    lightDark: {
      colorCanvas: { name: "colorCanvas", value: "var(--_color-canvas, light-dark(#fff,hsl(225 66.7% 1.2%)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **canvas** color, typically used for surfaces." },
      colorSurface: { name: "colorSurface", value: "var(--_color-surface, light-dark(hsl(240 10% 95%),hsl(240 2% 10%)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **surface** color, typically used for surfaces." },
      colorFrosted: { name: "colorFrosted", value: "var(--_color-frosted, light-dark(hsl(240 5% 70% / 0.148),hsl(240 2% 43% / 0.228)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **frosted** color, typically used as a background in combination with `blur()`." },
      colorFrostedSoft: { name: "colorFrostedSoft", value: "var(--_color-frosted-soft, light-dark(hsl(234 9.8% 60% / 0.06),hsl(240 3.7% 26.5% / 0.154)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **frosted-soft** color, typically used as a background `:hover`." },
      colorFrostedStrong: { name: "colorFrostedStrong", value: "var(--_color-frosted-strong, light-dark(hsl(236 6.5% 42% / 0.236),hsl(240 1.5% 61.8% / 0.302)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **frosted-strong** color, typically used as a background in combination with `blur()`." },
      colorBackdrop: { name: "colorBackdrop", value: "var(--_color-backdrop, light-dark(hsl(240 5.3% 14.9% / 0.5),hsl(240 5.3% 14.9% / 0.5)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **backdrop** color, typically used for backdrops." },
      colorPrimary: { name: "colorPrimary", value: "var(--_color-primary, light-dark(hsl(225 66.7% 1.2%),hsl(225 100% 99%)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **primary** color, typically used for text." },
      colorContrastHigher: { name: "colorContrastHigher", value: "var(--_color-contrast-higher, light-dark(hsl(240 8.7% 9% / 0.8),hsl(240 12.5% 96.9% / 0.78)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **contrast-higher** color, typically used for text." },
      colorContrastHigh: { name: "colorContrastHigh", value: "var(--_color-contrast-high, light-dark(hsl(240 7.1% 11% / 0.7),hsl(240 12.5% 96.9% / 0.67)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **contrast-high** color, typically used for text." },
      colorContrastMedium: { name: "colorContrastMedium", value: "var(--_color-contrast-medium, light-dark(hsl(240 6.1% 7% / 0.6),hsl(240 12.5% 96.9% / 0.56)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **contrast-medium** color, typically used for text." },
      colorContrastLow: { name: "colorContrastLow", value: "var(--_color-contrast-low, light-dark(hsl(240 5.3% 14.9% / 0.5),hsl(240 12.5% 96.9% / 0.45)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **contrast-low** color, intended only for decorative elements." },
      colorContrastLower: { name: "colorContrastLower", value: "var(--_color-contrast-lower, light-dark(hsl(234 6% 32.9% / 0.324),hsl(240 1.5% 61.8% / 0.302)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **contrast-lower** color, intended only for decorative elements." },
      colorInfo: { name: "colorInfo", value: "var(--_color-info, light-dark(hsl(228 83.2% 51%),hsl(210 100% 54.5%)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **info** color, typically used for text." },
      colorInfoMedium: { name: "colorInfoMedium", value: "var(--_color-info-medium, light-dark(hsl(228 83.2% 51% / 0.6),hsl(210 100% 54.5% / 0.6)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **info-medium** color, typically used for text or border." },
      colorInfoLow: { name: "colorInfoLow", value: "var(--_color-info-low, light-dark(hsl(228 83.2% 51% / 0.18),hsl(210 100% 54.5% / 0.18)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **info-low** color, typically used for text or border." },
      colorInfoFrosted: { name: "colorInfoFrosted", value: "var(--_color-info-frosted, light-dark(hsl(211 100% 90% / 0.55),hsl(210 79% 20% / 0.66)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **info-frosted** color, typically used as background with `.backdrop-blur-frosted`." },
      colorInfoFrostedSoft: { name: "colorInfoFrostedSoft", value: "var(--_color-info-frosted-soft, light-dark(hsl(211 80% 95% / 0.55),hsl(210 59% 15% / 0.66)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **info-frosted-soft** color, typically used as background `:hover`." },
      colorSuccess: { name: "colorSuccess", value: "var(--_color-success, light-dark(hsl(115 77.5% 27.8%),hsl(157 84.9% 41.6%)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **success** color, typically used for text." },
      colorSuccessMedium: { name: "colorSuccessMedium", value: "var(--_color-success-medium, light-dark(hsl(115 77.5% 27.8% / 0.6),hsl(157 84.9% 41.6% / 0.6)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **success-medium** color, typically used for text or border." },
      colorSuccessLow: { name: "colorSuccessLow", value: "var(--_color-success-low, light-dark(hsl(115 77.5% 27.8% / 0.18),hsl(157 84.9% 41.6% / 0.18)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **success-low** color, typically used for text or border." },
      colorSuccessFrosted: { name: "colorSuccessFrosted", value: "var(--_color-success-frosted, light-dark(hsl(109 100% 90% / 0.55),hsl(157 79% 20% / 0.66)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **success-frosted** color, typically used as background with `.backdrop-blur-frosted`." },
      colorSuccessFrostedSoft: { name: "colorSuccessFrostedSoft", value: "var(--_color-success-frosted-soft, light-dark(hsl(109 80% 95% / 0.55),hsl(157 59% 15% / 0.66)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **success-frosted-soft** color, typically used as background `:hover`." },
      colorWarning: { name: "colorWarning", value: "var(--_color-warning, light-dark(hsl(28 97.7% 34.1%),hsl(28 90.2% 56.1%)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **warning** color, typically used for text." },
      colorWarningMedium: { name: "colorWarningMedium", value: "var(--_color-warning-medium, light-dark(hsl(28 97.7% 34.1% / 0.6),hsl(28 90.2% 56.1% / 0.6)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **warning-medium** color, typically used for text or border." },
      colorWarningLow: { name: "colorWarningLow", value: "var(--_color-warning-low, light-dark(hsl(28 97.7% 34.1% / 0.18),hsl(28 90.2% 56.1% / 0.18)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **warning-low** color, typically used for text or border." },
      colorWarningFrosted: { name: "colorWarningFrosted", value: "var(--_color-warning-frosted, light-dark(hsl(40 100% 90% / 0.55),hsl(52 79% 20% / 0.66)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **warning-frosted** color, typically used as background with `.backdrop-blur-frosted`." },
      colorWarningFrostedSoft: { name: "colorWarningFrostedSoft", value: "var(--_color-warning-frosted-soft, light-dark(hsl(40 80% 95% / 0.55),hsl(52 59% 15% / 0.66)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **warning-frosted-soft** color, typically used as background `:hover`." },
      colorError: { name: "colorError", value: "var(--_color-error, light-dark(hsl(357 78% 41%),hsl(0 96.9% 62%)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **error** color, typically used for text." },
      colorErrorMedium: { name: "colorErrorMedium", value: "var(--_color-error-medium, light-dark(hsl(357 78% 41% / 0.6),hsl(0 96.9% 62% / 0.6)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **error-medium** color, typically used for text or border." },
      colorErrorLow: { name: "colorErrorLow", value: "var(--_color-error-low, light-dark(hsl(357 78% 41% / 0.18),hsl(0 96.9% 62% / 0.18)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **error-low** color, typically used for text or border." },
      colorErrorFrosted: { name: "colorErrorFrosted", value: "var(--_color-error-frosted, light-dark(hsl(0 100% 90% / 0.55),hsl(0 79% 20% / 0.66)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **error-frosted** color, typically used as background with `.backdrop-blur-frosted`." },
      colorErrorFrostedSoft: { name: "colorErrorFrostedSoft", value: "var(--_color-error-frosted-soft, light-dark(hsl(0 80% 95% / 0.55),hsl(0 59% 15% / 0.66)))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **error-frosted-soft** color, typically used as background `:hover`." },
      colorFocus: { name: "colorFocus", value: "var(--_color-focus, light-dark(#1A44EA,#1A44EA))", description: "Holds the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/color_value/light-dark) **focus** color, typically used as the outline for `:focus-visible` states." },
    },
    deprecated: {
      theme: { name: "theme", value: "{\"light\":{\"primary\":\"hsl(225 66.7% 1.2%)\",\"background\":{\"base\":\"#fff\",\"surface\":\"hsl(240 10% 95%)\",\"shading\":\"hsl(240 5.3% 14.9% / 0.5)\",\"frosted\":\"hsl(240 5% 70% / 0.148)\"},\"contrast\":{\"low\":\"hsl(240 5.3% 14.9% / 0.5)\",\"medium\":\"hsl(240 6.1% 7% / 0.6)\",\"high\":\"hsl(240 7.1% 11% / 0.7)\"},\"notification\":{\"success\":\"hsl(115 77.5% 27.8%)\",\"successSoft\":\"hsl(109 100% 90% / 0.55)\",\"warning\":\"hsl(28 97.7% 34.1%)\",\"warningSoft\":\"hsl(40 100% 90% / 0.55)\",\"error\":\"hsl(357 78% 41%)\",\"errorSoft\":\"hsl(0 100% 90% / 0.55)\",\"info\":\"hsl(228 83.2% 51%)\",\"infoSoft\":\"hsl(211 100% 90% / 0.55)\"},\"state\":{\"hover\":\"hsl(240 5% 70% / 0.148)\",\"active\":\"hsl(240 5% 70% / 0.148)\",\"focus\":\"#1A44EA\",\"disabled\":\"hsla(233,6.6%,23.9%,0.412)\"}},\"dark\":{\"primary\":\"hsl(225 100% 99%)\",\"background\":{\"base\":\"hsl(225 66.7% 1.2%)\",\"surface\":\"hsl(240 2% 10%)\",\"shading\":\"hsl(240 5.3% 14.9% / 0.5)\",\"frosted\":\"hsl(240 2% 43% / 0.228)\"},\"contrast\":{\"low\":\"hsl(240 12.5% 96.9% / 0.45)\",\"medium\":\"hsl(240 12.5% 96.9% / 0.56)\",\"high\":\"hsl(240 12.5% 96.9% / 0.67)\"},\"notification\":{\"success\":\"hsl(157 84.9% 41.6%)\",\"successSoft\":\"hsl(157 79% 20% / 0.66)\",\"warning\":\"hsl(28 90.2% 56.1%)\",\"warningSoft\":\"hsl(52 79% 20% / 0.66)\",\"error\":\"hsl(0 96.9% 62%)\",\"errorSoft\":\"hsl(0 79% 20% / 0.66)\",\"info\":\"hsl(210 100% 54.5%)\",\"infoSoft\":\"hsl(210 79% 20% / 0.66)\"},\"state\":{\"hover\":\"hsl(240 2% 43% / 0.228)\",\"active\":\"hsl(240 2% 43% / 0.228)\",\"focus\":\"#1A44EA\",\"disabled\":\"hsla(240,1.5%,61.8%,0.302)\"}}}", description: "since v4.0.0, will be removed with next major release. Use individual variables instead." },
      themeDark: { name: "themeDark", value: "{\"primary\":\"hsl(225 100% 99%)\",\"background\":{\"base\":\"hsl(225 66.7% 1.2%)\",\"surface\":\"hsl(240 2% 10%)\",\"shading\":\"hsl(240 5.3% 14.9% / 0.5)\",\"frosted\":\"hsl(240 2% 43% / 0.228)\"},\"contrast\":{\"low\":\"hsl(240 12.5% 96.9% / 0.45)\",\"medium\":\"hsl(240 12.5% 96.9% / 0.56)\",\"high\":\"hsl(240 12.5% 96.9% / 0.67)\"},\"notification\":{\"success\":\"hsl(157 84.9% 41.6%)\",\"successSoft\":\"hsl(157 79% 20% / 0.66)\",\"warning\":\"hsl(28 90.2% 56.1%)\",\"warningSoft\":\"hsl(52 79% 20% / 0.66)\",\"error\":\"hsl(0 96.9% 62%)\",\"errorSoft\":\"hsl(0 79% 20% / 0.66)\",\"info\":\"hsl(210 100% 54.5%)\",\"infoSoft\":\"hsl(210 79% 20% / 0.66)\"},\"state\":{\"hover\":\"hsl(240 2% 43% / 0.228)\",\"active\":\"hsl(240 2% 43% / 0.228)\",\"focus\":\"#1A44EA\",\"disabled\":\"hsla(240,1.5%,61.8%,0.302)\"}}", description: "since v4.0.0, will be removed with next major release. Use individual variables instead." },
      themeDarkBackgroundBase: { name: "themeDarkBackgroundBase", value: "hsl(225 66.7% 1.2%)", description: "since v4.0.0, will be removed with next major release. Use colorCanvasDark instead." },
      themeDarkBackgroundFrosted: { name: "themeDarkBackgroundFrosted", value: "hsl(240 2% 43% / 0.228)", description: "since v4.0.0, will be removed with next major release. Use colorFrostedDark instead." },
      themeDarkBackgroundShading: { name: "themeDarkBackgroundShading", value: "hsl(240 5.3% 14.9% / 0.5)", description: "since v4.0.0, will be removed with next major release. Use colorBackdropDark instead." },
      themeDarkBackgroundSurface: { name: "themeDarkBackgroundSurface", value: "hsl(240 2% 10%)", description: "since v4.0.0, will be removed with next major release. Use colorSurfaceDark instead." },
      themeDarkContrastHigh: { name: "themeDarkContrastHigh", value: "hsl(240 12.5% 96.9% / 0.67)", description: "since v4.0.0, will be removed with next major release. Use colorContrastHighDark instead." },
      themeDarkContrastLow: { name: "themeDarkContrastLow", value: "hsl(240 12.5% 96.9% / 0.45)", description: "since v4.0.0, will be removed with next major release. Use colorContrastLowDark instead." },
      themeDarkContrastMedium: { name: "themeDarkContrastMedium", value: "hsl(240 12.5% 96.9% / 0.56)", description: "since v4.0.0, will be removed with next major release. Use colorContrastMediumDark instead." },
      themeDarkNotificationError: { name: "themeDarkNotificationError", value: "hsl(0 96.9% 62%)", description: "since v4.0.0, will be removed with next major release. Use colorErrorDark instead." },
      themeDarkNotificationErrorSoft: { name: "themeDarkNotificationErrorSoft", value: "hsl(0 79% 20% / 0.66)", description: "since v4.0.0, will be removed with next major release. Use colorErrorFrostedDark instead." },
      themeDarkNotificationInfo: { name: "themeDarkNotificationInfo", value: "hsl(210 100% 54.5%)", description: "since v4.0.0, will be removed with next major release. Use colorInfoDark instead." },
      themeDarkNotificationInfoSoft: { name: "themeDarkNotificationInfoSoft", value: "hsl(210 79% 20% / 0.66)", description: "since v4.0.0, will be removed with next major release. Use colorInfoFrostedDark instead." },
      themeDarkNotificationSuccess: { name: "themeDarkNotificationSuccess", value: "hsl(157 84.9% 41.6%)", description: "since v4.0.0, will be removed with next major release. Use colorSuccessDark instead." },
      themeDarkNotificationSuccessSoft: { name: "themeDarkNotificationSuccessSoft", value: "hsl(157 79% 20% / 0.66)", description: "since v4.0.0, will be removed with next major release. Use colorSuccessFrostedDark instead." },
      themeDarkNotificationWarning: { name: "themeDarkNotificationWarning", value: "hsl(28 90.2% 56.1%)", description: "since v4.0.0, will be removed with next major release. Use colorWarningDark instead." },
      themeDarkNotificationWarningSoft: { name: "themeDarkNotificationWarningSoft", value: "hsl(52 79% 20% / 0.66)", description: "since v4.0.0, will be removed with next major release. Use colorWarningFrostedDark instead." },
      themeDarkPrimary: { name: "themeDarkPrimary", value: "hsl(225 100% 99%)", description: "since v4.0.0, will be removed with next major release. Use colorPrimaryDark instead." },
      themeDarkStateActive: { name: "themeDarkStateActive", value: "hsl(240 2% 43% / 0.228)", description: "since v4.0.0, will be removed with next major release. Use colorFrostedDark instead." },
      themeDarkStateDisabled: { name: "themeDarkStateDisabled", value: "hsla(240,1.5%,61.8%,0.302)", description: "since v4.0.0, will be removed with next major release." },
      themeDarkStateFocus: { name: "themeDarkStateFocus", value: "#1A44EA", description: "since v4.0.0, will be removed with next major release. Use colorFocusDark instead." },
      themeDarkStateHover: { name: "themeDarkStateHover", value: "hsl(240 2% 43% / 0.228)", description: "since v4.0.0, will be removed with next major release. Use colorFrostedDark instead." },
      themeLight: { name: "themeLight", value: "{\"primary\":\"hsl(225 66.7% 1.2%)\",\"background\":{\"base\":\"#fff\",\"surface\":\"hsl(240 10% 95%)\",\"shading\":\"hsl(240 5.3% 14.9% / 0.5)\",\"frosted\":\"hsl(240 5% 70% / 0.148)\"},\"contrast\":{\"low\":\"hsl(240 5.3% 14.9% / 0.5)\",\"medium\":\"hsl(240 6.1% 7% / 0.6)\",\"high\":\"hsl(240 7.1% 11% / 0.7)\"},\"notification\":{\"success\":\"hsl(115 77.5% 27.8%)\",\"successSoft\":\"hsl(109 100% 90% / 0.55)\",\"warning\":\"hsl(28 97.7% 34.1%)\",\"warningSoft\":\"hsl(40 100% 90% / 0.55)\",\"error\":\"hsl(357 78% 41%)\",\"errorSoft\":\"hsl(0 100% 90% / 0.55)\",\"info\":\"hsl(228 83.2% 51%)\",\"infoSoft\":\"hsl(211 100% 90% / 0.55)\"},\"state\":{\"hover\":\"hsl(240 5% 70% / 0.148)\",\"active\":\"hsl(240 5% 70% / 0.148)\",\"focus\":\"#1A44EA\",\"disabled\":\"hsla(233,6.6%,23.9%,0.412)\"}}", description: "since v4.0.0, will be removed with next major release. Use individual variables instead." },
      themeLightBackgroundBase: { name: "themeLightBackgroundBase", value: "#fff", description: "since v4.0.0, will be removed with next major release. Use colorCanvasLight instead." },
      themeLightBackgroundFrosted: { name: "themeLightBackgroundFrosted", value: "hsl(240 5% 70% / 0.148)", description: "since v4.0.0, will be removed with next major release. Use colorFrostedLight instead." },
      themeLightBackgroundShading: { name: "themeLightBackgroundShading", value: "hsl(240 5.3% 14.9% / 0.5)", description: "since v4.0.0, will be removed with next major release. Use colorBackdropLight instead." },
      themeLightBackgroundSurface: { name: "themeLightBackgroundSurface", value: "hsl(240 10% 95%)", description: "since v4.0.0, will be removed with next major release. Use colorSurfaceLight instead." },
      themeLightContrastHigh: { name: "themeLightContrastHigh", value: "hsl(240 7.1% 11% / 0.7)", description: "since v4.0.0, will be removed with next major release. Use colorContrastHighLight instead." },
      themeLightContrastLow: { name: "themeLightContrastLow", value: "hsl(240 5.3% 14.9% / 0.5)", description: "since v4.0.0, will be removed with next major release. Use colorContrastLowLight instead." },
      themeLightContrastMedium: { name: "themeLightContrastMedium", value: "hsl(240 6.1% 7% / 0.6)", description: "since v4.0.0, will be removed with next major release. Use colorContrastMediumLight instead." },
      themeLightNotificationError: { name: "themeLightNotificationError", value: "hsl(357 78% 41%)", description: "since v4.0.0, will be removed with next major release. Use colorErrorLight instead." },
      themeLightNotificationErrorSoft: { name: "themeLightNotificationErrorSoft", value: "hsl(0 100% 90% / 0.55)", description: "since v4.0.0, will be removed with next major release. Use colorErrorFrostedLight instead." },
      themeLightNotificationInfo: { name: "themeLightNotificationInfo", value: "hsl(228 83.2% 51%)", description: "since v4.0.0, will be removed with next major release. Use colorInfoLight instead." },
      themeLightNotificationInfoSoft: { name: "themeLightNotificationInfoSoft", value: "hsl(211 100% 90% / 0.55)", description: "since v4.0.0, will be removed with next major release. Use colorInfoFrostedLight instead." },
      themeLightNotificationSuccess: { name: "themeLightNotificationSuccess", value: "hsl(115 77.5% 27.8%)", description: "since v4.0.0, will be removed with next major release. Use colorSuccessLight instead." },
      themeLightNotificationSuccessSoft: { name: "themeLightNotificationSuccessSoft", value: "hsl(109 100% 90% / 0.55)", description: "since v4.0.0, will be removed with next major release. Use colorSuccessFrostedLight instead." },
      themeLightNotificationWarning: { name: "themeLightNotificationWarning", value: "hsl(28 97.7% 34.1%)", description: "since v4.0.0, will be removed with next major release. Use colorWarningLight instead." },
      themeLightNotificationWarningSoft: { name: "themeLightNotificationWarningSoft", value: "hsl(40 100% 90% / 0.55)", description: "since v4.0.0, will be removed with next major release. Use colorWarningFrostedLight instead." },
      themeLightPrimary: { name: "themeLightPrimary", value: "hsl(225 66.7% 1.2%)", description: "since v4.0.0, will be removed with next major release. Use colorPrimaryLight instead." },
      themeLightStateActive: { name: "themeLightStateActive", value: "hsl(240 5% 70% / 0.148)", description: "since v4.0.0, will be removed with next major release. Use colorFrostedLight instead." },
      themeLightStateDisabled: { name: "themeLightStateDisabled", value: "hsla(233,6.6%,23.9%,0.412)", description: "since v4.0.0, will be removed with next major release." },
      themeLightStateFocus: { name: "themeLightStateFocus", value: "#1A44EA", description: "since v4.0.0, will be removed with next major release. Use colorFocusLight instead." },
      themeLightStateHover: { name: "themeLightStateHover", value: "hsl(240 5% 70% / 0.148)", description: "since v4.0.0, will be removed with next major release. Use colorFrostedLight instead." },
    },
  },
  focus: {
    getFocusVisibleStyle: { name: "getFocusVisibleStyle({ offset: string = '2px' })", description: "Applies a **focus-visible** outline style with configurable `offset`." },
    deprecated: {
      getFocusStyle: { name: "getFocusStyle", description: "since v4.0.0, will be removed with next major release. Use getFocusVisibleStyle instead." },
    },
  },
  font: {
    family: {
      fontPorscheNext: { name: "fontPorscheNext", value: "'Porsche Next','Arial Narrow',Arial,'Heiti SC',SimHei,sans-serif", description: "Holds the **Porsche Next** font family along with fallback fonts." },
    },
    lineHeight: {
      leadingNormal: { name: "leadingNormal", value: "calc(6px + 2.125ex)", description: "Holds a dynamic default line height specifically optimized for the Porsche Next typeface." },
    },
    size: {
      typescale2Xs: { name: "typescale2Xs", value: ".75rem", description: "Holds the **2x-small** font size optimized for the Porsche Next typeface." },
      typescaleXs: { name: "typescaleXs", value: ".875rem", description: "Holds the **x-small** font size optimized for the Porsche Next typeface." },
      typescaleSm: { name: "typescaleSm", value: "1rem", description: "Holds the **small** font size optimized for the Porsche Next typeface." },
      typescaleMd: { name: "typescaleMd", value: "clamp(1.13rem, 0.21vw + 1.08rem, 1.33rem)", description: "Holds the **medium** font size optimized for the Porsche Next typeface." },
      typescaleLg: { name: "typescaleLg", value: "clamp(1.27rem, 0.51vw + 1.16rem, 1.78rem)", description: "Holds the **large** font size optimized for the Porsche Next typeface." },
      typescaleXl: { name: "typescaleXl", value: "clamp(1.42rem, 0.94vw + 1.23rem, 2.37rem)", description: "Holds the **x-large** font size optimized for the Porsche Next typeface." },
      typescale2Xl: { name: "typescale2Xl", value: "clamp(1.6rem, 1.56vw + 1.29rem, 3.16rem)", description: "Holds the **2x-large** font size optimized for the Porsche Next typeface." },
      typescale3Xl: { name: "typescale3Xl", value: "clamp(1.8rem, 2.41vw + 1.32rem, 4.21rem)", description: "Holds the **3x-large** font size optimized for the Porsche Next typeface." },
      typescale4Xl: { name: "typescale4Xl", value: "clamp(2.03rem, 3.58vw + 1.31rem, 5.61rem)", description: "Holds the **4x-large** font size optimized for the Porsche Next typeface." },
      typescale5Xl: { name: "typescale5Xl", value: "clamp(2.28rem, 5.2vw + 1.24rem, 7.48rem)", description: "Holds the **5x-large** font size optimized for the Porsche Next typeface." },
    },
    weight: {
      fontWeightNormal: { name: "fontWeightNormal", value: 400, description: "Holds the **normal** font weight optimized for the Porsche Next typeface." },
      fontWeightSemibold: { name: "fontWeightSemibold", value: 600, description: "Holds the **semibold** font weight optimized for the Porsche Next typeface." },
      fontWeightBold: { name: "fontWeightBold", value: 700, description: "Holds the **bold** font weight optimized for the Porsche Next typeface." },
    },
    deprecated: {
      fontFamily: { name: "fontFamily", value: "'Porsche Next','Arial Narrow',Arial,'Heiti SC',SimHei,sans-serif", description: "since v4.0.0, will be removed with next major release. Use fontPorscheNext instead." },
      fontStyle: { name: "fontStyle", value: "{\"normal\":\"normal\",\"italic\":\"italic\"}", description: "since v4.0.0, will be removed with next major release. Use 'normal' | 'italic' instead." },
      fontStyleItalic: { name: "fontStyleItalic", value: "italic", description: "since v4.0.0, will be removed with next major release. Use 'italic' instead." },
      fontStyleNormal: { name: "fontStyleNormal", value: "normal", description: "since v4.0.0, will be removed with next major release. Use 'normal' instead." },
      fontVariant: { name: "fontVariant", value: "normal", description: "since v4.0.0, will be removed with next major release. Use 'normal' instead." },
      fontWeight: { name: "fontWeight", value: "{\"regular\":400,\"semiBold\":600,\"bold\":700}", description: "since v4.0.0, will be removed with next major release. Use variables directly instead." },
      fontSizeTextXXSmall: { name: "fontSizeTextXXSmall", value: ".75rem", description: "since v4.0.0, will be removed with next major release. Use typescale2Xs instead." },
      fontSizeTextXSmall: { name: "fontSizeTextXSmall", value: ".875rem", description: "since v4.0.0, will be removed with next major release. Use typescaleXs instead." },
      fontSizeHeadingSmall: { name: "fontSizeHeadingSmall", value: "1rem", description: "since v4.0.0, will be removed with next major release. Use typescaleSm instead." },
      fontSizeTextSmall: { name: "fontSizeTextSmall", value: "1rem", description: "since v4.0.0, will be removed with next major release. Use typescaleSm instead." },
      fontSize: { name: "fontSize", value: "{\"text\":{\"xxSmall\":\".75rem\",\"xSmall\":\".875rem\",\"small\":\"1rem\",\"medium\":\"clamp(1.13rem, 0.21vw + 1.08rem, 1.33rem)\",\"large\":\"clamp(1.27rem, 0.51vw + 1.16rem, 1.78rem)\",\"xLarge\":\"clamp(1.42rem, 0.94vw + 1.23rem, 2.37rem)\"},\"heading\":{\"small\":\"1rem\",\"medium\":\"clamp(1.13rem, 0.21vw + 1.08rem, 1.33rem)\",\"large\":\"clamp(1.27rem, 0.51vw + 1.16rem, 1.78rem)\",\"xLarge\":\"clamp(1.42rem, 0.94vw + 1.23rem, 2.37rem)\",\"xxLarge\":\"clamp(1.6rem, 1.56vw + 1.29rem, 3.16rem)\"},\"display\":{\"small\":\"clamp(1.8rem, 2.41vw + 1.32rem, 4.21rem)\",\"medium\":\"clamp(2.03rem, 3.58vw + 1.31rem, 5.61rem)\",\"large\":\"clamp(2.28rem, 5.2vw + 1.24rem, 7.48rem)\"}}", description: "since v4.0.0, will be removed with next major release. Use typescale variables instead." },
      fontSizeHeading: { name: "fontSizeHeading", value: "{\"small\":\"1rem\",\"medium\":\"clamp(1.13rem, 0.21vw + 1.08rem, 1.33rem)\",\"large\":\"clamp(1.27rem, 0.51vw + 1.16rem, 1.78rem)\",\"xLarge\":\"clamp(1.42rem, 0.94vw + 1.23rem, 2.37rem)\",\"xxLarge\":\"clamp(1.6rem, 1.56vw + 1.29rem, 3.16rem)\"}", description: "since v4.0.0, will be removed with next major release. Use typescale variables instead." },
      fontSizeHeadingMedium: { name: "fontSizeHeadingMedium", value: "clamp(1.13rem, 0.21vw + 1.08rem, 1.33rem)", description: "since v4.0.0, will be removed with next major release. Use typescaleMd instead." },
      fontSizeText: { name: "fontSizeText", value: "{\"xxSmall\":\".75rem\",\"xSmall\":\".875rem\",\"small\":\"1rem\",\"medium\":\"clamp(1.13rem, 0.21vw + 1.08rem, 1.33rem)\",\"large\":\"clamp(1.27rem, 0.51vw + 1.16rem, 1.78rem)\",\"xLarge\":\"clamp(1.42rem, 0.94vw + 1.23rem, 2.37rem)\"}", description: "since v4.0.0, will be removed with next major release. Use typescale variables instead." },
      fontSizeTextMedium: { name: "fontSizeTextMedium", value: "clamp(1.13rem, 0.21vw + 1.08rem, 1.33rem)", description: "since v4.0.0, will be removed with next major release. Use typescaleMd instead." },
      fontSizeHeadingLarge: { name: "fontSizeHeadingLarge", value: "clamp(1.27rem, 0.51vw + 1.16rem, 1.78rem)", description: "since v4.0.0, will be removed with next major release. Use typescaleLg instead." },
      fontSizeTextLarge: { name: "fontSizeTextLarge", value: "clamp(1.27rem, 0.51vw + 1.16rem, 1.78rem)", description: "since v4.0.0, will be removed with next major release. Use typescaleLg instead." },
      fontSizeHeadingXLarge: { name: "fontSizeHeadingXLarge", value: "clamp(1.42rem, 0.94vw + 1.23rem, 2.37rem)", description: "since v4.0.0, will be removed with next major release. Use typescaleXl instead." },
      fontSizeTextXLarge: { name: "fontSizeTextXLarge", value: "clamp(1.42rem, 0.94vw + 1.23rem, 2.37rem)", description: "since v4.0.0, will be removed with next major release. Use typescaleXl instead." },
      fontSizeHeadingXXLarge: { name: "fontSizeHeadingXXLarge", value: "clamp(1.6rem, 1.56vw + 1.29rem, 3.16rem)", description: "since v4.0.0, will be removed with next major release. Use typescale2Xl instead." },
      fontSizeDisplay: { name: "fontSizeDisplay", value: "{\"small\":\"clamp(1.8rem, 2.41vw + 1.32rem, 4.21rem)\",\"medium\":\"clamp(2.03rem, 3.58vw + 1.31rem, 5.61rem)\",\"large\":\"clamp(2.28rem, 5.2vw + 1.24rem, 7.48rem)\"}", description: "since v4.0.0, will be removed with next major release. Use variables directly instead." },
      fontLineHeight: { name: "fontLineHeight", value: "calc(6px + 2.125ex)", description: "since v4.0.0, will be removed with next major release. Use leadingNormal instead" },
      fontWeightRegular: { name: "fontWeightRegular", value: 400, description: "since v4.0.0, will be removed with next major release. Use fontWeightNormal instead." },
      fontWeightSemiBold: { name: "fontWeightSemiBold", value: 600, description: "since v4.0.0, will be removed with next major release. Use fontWeightSemibold instead." },
    },
  },
  gradient: {
    gradientStopsFadeDark: { name: "gradientStopsFadeDark", value: "hsla(0,0%,0%,.8) 0%,hsla(0,0%,0%,.8) 8.1%,hsla(0,0%,0%,.8) 15.5%,hsla(0,0%,0%,.8) 22.5%,hsla(0,0%,0%,.78) 29%,hsla(0,0%,0%,.73) 35.3%,hsla(0,0%,0%,.67) 41.2%,hsla(0,0%,0%,.6) 47.1%,hsla(0,0%,0%,.52) 52.9%,hsla(0,0%,0%,.44) 58.8%,hsla(0,0%,0%,.33) 64.7%,hsla(0,0%,0%,.22) 71%,hsla(0,0%,0%,.12) 77.5%,hsla(0,0%,0%,.05) 84.5%,hsla(0,0%,0%,.011) 91.9%,hsla(0,0%,0%,0) 100%", description: "Holds color stops for a faded gradient, used as `background-image`." },
    deprecated: {
      gradientToBottomStyle: { name: "gradientToBottomStyle", value: "{\"background\":\"linear-gradient(to bottom, hsla(0,0%,0%,.8) 0%,hsla(0,0%,0%,.8) 8.1%,hsla(0,0%,0%,.8) 15.5%,hsla(0,0%,0%,.8) 22.5%,hsla(0,0%,0%,.78) 29%,hsla(0,0%,0%,.73) 35.3%,hsla(0,0%,0%,.67) 41.2%,hsla(0,0%,0%,.6) 47.1%,hsla(0,0%,0%,.52) 52.9%,hsla(0,0%,0%,.44) 58.8%,hsla(0,0%,0%,.33) 64.7%,hsla(0,0%,0%,.22) 71%,hsla(0,0%,0%,.12) 77.5%,hsla(0,0%,0%,.05) 84.5%,hsla(0,0%,0%,.011) 91.9%,hsla(0,0%,0%,0) 100%);\"}", description: "since v4.0.0, will be removed with next major release. Use background: `linear-gradient(to bottom, ${gradientStopsFadeDark});` instead" },
      gradientToLeftStyle: { name: "gradientToLeftStyle", value: "{\"background\":\"linear-gradient(to left, hsla(0,0%,0%,.8) 0%,hsla(0,0%,0%,.8) 8.1%,hsla(0,0%,0%,.8) 15.5%,hsla(0,0%,0%,.8) 22.5%,hsla(0,0%,0%,.78) 29%,hsla(0,0%,0%,.73) 35.3%,hsla(0,0%,0%,.67) 41.2%,hsla(0,0%,0%,.6) 47.1%,hsla(0,0%,0%,.52) 52.9%,hsla(0,0%,0%,.44) 58.8%,hsla(0,0%,0%,.33) 64.7%,hsla(0,0%,0%,.22) 71%,hsla(0,0%,0%,.12) 77.5%,hsla(0,0%,0%,.05) 84.5%,hsla(0,0%,0%,.011) 91.9%,hsla(0,0%,0%,0) 100%);\"}", description: "since v4.0.0, will be removed with next major release. Use background: `linear-gradient(to left, ${gradientStopsFadeDark});` instead" },
      gradientToRightStyle: { name: "gradientToRightStyle", value: "{\"background\":\"linear-gradient(to right, hsla(0,0%,0%,.8) 0%,hsla(0,0%,0%,.8) 8.1%,hsla(0,0%,0%,.8) 15.5%,hsla(0,0%,0%,.8) 22.5%,hsla(0,0%,0%,.78) 29%,hsla(0,0%,0%,.73) 35.3%,hsla(0,0%,0%,.67) 41.2%,hsla(0,0%,0%,.6) 47.1%,hsla(0,0%,0%,.52) 52.9%,hsla(0,0%,0%,.44) 58.8%,hsla(0,0%,0%,.33) 64.7%,hsla(0,0%,0%,.22) 71%,hsla(0,0%,0%,.12) 77.5%,hsla(0,0%,0%,.05) 84.5%,hsla(0,0%,0%,.011) 91.9%,hsla(0,0%,0%,0) 100%);\"}", description: "since v4.0.0, will be removed with next major release. background: `linear-gradient(to right, ${gradientStopsFadeDark});` instead" },
      gradientToTopStyle: { name: "gradientToTopStyle", value: "{\"background\":\"linear-gradient(to top, hsla(0,0%,0%,.8) 0%,hsla(0,0%,0%,.8) 8.1%,hsla(0,0%,0%,.8) 15.5%,hsla(0,0%,0%,.8) 22.5%,hsla(0,0%,0%,.78) 29%,hsla(0,0%,0%,.73) 35.3%,hsla(0,0%,0%,.67) 41.2%,hsla(0,0%,0%,.6) 47.1%,hsla(0,0%,0%,.52) 52.9%,hsla(0,0%,0%,.44) 58.8%,hsla(0,0%,0%,.33) 64.7%,hsla(0,0%,0%,.22) 71%,hsla(0,0%,0%,.12) 77.5%,hsla(0,0%,0%,.05) 84.5%,hsla(0,0%,0%,.011) 91.9%,hsla(0,0%,0%,0) 100%);\"}", description: "since v4.0.0, will be removed with next major release. background: `linear-gradient(to top, ${gradientStopsFadeDark});` instead" },
    },
  },
  grid: {
    gridBasic: { name: "gridBasic", value: "{\"columnStart\":\"basic-start\",\"columnEnd\":\"basic-end\",\"spanOneHalf\":\"var(--pds-grid-basic-span-one-half)\",\"spanOneThird\":\"var(--pds-grid-basic-span-one-third)\",\"spanTwoThirds\":\"var(--pds-grid-basic-span-two-thirds)\"}", description: "Object containing all `basic` grid styles." },
    gridBasicColumnEnd: { name: "gridBasicColumnEnd", value: "basic-end", description: "Holds the **end** position of the `basic` area within the Porsche Grid." },
    gridBasicColumnStart: { name: "gridBasicColumnStart", value: "basic-start", description: "Holds the **start** position of the `basic` area within the Porsche Grid." },
    gridBasicSpanOneHalf: { name: "gridBasicSpanOneHalf", value: "var(--pds-grid-basic-span-one-half)", description: "Holds a **half** span within the `basic` area of the Porsche Grid." },
    gridBasicSpanOneThird: { name: "gridBasicSpanOneThird", value: "var(--pds-grid-basic-span-one-third)", description: "Holds a **one third** span within the `basic` area of the Porsche Grid." },
    gridBasicSpanTwoThirds: { name: "gridBasicSpanTwoThirds", value: "var(--pds-grid-basic-span-two-thirds)", description: "Holds a **two thirds** span within the `basic` area of the Porsche Grid." },
    gridExtended: { name: "gridExtended", value: "{\"columnStart\":\"extended-start\",\"columnEnd\":\"extended-end\",\"spanOneHalf\":\"var(--pds-grid-extended-span-one-half)\"}", description: "Object containing all `extended` grid styles." },
    gridExtendedColumnEnd: { name: "gridExtendedColumnEnd", value: "extended-end", description: "Holds the **end** position of the `extended` area within the Porsche Grid." },
    gridExtendedColumnStart: { name: "gridExtendedColumnStart", value: "extended-start", description: "Holds the **start** position of the `extended` area within the Porsche Grid." },
    gridExtendedSpanOneHalf: { name: "gridExtendedSpanOneHalf", value: "var(--pds-grid-extended-span-one-half)", description: "Holds a **half** span within the `extended` area of the Porsche Grid." },
    gridFull: { name: "gridFull", value: "{\"columnStart\":\"full-start\",\"columnEnd\":\"full-end\"}", description: "Object containing all `full` grid styles." },
    gridFullColumnEnd: { name: "gridFullColumnEnd", value: "full-end", description: "Holds the **end** position of the `full` area within the Porsche Grid." },
    gridFullColumnStart: { name: "gridFullColumnStart", value: "full-start", description: "Holds the **start** position of the `full` area within the Porsche Grid." },
    gridNarrow: { name: "gridNarrow", value: "{\"columnStart\":\"narrow-start\",\"columnEnd\":\"narrow-end\",\"spanOneHalf\":\"var(--pds-grid-narrow-span-one-half)\"}", description: "Object containing all `narrow` grid styles." },
    gridNarrowColumnEnd: { name: "gridNarrowColumnEnd", value: "narrow-end", description: "Holds the **end** position of the `narrow` area within the Porsche Grid." },
    gridNarrowColumnStart: { name: "gridNarrowColumnStart", value: "narrow-start", description: "Holds the **start** position of the `narrow` area within the Porsche Grid." },
    gridNarrowSpanOneHalf: { name: "gridNarrowSpanOneHalf", value: "var(--pds-grid-narrow-span-one-half)", description: "Holds a **one half** span within the `narrow` area of the Porsche Grid." },
    gridWide: { name: "gridWide", value: "{\"columnStart\":\"wide-start\",\"columnEnd\":\"wide-end\"}", description: "Object containing all `wide` grid styles." },
    gridWideColumnEnd: { name: "gridWideColumnEnd", value: "wide-end", description: "Holds the **end** position of the `wide` area within the Porsche Grid." },
    gridWideColumnStart: { name: "gridWideColumnStart", value: "wide-start", description: "Holds the **start** position of the `wide` area within the Porsche Grid." },
    gridBasicOffset: { name: "gridBasicOffset", value: "{\"base\":\"max(22px, 10.625vw - 12px)\",\"s\":\"calc(calc(5vw - 16px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((100vw - calc(5vw - 16px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 2)\",\"xxl\":\"calc(max(0px, 50vw - 2560px / 2) + min(50vw - 880px, 400px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((min(100vw, 2560px) - min(50vw - 880px, 400px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 2)\"}", description: "Object containing all `basic` grid offset styles." },
    gridBasicOffsetS: { name: "gridBasicOffsetS", value: "calc(calc(5vw - 16px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((100vw - calc(5vw - 16px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 2)", description: "Holds a **small** offset within the `basic` area of the Porsche Grid." },
    gridBasicOffsetXXL: { name: "gridBasicOffsetXXL", value: "calc(max(0px, 50vw - 2560px / 2) + min(50vw - 880px, 400px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((min(100vw, 2560px) - min(50vw - 880px, 400px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 2)", description: "Holds a **xxl** offset within the `basic` area of the Porsche Grid." },
    gridExtendedOffset: { name: "gridExtendedOffset", value: "{\"base\":\"max(22px, 10.625vw - 12px)\",\"s\":\"calc(calc(5vw - 16px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((100vw - calc(5vw - 16px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 1)\",\"xxl\":\"calc(max(0px, 50vw - 2560px / 2) + min(50vw - 880px, 400px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((min(100vw, 2560px) - min(50vw - 880px, 400px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 1)\"}", description: "Object containing all `extended` grid offset styles." },
    gridExtendedOffsetS: { name: "gridExtendedOffsetS", value: "calc(calc(5vw - 16px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((100vw - calc(5vw - 16px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 1)", description: "Holds a **small** offset within the `extended` area of the Porsche Grid." },
    gridExtendedOffsetXXL: { name: "gridExtendedOffsetXXL", value: "calc(max(0px, 50vw - 2560px / 2) + min(50vw - 880px, 400px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((min(100vw, 2560px) - min(50vw - 880px, 400px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 1)", description: "Holds a **xxl** offset within the `extended` area of the Porsche Grid." },
    gridGap: { name: "gridGap", value: "clamp(16px, 1.25vw + 12px, 36px)", description: "Holds the grid **gap** of the Porsche Grid." },
    gridNarrowOffset: { name: "gridNarrowOffset", value: "{\"base\":\"max(22px, 10.625vw - 12px)\",\"s\":\"calc(calc(5vw - 16px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((100vw - calc(5vw - 16px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 4)\",\"xxl\":\"calc(max(0px, 50vw - 2560px / 2) + min(50vw - 880px, 400px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((min(100vw, 2560px) - min(50vw - 880px, 400px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 4)\"}", description: "Object containing all `narrow` grid offset styles." },
    gridNarrowOffsetS: { name: "gridNarrowOffsetS", value: "calc(calc(5vw - 16px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((100vw - calc(5vw - 16px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 4)", description: "Holds a **small** offset within the `narrow` area of the Porsche Grid." },
    gridNarrowOffsetXXL: { name: "gridNarrowOffsetXXL", value: "calc(max(0px, 50vw - 2560px / 2) + min(50vw - 880px, 400px) + (clamp(16px, 1.25vw + 12px, 36px) + calc((min(100vw, 2560px) - min(50vw - 880px, 400px) * 2 - clamp(16px, 1.25vw + 12px, 36px) * 15) / 16)) * 4)", description: "Holds a **xxl** offset within the `narrow` area of the Porsche Grid." },
    gridStyle: { name: "gridStyle", value: "{\"--pds-internal-grid-safe-zone\":\"max(22px, 10.625vw - 12px)\",\"--pds-grid-extended-span-one-half\":\"span 3\",\"--pds-grid-basic-span-one-half\":\"span 3\",\"--pds-grid-basic-span-one-third\":\"span 2\",\"--pds-grid-basic-span-two-thirds\":\"span 4\",\"--pds-grid-narrow-span-one-half\":\"span 3\",\"display\":\"grid\",\"gridGap\":\"clamp(16px, 1.25vw + 12px, 36px)\",\"gridTemplateColumns\":\"[full-start] minmax(0,var(--pds-internal-grid-outer-column,calc(var(--pds-internal-grid-safe-zone) - clamp(16px, 1.25vw + 12px, 36px)))) [wide-start extended-start basic-start narrow-start] repeat(6, minmax(0,1fr)) [narrow-end basic-end extended-end wide-end] minmax(0,var(--pds-internal-grid-outer-column,calc(var(--pds-internal-grid-safe-zone) - clamp(16px, 1.25vw + 12px, 36px)))) [full-end]\",\"minWidth\":\"var(--pds-internal-grid-width-min,320px)\",\"maxWidth\":\"var(--pds-internal-grid-width-max,2560px)\",\"margin\":\"0 var(--pds-internal-grid-margin,0)\",\"padding\":\"0 calc(50% - var(--pds-internal-grid-margin,0px) - 2560px / 2)\",\"boxSizing\":\"content-box\",\"@media\":{\"(min-width:760px)\":{\"display\":\"grid\",\"--pds-internal-grid-safe-zone\":\"calc(5vw - 16px)\",\"--pds-grid-extended-span-one-half\":\"span 7\",\"--pds-grid-basic-span-one-half\":\"span 6\",\"--pds-grid-basic-span-one-third\":\"span 4\",\"--pds-grid-basic-span-two-thirds\":\"span 8\",\"--pds-grid-narrow-span-one-half\":\"span 4\",\"gridTemplateColumns\":\"[full-start] minmax(0,var(--pds-internal-grid-outer-column,calc(var(--pds-internal-grid-safe-zone) - clamp(16px, 1.25vw + 12px, 36px)))) [wide-start] minmax(0,1fr) [extended-start] minmax(0,1fr) [basic-start] repeat(2, minmax(0,1fr)) [narrow-start] repeat(8, minmax(0,1fr)) [narrow-end] repeat(2, minmax(0,1fr)) [basic-end] minmax(0,1fr) [extended-end] minmax(0,1fr) [wide-end] minmax(0,var(--pds-internal-grid-outer-column,calc(var(--pds-internal-grid-safe-zone) - clamp(16px, 1.25vw + 12px, 36px)))) [full-end]\"},\"(min-width:1920px)\":{\"display\":\"grid\",\"--pds-internal-grid-safe-zone\":\"min(50vw - 880px, 400px)\"}}}", description: "Applies the **Porsche Grid** layout system (must be applied once at the top level, span the full viewport width, and cannot be nested)." },
    gridWideOffsetS: { name: "gridWideOffsetS", value: "calc(5vw - 16px)", description: "Holds a **small** offset within the `wide` area of the Porsche Grid." },
    gridBasicOffsetBase: { name: "gridBasicOffsetBase", value: "max(22px, 10.625vw - 12px)", description: "Holds a **base** offset within the `basic` area of the Porsche Grid." },
    gridExtendedOffsetBase: { name: "gridExtendedOffsetBase", value: "max(22px, 10.625vw - 12px)", description: "Holds a **base** offset within the `extended` area of the Porsche Grid." },
    gridNarrowOffsetBase: { name: "gridNarrowOffsetBase", value: "max(22px, 10.625vw - 12px)", description: "Holds a **base** offset within the `narrow` area of the Porsche Grid." },
    gridWideOffsetBase: { name: "gridWideOffsetBase", value: "max(22px, 10.625vw - 12px)", description: "Holds a **base** offset within the `wide` area of the Porsche Grid." },
    gridFullOffset: { name: "gridFullOffset", value: "max(0px, 50vw - 2560px / 2)", description: "Holds a **full** offset within the `full` area of the Porsche Grid." },
    gridWideOffset: { name: "gridWideOffset", value: "{\"base\":\"max(22px, 10.625vw - 12px)\",\"s\":\"calc(5vw - 16px)\",\"xxl\":\"calc(max(0px, 50vw - 2560px / 2) + min(50vw - 880px, 400px))\"}", description: "Object containing all `wide` grid offset styles." },
    gridWideOffsetXXL: { name: "gridWideOffsetXXL", value: "calc(max(0px, 50vw - 2560px / 2) + min(50vw - 880px, 400px))", description: "Holds a **xxl** offset within the `wide` area of the Porsche Grid." },
  },
  mediaQuery: {
    breakpoint: { name: "breakpoint", value: "{\"base\":0,\"xs\":480,\"s\":760,\"m\":1000,\"l\":1300,\"xl\":1760,\"xxl\":1920}", description: "Object containing all breakpoint values." },
    breakpoints: { name: "breakpoints", value: "[\"base\",\"xs\",\"s\",\"m\",\"l\",\"xl\",\"xxl\"]", description: "Array containing all breakpoint keys." },
    getMediaQueryMax: { name: "getMediaQueryMax('xs'|'s'|'m'|'l'|'xl'|'xxl')", description: "Returns a **max-width** media query string for the specified breakpoint." },
    getMediaQueryMin: { name: "getMediaQueryMin('base'|'xs'|'s'|'m'|'l'|'xl'|'xxl')", description: "Returns a **min-width** media query string for the specified breakpoint." },
    getMediaQueryMinMax: { name: "getMediaQueryMinMax('base'|'xs'|'s'|'m'|'l'|'xl', 'xs'|'s'|'m'|'l'|'xl'|'xxl')", description: "Returns a **min-width and max-width** media query string for the specified breakpoints." },
    breakpointBase: { name: "breakpointBase", value: 0, description: "Holds the `base` breakpoint value." },
    breakpointXS: { name: "breakpointXS", value: 480, description: "Holds the `xs` breakpoint value." },
    breakpointS: { name: "breakpointS", value: 760, description: "Holds the `s` breakpoint value." },
    breakpointM: { name: "breakpointM", value: 1000, description: "Holds the `m` breakpoint value." },
    breakpointL: { name: "breakpointL", value: 1300, description: "Holds the `l` breakpoint value." },
    breakpointXL: { name: "breakpointXL", value: 1760, description: "Holds the `xl` breakpoint value." },
    breakpointXXL: { name: "breakpointXXL", value: 1920, description: "Holds the `2xl` breakpoint value." },
  },
  motion: {
    duration: {
      durationSm: { name: "durationSm", value: ".25s", description: "Holds a **short** `transition-duration` / `animation-duration`." },
      durationMd: { name: "durationMd", value: ".4s", description: "Holds a **moderate** `transition-duration` / `animation-duration`." },
      durationLg: { name: "durationLg", value: ".6s", description: "Holds a **long** `transition-duration` / `animation-duration`." },
      durationXl: { name: "durationXl", value: "1.2s", description: "Holds a **very long** `transition-duration` / `animation-duration`." },
    },
    ease: {
      easeIn: { name: "easeIn", value: "cubic-bezier(0,0,.2,1)", description: "Holds an **in** `transition-timing-function`." },
      easeInOut: { name: "easeInOut", value: "cubic-bezier(.25,.1,.25,1)", description: "Holds an **in-out** `transition-timing-function`." },
      easeOut: { name: "easeOut", value: "cubic-bezier(.4,0,.5,1)", description: "Holds an **out** `transition-timing-function`." },
    },
    deprecated: {
      motionEasingBase: { name: "motionEasingBase", value: "cubic-bezier(.25,.1,.25,1)", description: "since v4.0.0, will be removed with next major release. Use easeInOut instead." },
      motionEasingIn: { name: "motionEasingIn", value: "cubic-bezier(0,0,.2,1)", description: "since v4.0.0, will be removed with next major release. Use easeIn instead." },
      motionEasingOut: { name: "motionEasingOut", value: "cubic-bezier(.4,0,.5,1)", description: "since v4.0.0, will be removed with next major release. Use easeOut instead." },
      motionDurationShort: { name: "motionDurationShort", value: ".25s", description: "since v4.0.0, will be removed with next major release. Use durationSm instead." },
      motionDurationModerate: { name: "motionDurationModerate", value: ".4s", description: "since v4.0.0, will be removed with next major release. Use durationMd instead." },
      motionDurationLong: { name: "motionDurationLong", value: ".6s", description: "since v4.0.0, will be removed with next major release. Use durationLg instead." },
      motionDurationVeryLong: { name: "motionDurationVeryLong", value: "1.2s", description: "since v4.0.0, will be removed with next major release. Use durationXl instead." },
    },
  },
  shadow: {
    shadowSm: { name: "shadowSm", value: "0px 3px 8px rgba(0,0,0,.16)", description: "Holds a **small** `box-shadow`." },
    shadowMd: { name: "shadowMd", value: "0px 4px 16px rgba(0,0,0,.16)", description: "Holds a **medium** `box-shadow`." },
    shadowLg: { name: "shadowLg", value: "0px 8px 40px rgba(0,0,0,.16)", description: "Holds a **large** `box-shadow`." },
    deprecated: {
      dropShadowHighStyle: { name: "dropShadowHighStyle", value: "{\"boxShadow\":\"0px 8px 40px rgba(0,0,0,.16)\"}", description: "since v4.0.0, will be removed with next major release. Use boxShadow: shadowLg instead." },
      dropShadowMediumStyle: { name: "dropShadowMediumStyle", value: "{\"boxShadow\":\"0px 4px 16px rgba(0,0,0,.16)\"}", description: "since v4.0.0, will be removed with next major release. Use boxShadow: shadowMd instead." },
      dropShadowLowStyle: { name: "dropShadowLowStyle", value: "{\"boxShadow\":\"0px 3px 8px rgba(0,0,0,.16)\"}", description: "since v4.0.0, will be removed with next major release. Use boxShadow: shadowSm instead." },
    },
  },
  skeleton: {
    getSkeletonStyle: { name: "getSkeletonStyle(animationName: string)", description: "Applies a skeleton placeholder style to indicate loading state." },
    skeletonKeyframes: { name: "skeletonKeyframes", value: "{\"from\":{\"backgroundPositionX\":\"100%\"},\"to\":{\"backgroundPositionX\":\"-100%\"}}", description: "Holds the **keyframes** to be used with the `keyframes` vanilla-extract function." },
  },
  spacing: {
    fluid: {
      spacingFluidXs: { name: "spacingFluidXs", value: "clamp(4px, 0.25vw + 3px, 8px)", description: "Holds the **x-small fluid** spacing." },
      spacingFluidSm: { name: "spacingFluidSm", value: "clamp(8px, 0.5vw + 6px, 16px)", description: "Holds the **small fluid** spacing." },
      spacingFluidMd: { name: "spacingFluidMd", value: "clamp(16px, 1.25vw + 12px, 36px)", description: "Holds the **medium fluid** spacing." },
      spacingFluidLg: { name: "spacingFluidLg", value: "clamp(32px, 2.75vw + 23px, 76px)", description: "Holds the **large fluid** spacing." },
      spacingFluidXl: { name: "spacingFluidXl", value: "clamp(48px, 3vw + 38px, 96px)", description: "Holds the **x-large fluid** spacing." },
      spacingFluid2Xl: { name: "spacingFluid2Xl", value: "clamp(80px, 7.5vw + 56px, 200px)", description: "Holds the **2x-large fluid** spacing." },
    },
    static: {
      spacingStatic2Xs: { name: "spacingStatic2Xs", value: "1px", description: "Holds the **2x-small static** spacing." },
      spacingStaticXs: { name: "spacingStaticXs", value: "4px", description: "Holds the **x-small static** spacing." },
      spacingStaticSm: { name: "spacingStaticSm", value: "8px", description: "Holds the **small static** spacing." },
      spacingStaticMd: { name: "spacingStaticMd", value: "16px", description: "Holds the **medium static** spacing." },
      spacingStaticLg: { name: "spacingStaticLg", value: "32px", description: "Holds the **large static** spacing." },
      spacingStaticXl: { name: "spacingStaticXl", value: "48px", description: "Holds the **x-large static** spacing." },
      spacingStatic2Xl: { name: "spacingStatic2Xl", value: "80px", description: "Holds the **2x-large static** spacing." },
    },
    deprecated: {
      spacing: { name: "spacing", value: "{\"static\":{\"xSmall\":\"4px\",\"small\":\"8px\",\"medium\":\"16px\",\"large\":\"32px\",\"xLarge\":\"48px\",\"xxLarge\":\"80px\"},\"fluid\":{\"xSmall\":\"clamp(4px, 0.25vw + 3px, 8px)\",\"small\":\"clamp(8px, 0.5vw + 6px, 16px)\",\"medium\":\"clamp(16px, 1.25vw + 12px, 36px)\",\"large\":\"clamp(32px, 2.75vw + 23px, 76px)\",\"xLarge\":\"clamp(48px, 3vw + 38px, 96px)\",\"xxLarge\":\"clamp(80px, 7.5vw + 56px, 200px)\"}}", description: "since v4.0.0, will be removed with next major release. Use spacing variables directly instead." },
      spacingFluid: { name: "spacingFluid", value: "{\"xSmall\":\"clamp(4px, 0.25vw + 3px, 8px)\",\"small\":\"clamp(8px, 0.5vw + 6px, 16px)\",\"medium\":\"clamp(16px, 1.25vw + 12px, 36px)\",\"large\":\"clamp(32px, 2.75vw + 23px, 76px)\",\"xLarge\":\"clamp(48px, 3vw + 38px, 96px)\",\"xxLarge\":\"clamp(80px, 7.5vw + 56px, 200px)\"}", description: "since v4.0.0, will be removed with next major release. Use spacing variables directly instead." },
      spacingFluidXSmall: { name: "spacingFluidXSmall", value: "clamp(4px, 0.25vw + 3px, 8px)", description: "since v4.0.0, will be removed with next major release. Use spacingFluidXs instead." },
      spacingStaticXSmall: { name: "spacingStaticXSmall", value: "4px", description: "since v4.0.0, will be removed with next major release. Use spacingStaticXs instead." },
      spacingFluidSmall: { name: "spacingFluidSmall", value: "clamp(8px, 0.5vw + 6px, 16px)", description: "since v4.0.0, will be removed with next major release. Use spacingFluidSm instead." },
      spacingStaticSmall: { name: "spacingStaticSmall", value: "8px", description: "since v4.0.0, will be removed with next major release. Use spacingStaticSm instead." },
      spacingFluidMedium: { name: "spacingFluidMedium", value: "clamp(16px, 1.25vw + 12px, 36px)", description: "since v4.0.0, will be removed with next major release. Use spacingFluidMd instead." },
      spacingStaticMedium: { name: "spacingStaticMedium", value: "16px", description: "since v4.0.0, will be removed with next major release. Use spacingStaticMd instead." },
      spacingFluidLarge: { name: "spacingFluidLarge", value: "clamp(32px, 2.75vw + 23px, 76px)", description: "since v4.0.0, will be removed with next major release. Use spacingFluidLg instead." },
      spacingStaticLarge: { name: "spacingStaticLarge", value: "32px", description: "since v4.0.0, will be removed with next major release. Use spacingStaticLg instead." },
      spacingFluidXLarge: { name: "spacingFluidXLarge", value: "clamp(48px, 3vw + 38px, 96px)", description: "since v4.0.0, will be removed with next major release. Use spacingFluidXl instead." },
      spacingStaticXLarge: { name: "spacingStaticXLarge", value: "48px", description: "since v4.0.0, will be removed with next major release. Use spacingStaticXl instead." },
      spacingFluidXXLarge: { name: "spacingFluidXXLarge", value: "clamp(80px, 7.5vw + 56px, 200px)", description: "since v4.0.0, will be removed with next major release. Use spacingFluid2Xl instead." },
      spacingStatic: { name: "spacingStatic", value: "{\"xSmall\":\"4px\",\"small\":\"8px\",\"medium\":\"16px\",\"large\":\"32px\",\"xLarge\":\"48px\",\"xxLarge\":\"80px\"}", description: "since v4.0.0, will be removed with next major release. Use spacing variables directly instead." },
      spacingStaticXXLarge: { name: "spacingStaticXXLarge", value: "80px", description: "since v4.0.0, will be removed with next major release. Use spacingStatic2Xl instead." },
    },
  },
  typography: {
    proseHeading5XlStyle: { name: "proseHeading5XlStyle", description: "Applies the **5x-large** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseText5XlStyle: { name: "proseText5XlStyle", description: "Applies the **5x-large** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeading4XlStyle: { name: "proseHeading4XlStyle", description: "Applies the **4x-large** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseText4XlStyle: { name: "proseText4XlStyle", description: "Applies the **4x-large** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeading3XlStyle: { name: "proseHeading3XlStyle", description: "Applies the **3x-large** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseText3XlStyle: { name: "proseText3XlStyle", description: "Applies the **3x-large** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeading2XlStyle: { name: "proseHeading2XlStyle", description: "Applies the **2x-large** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseText2XlStyle: { name: "proseText2XlStyle", description: "Applies the **2x-large** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeadingXlStyle: { name: "proseHeadingXlStyle", description: "Applies the **x-large** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseTextXlStyle: { name: "proseTextXlStyle", description: "Applies the **x-large** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeadingLgStyle: { name: "proseHeadingLgStyle", description: "Applies the **large** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseTextLgStyle: { name: "proseTextLgStyle", description: "Applies the **large** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeadingMdStyle: { name: "proseHeadingMdStyle", description: "Applies the **medium** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseTextMdStyle: { name: "proseTextMdStyle", description: "Applies the **medium** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeadingSmStyle: { name: "proseHeadingSmStyle", description: "Applies the **small** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseTextSmStyle: { name: "proseTextSmStyle", description: "Applies the **small** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeadingXsStyle: { name: "proseHeadingXsStyle", description: "Applies the **x-small** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseTextXsStyle: { name: "proseTextXsStyle", description: "Applies the **x-small** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    proseHeading2XsStyle: { name: "proseHeading2XsStyle", description: "Applies the **2x-small** heading typography variant primarily to `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` tags." },
    proseText2XsStyle: { name: "proseText2XsStyle", description: "Applies the **2x-small** text typography variant primarily to `<p>`, `<ul>`, `<ol>`, `<blockquote>` tags." },
    deprecated: {
      display: {
        displayLargeStyle: { name: "displayLargeStyle", description: "since v4.0.0, will be removed with next major release. Use proseHeading5XlStyle instead." },
        displayMediumStyle: { name: "displayMediumStyle", description: "since v4.0.0, will be removed with next major release. Use proseHeading4XlStyle instead." },
        displaySmallStyle: { name: "displaySmallStyle", description: "since v4.0.0, will be removed with next major release. Use proseHeading3XlStyle instead." },
      },
      heading: {
        headingLargeStyle: { name: "headingLargeStyle", description: "since v4.0.0, will be removed with next major release. Use proseHeadingLg instead." },
        headingMediumStyle: { name: "headingMediumStyle", description: "since v4.0.0, will be removed with next major release. Use proseHeadingMd instead." },
        headingSmallStyle: { name: "headingSmallStyle", description: "since v4.0.0, will be removed with next major release. Use proseHeadingSm instead." },
        headingXLargeStyle: { name: "headingXLargeStyle", description: "since v4.0.0, will be removed with next major release. Use proseHeadingXl instead." },
        headingXXLargeStyle: { name: "headingXXLargeStyle", description: "since v4.0.0, will be removed with next major release. Use proseHeading2Xl instead." },
      },
      text: {
        textLargeStyle: { name: "textLargeStyle", description: "since v4.0.0, will be removed with next major release. Use proseTextLg instead." },
        textMediumStyle: { name: "textMediumStyle", description: "since v4.0.0, will be removed with next major release. Use proseTextMd instead." },
        textSmallStyle: { name: "textSmallStyle", description: "since v4.0.0, will be removed with next major release. Use proseTextSm instead." },
        textXLargeStyle: { name: "textXLargeStyle", description: "since v4.0.0, will be removed with next major release. Use proseTextXl instead." },
        textXSmallStyle: { name: "textXSmallStyle", description: "since v4.0.0, will be removed with next major release. Use proseTextXs instead." },
        textXXSmallStyle: { name: "textXXSmallStyle", description: "since v4.0.0, will be removed with next major release. Use proseText2Xs instead." },
      },
    },
  },
} satisfies VanillaExtractMetaTree;
