floatPrecision: 3
plugins:
  - removeViewBox: false # ensures view box is not changed
  - removeDimensions: true # ensures custom width + height is settable by addAttributesToSVGElement plugin
  - sortAttrs: true # sort element attributes for epic readability
  - removeAttrs:
      attrs: '(stroke|fill)' # ensures coloring is applicable by CSS
  - addAttributesToSVGElement:
      attributes:
        - width: '100%' # ensures optimal scaling behaviour
        - height: '100%' # ensures optimal scaling behaviour
        - focusable: false # disables focus in IE11
  - convertPathData: { noSpaceAfterFlags: false }
  - mergePaths: { noSpaceAfterFlags: false }
