name: 'Pull Request'

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
  # test:
  #   name: 'Test'
  #   uses: ./.github/workflows/test.yml
  #   needs:
  #     - build