name: 'Pull Request'

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
    with:
      image: mcr.microsoft.com/playwright:v1.49.1
  test:
    name: 'Test'
    uses: ./.github/workflows/test.yml
    with:
      image: mcr.microsoft.com/playwright:v1.49.1
    needs:
      - build