import { IconName } from '../../types';

export type SocialIconName = Extract<
  IconName,
  | 'logo-facebook'
  | 'logo-google'
  | 'logo-instagram'
  | 'logo-linkedin'
  | 'logo-pinterest'
  | 'logo-twitter'
  | 'logo-wechat'
  | 'logo-whatsapp'
  | 'logo-xing'
  | 'logo-youtube'
  | 'logo-baidu'
  | 'logo-delicious'
  | 'logo-digg'
  | 'logo-foursquare'
  | 'logo-gmail'
  | 'logo-hatena'
  | 'logo-kaixin'
  | 'logo-kakaotalk'
  | 'logo-naver'
  | 'logo-qq-share'
  | 'logo-qq'
  | 'logo-reddit'
  | 'logo-skyrock'
  | 'logo-sohu'
  | 'logo-tecent'
  | 'logo-telegram'
  | 'logo-tiktok'
  | 'logo-tumblr'
  | 'logo-viber'
  | 'logo-vk'
  | 'logo-weibo'
  | 'logo-yahoo'
  | 'logo-youku'
>;
